from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import PE1World




ITEM_NAME_TO_ID = {
    "Ammo +6": 1,
    "Ammo +15": 2,
    "Ammo +30": 3,
    "DNA Bullets": 4,
    "Rocket": 5,
    "Medicine 1": 6,
    "Medicine 2": 7,
    "Medicine 3": 8,
    "Medicine 4": 9,
    "Full Recovery": 10,
    "Super Junk": 11,
    "Duper Junk": 12,
    "Cure-P": 13,
    "Cure-D": 14,
    "Cure-C": 15,
    "Cure-M": 16,
    "FullCure": 17,
    "Revive": 18,
    #Defense +1": 19,
    "Junk": 20,
    "Trading Card": 21,
    "Tool": 22,
    "Super Tool": 23,
    #Item24": 24,
    #Item25": 25,
    #Ammo Crate": 26,
    #Rocket Crate": 27,
    #Maeda Crate": 28,
    "Offense +1": 29,
    "Offense +2": 30,
    "Offense +3": 31,
    "Offense +4": 32,
    "Range +1": 33,
    "Range +2": 34,
    "Range +3": 35,
    "Range +4": 36,
    "Bullet Cap +1": 37,
    "Bullet Cap +2": 38,
    "Bullet Cap +3": 39,
    "Bullet Cap +4": 40,
    "Defense +1": 41,
    "Defense +2": 42,
    "Defense +3": 43,
    "Defense +4": 44,
    "Cr Evade +1":45,
    "Cr Evade +2":46,
    "Cr Evade +3":47,
    "Cr Evade +4":48,
    "PE +1": 49,
    "PE +2": 50,
    "PE +3": 51,
    "PE +4": 52,
    "Tool Kit": 53,
    "Super Tool Kit": 54,
    "Mod Permit": 55,
    "Chrysler Key 1": 56,
    "Chrysler Key 2": 57,
    "Chrysler Key 3": 58,
    "Chrysler Key 4": 59,
    "Chrysler Key 5": 60,
    "Chrysler Key 6": 61,
    "Chrysler Key 7": 62,

    "Club 1": 63,
    "Club 2": 64,
    "Club 3": 65,
    "Club 4": 66,
    "Club 5": 67,
    "M84F": 68,
    "M9": 69,
    "M9-2": 70,
    "M9-3": 71,
    "M8000": 72,
    "M96": 73,
    "M96R": 74,
    "P220": 75,
    "P220-2": 76,
    "P228": 77,
    "P226": 78,
    "P229": 79,
    "M1911A1": 80,
    "M1911A2": 81,
    "M1911A3": 82,
    "M1911A4": 83,
    "M1911A5": 84,
    "P8": 85,
    "USP": 86,
    "USP-2": 87,
    "USP-3": 88,
    "Mark 23": 89,
    "G19": 90,
    "G23": 91,
    "G22": 92,
    "G20": 93,
    "M712": 94,
    "PPK": 95,
    "AM44": 96,
    "Maeda's Gun": 97,
    "PPSh41": 98,
    "SP1C": 99,
    "USP-TU": 100,
    "AK-47": 101,
    "DE50AE7": 102,
    #Debug SMG": 103,
    "M870": 104,
    "M870-2": 105,
    "M500": 106,
    "M500-2": 107,
    "Maverick": 108,
    "S12": 109,
    "M10B": 110,
    "M11": 111,
    "M10": 112,
    "MP5K": 113,
    "MP5PDW": 114,
    "MP5A5": 115,
    "MP5SD6": 116,
    "Micro UZ": 117,
    "Mini UZ": 118,
    "Full UZ": 119,
    "P90": 120,
    "M16A1": 121,
    "M16A2": 122,
    "SG550": 123,
    "SAR": 124,
    "G3A3": 125,
    "Type64": 126,
    "XM177E2": 127,
    "PSG-1": 128,
    "FA-MAS": 129,
    "MAG": 130,
    "M203": 131,
    "M203-2": 132,
    "M203-3": 133,
    "M203-4": 134,
    "M203-5": 135,
    "M203-6": 136,
    "M79": 137,
    "M79-2": 138,
    "M79-3": 139,
    "M79-4": 140,
    "M79-5": 141,
    "M79-6": 142,
    "HK40": 143,
    "AT4": 144,
    "AT4-1": 145,
    "LAW80": 146,
    #Maeda's Gun WB": 147,
    "M92F": 148,
    "Dress": 149,
    "N Vest": 150,
    "N Protector": 151,
    "N Jacket": 152,
    "N Suit": 153,
    "N Armor": 154,
    "Kv Vest 1": 155,
    "Kv Protector": 156,
    "Kv Jacket": 157,
    "Kv Suit 1": 158,
    "Kv Armor 1": 159,
    "Sp Vest 1": 160,
    "Sp Vest 2": 161,
    "Sp Protector": 162,
    "Sp Jacket": 163,
    "Sp Suit 1": 164,
    "Sp Suit 2": 165,
    "Sp Armor 1": 166,
    "Sp Armor 2": 167,
    "Sv Vest 1": 168,
    "Sv Vest 2": 169,
    "Sv Protector": 170,
    "Sv Jacket": 171,
    "Sv Suit 1": 172,
    "Sv Suit 2": 173,
    "Sv Armor 1": 174,
    "Sv Armor 2": 175,
    "Cr Vest 1": 176,
    "Cr Vest 2": 177,
    "Cr Protector": 178,
    "Cr Jacket": 179,
    "Cr Suit 1": 180,
    "Cr Suit 2": 181,
    "Cr Armor 1": 182,
    "Cr Armor 2": 183,
    "B Vest 1": 184,
    "B Vest 2": 185,
    "B Protector": 186,
    "B Jacket 1": 187,
    "B Jacket 2": 188,
    "B Suit 1": 189,
    "B Suit 2": 190,
    "B Armor": 191,
    "Cm Vest 1": 192,
    "Cm Vest 2": 193,
    "Cm Protector": 194,
    "Cm Jacket": 195,
    "Cm Suit 1": 196,
    "Cm Armor 1": 197,
    "Cm Armor 2": 198,
    #Cm Suit 2": 199,

    "Theater Key": 200,
    "Rehearse Key": 201,
    "Zoo Key": 202,
    "Narita": 203,
    "Mayoke": 204,
    "Hamaya": 205,
    "Fuse 1": 206,
    "Fuse 2": 207,
    "Fuse 3": 208,
    "Autopsy Key": 209,
    "Blue Cardkey": 210,
    "Green Cardkey": 211,
    "Pump Key": 212,
    "Klamp Key": 213,
    "Storage Key": 214,
    "Locker Key": 215,
    "Weapon Memo": 216,
    #Medal": 217,
    "Elevator Key": 218,
    "Gate Key": 219,
    "Warehouse Key": 220,
    "GSP T Card": 221,
    "P38 T Card": 222,
    "Bhawk T Card": 223,
    "Kasul T Card": 224,
    "PPKS T Card": 225,
    "M1 T Card": 226,
    "MK5 T Card": 227,
    "MP44 T Card": 228,
    "BAR T Card": 229,
    "MG42 T Card": 230,
    "M29 T Card": 231,
    "M73 T Card": 232,
    "Type38 T Card": 233,
    "Type3 T Card": 234,
    "Eagle T Card": 235,

    "Heal 1": 236,
    "Heal 2": 237,
    "Heal 3": 238,
    "Detox": 239,
    "Medic": 240,
    "Barrier": 241,
    "Energy Shot": 242,
    "Scan": 243,
    "Slow": 244,
    "Haste": 245,
    "Confuse": 246,
    "Gene Heal": 247,
    "Preraise": 248,
    #mito14": 249,
    #mito15": 250,
    #mito16": 251,
    #mito17": 252,
    #mito18": 253,
    "Full Recover": 254,
    "Liberate": 255,

    "Area: Carnegie Hall": 256,
    "Area: N.Y.P.D. #17": 257,
    "Area: Central Park": 258,
    "Area: Soho": 259,
    "Area: Hospital": 260,
    "Area: Chinatown": 261,
    "Area: Subway": 262,
    "Area: Warehouse": 263,
    "Area: Museum": 264,
    "Area: Chrysler BLDG.": 265,

    "Confusion Trap": 266,
    "Darkness Trap": 267,
    "Silence Trap": 268,
    "Impact Trap": 269,
}


DEFAULT_ITEM_CLASSIFICATIONS = {
    "Ammo +6": ItemClassification.filler,
    "Ammo +15": ItemClassification.filler,
    "Ammo +30": ItemClassification.useful,
    "DNA Bullets": ItemClassification.useful,
    "Rocket": ItemClassification.useful,
    "Medicine 1": ItemClassification.filler,
    "Medicine 2": ItemClassification.useful,
    "Medicine 3": ItemClassification.useful,
    "Medicine 4": ItemClassification.useful,
    "Full Recovery": ItemClassification.useful,
    "Super Junk": ItemClassification.progression,
    "Duper Junk": ItemClassification.filler,
    "Cure-P": ItemClassification.useful,
    "Cure-D": ItemClassification.useful,
    "Cure-C": ItemClassification.filler,
    "Cure-M": ItemClassification.useful,
    "FullCure": ItemClassification.useful,
    "Revive": ItemClassification.useful,
    #Defense +1": "Unused duplicate Defense 1, unable to be used.",
    "Junk": ItemClassification.filler,
    "Trading Card": ItemClassification.filler,
    "Tool": ItemClassification.useful,
    "Super Tool": ItemClassification.useful,
    #Item24": "Unused item. Consumable, but has no effect.",
    #Item25": "Unused item. Consumable, but has no effect.",
    #Ammo Crate": "Crate is automatically given upon receiving its ammo.",
    #Rocket Crate": "Crate is automatically given upon receiving its ammo.",
    #Maeda Crate": "Crate is automatically given upon receiving its ammo.",
    "Offense +1": ItemClassification.filler,
    "Offense +2": ItemClassification.useful,
    "Offense +3": ItemClassification.useful,
    "Offense +4": ItemClassification.useful,
    "Range +1": ItemClassification.filler,
    "Range +2": ItemClassification.useful,
    "Range +3": ItemClassification.useful,
    "Range +4": ItemClassification.useful,
    "Bullet Cap +1": ItemClassification.filler,
    "Bullet Cap +2": ItemClassification.useful,
    "Bullet Cap +3": ItemClassification.useful,
    "Bullet Cap +4": ItemClassification.useful,
    "Defense +1": ItemClassification.filler,
    "Defense +2": ItemClassification.useful,
    "Defense +3": ItemClassification.useful,
    "Defense +4": ItemClassification.useful,
    "Cr Evade +1":ItemClassification.filler,
    "Cr Evade +2":ItemClassification.useful,
    "Cr Evade +3":ItemClassification.useful,
    "Cr Evade +4":ItemClassification.useful,
    "PE +1": ItemClassification.filler,
    "PE +2": ItemClassification.useful,
    "PE +3": ItemClassification.useful,
    "PE +4": ItemClassification.useful,
    "Tool Kit": ItemClassification.useful,
    "Super Tool Kit": ItemClassification.useful,
    "Mod Permit": ItemClassification.useful,
    "Chrysler Key 1": ItemClassification.progression,
    "Chrysler Key 2": ItemClassification.progression,
    "Chrysler Key 3": ItemClassification.progression,
    "Chrysler Key 4": ItemClassification.progression,
    "Chrysler Key 5": ItemClassification.progression,
    "Chrysler Key 6": ItemClassification.progression,
    "Chrysler Key 7": ItemClassification.progression,

    "Club 1": ItemClassification.useful,
    "Club 2": ItemClassification.useful,
    "Club 3": ItemClassification.useful,
    "Club 4": ItemClassification.progression,
    "Club 5": ItemClassification.progression,
    "M84F": ItemClassification.useful,
    "M9": ItemClassification.useful,
    "M9-2": ItemClassification.useful,
    "M9-3": ItemClassification.progression,
    "M8000": ItemClassification.progression,
    "M96": ItemClassification.useful,
    "M96R": ItemClassification.progression,
    "P220": ItemClassification.useful,
    "P220-2": ItemClassification.useful,
    "P228": ItemClassification.useful,
    "P226": ItemClassification.useful,
    "P229": ItemClassification.useful,
    "M1911A1": ItemClassification.useful,
    "M1911A2": ItemClassification.useful,
    "M1911A3": ItemClassification.useful,
    "M1911A4": ItemClassification.useful,
    "M1911A5": ItemClassification.useful,
    "P8": ItemClassification.useful,
    "USP": ItemClassification.useful,
    "USP-2": ItemClassification.useful,
    "USP-3": ItemClassification.useful,
    "Mark 23": ItemClassification.useful,
    "G19": ItemClassification.useful,
    "G23": ItemClassification.useful,
    "G22": ItemClassification.useful,
    "G20": ItemClassification.useful,
    "M712": ItemClassification.useful,
    "PPK": ItemClassification.progression,
    "AM44": ItemClassification.useful,
    "Maeda's Gun": ItemClassification.useful,
    "PPSh41": ItemClassification.useful,
    "SP1C": ItemClassification.useful,
    "USP-TU": ItemClassification.useful,
    "AK-47": ItemClassification.useful,
    "DE50AE7": ItemClassification.useful,
    #Debug SMG": "Completely busted plus stats, not using.",
    "M870": ItemClassification.useful,
    "M870-2": ItemClassification.useful,
    "M500": ItemClassification.useful,
    "M500-2": ItemClassification.useful,
    "Maverick": ItemClassification.progression,
    "S12": ItemClassification.useful,
    "M10B": ItemClassification.useful,
    "M11": ItemClassification.useful,
    "M10": ItemClassification.useful,
    "MP5K": ItemClassification.useful,
    "MP5PDW": ItemClassification.useful,
    "MP5A5": ItemClassification.progression,
    "MP5SD6": ItemClassification.useful,
    "Micro UZ": ItemClassification.useful,
    "Mini UZ": ItemClassification.useful,
    "Full UZ": ItemClassification.useful,
    "P90": ItemClassification.useful,
    "M16A1": ItemClassification.useful,
    "M16A2": ItemClassification.useful,
    "SG550": ItemClassification.useful,
    "SAR": ItemClassification.useful,
    "G3A3": ItemClassification.useful,
    "Type64": ItemClassification.progression,
    "XM177E2": ItemClassification.useful,
    "PSG-1": ItemClassification.useful,
    "FA-MAS": ItemClassification.useful,
    "MAG": ItemClassification.useful,
    "M203": ItemClassification.useful,
    "M203-2": ItemClassification.useful,
    "M203-3": ItemClassification.progression,
    "M203-4": ItemClassification.useful,
    "M203-5": ItemClassification.useful,
    "M203-6": ItemClassification.useful,
    "M79": ItemClassification.progression,
    "M79-2": ItemClassification.useful,
    "M79-3": ItemClassification.useful,
    "M79-4": ItemClassification.useful,
    "M79-5": ItemClassification.useful,
    "M79-6": ItemClassification.useful,
    "HK40": ItemClassification.useful,
    "AT4": ItemClassification.useful,
    "AT4-1": ItemClassification.useful,
    "LAW80": ItemClassification.progression,
    #Maeda's Gun WB": "Loaded variant for final fight, excluded.",
    "M92F": ItemClassification.useful,
    "Dress": ItemClassification.useful,
    "N Vest": ItemClassification.useful,
    "N Protector": ItemClassification.useful,
    "N Jacket": ItemClassification.useful,
    "N Suit": ItemClassification.useful,
    "N Armor": ItemClassification.useful,
    "Kv Vest 1": ItemClassification.useful,
    "Kv Protector": ItemClassification.useful,
    "Kv Jacket": ItemClassification.useful,
    "Kv Suit 1": ItemClassification.useful,
    "Kv Armor 1": ItemClassification.useful,
    "Sp Vest 1": ItemClassification.useful,
    "Sp Vest 2": ItemClassification.useful,
    "Sp Protector": ItemClassification.useful,
    "Sp Jacket": ItemClassification.useful,
    "Sp Suit 1": ItemClassification.useful,
    "Sp Suit 2": ItemClassification.useful,
    "Sp Armor 1": ItemClassification.useful,
    "Sp Armor 2": ItemClassification.progression,
    "Sv Vest 1": ItemClassification.useful,
    "Sv Vest 2": ItemClassification.useful,
    "Sv Protector": ItemClassification.useful,
    "Sv Jacket": ItemClassification.useful,
    "Sv Suit 1": ItemClassification.useful,
    "Sv Suit 2": ItemClassification.useful,
    "Sv Armor 1": ItemClassification.progression,
    "Sv Armor 2": ItemClassification.useful,
    "Cr Vest 1": ItemClassification.useful,
    "Cr Vest 2": ItemClassification.useful,
    "Cr Protector": ItemClassification.progression,
    "Cr Jacket": ItemClassification.useful,
    "Cr Suit 1": ItemClassification.useful,
    "Cr Suit 2": ItemClassification.useful,
    "Cr Armor 1": ItemClassification.useful,
    "Cr Armor 2": ItemClassification.useful,
    "B Vest 1": ItemClassification.progression,
    "B Vest 2": ItemClassification.useful,
    "B Protector": ItemClassification.progression,
    "B Jacket 1": ItemClassification.useful,
    "B Jacket 2": ItemClassification.progression,
    "B Suit 1": ItemClassification.useful,
    "B Suit 2": ItemClassification.progression,
    "B Armor": ItemClassification.useful,
    "Cm Vest 1": ItemClassification.progression,
    "Cm Vest 2": ItemClassification.useful,
    "Cm Protector": ItemClassification.useful,
    "Cm Jacket": ItemClassification.useful,
    "Cm Suit 1": ItemClassification.progression,
    "Cm Armor 1": ItemClassification.useful,
    "Cm Armor 2": ItemClassification.progression,
    #Cm Suit 2": "Armor-equivalent of Debug SMG, excluded.",

    "Theater Key": ItemClassification.progression,
    "Rehearse Key": ItemClassification.progression,
    "Zoo Key": ItemClassification.progression,
    "Narita": ItemClassification.progression,
    "Mayoke": ItemClassification.progression,
    "Hamaya": ItemClassification.progression,
    "Fuse 1": ItemClassification.progression,
    "Fuse 2": ItemClassification.progression,
    "Fuse 3": ItemClassification.progression,
    "Autopsy Key": ItemClassification.progression,
    "Blue Cardkey": ItemClassification.progression,
    "Green Cardkey": ItemClassification.progression,
    "Pump Key": ItemClassification.progression,
    "Klamp Key": ItemClassification.progression,
    "Storage Key": ItemClassification.progression,
    "Locker Key": ItemClassification.progression,
    "Weapon Memo": ItemClassification.progression,
    #Medal": ItemClassification.progression (soon?),
    "Elevator Key": ItemClassification.progression,
    "Gate Key": ItemClassification.progression,
    "Warehouse Key": ItemClassification.progression,
    "GSP T Card": ItemClassification.progression,
    "P38 T Card": ItemClassification.progression,
    "Bhawk T Card": ItemClassification.progression,
    "Kasul T Card": ItemClassification.progression,
    "PPKS T Card": ItemClassification.progression,
    "M1 T Card": ItemClassification.progression,
    "MK5 T Card": ItemClassification.progression,
    "MP44 T Card": ItemClassification.progression,
    "BAR T Card": ItemClassification.progression,
    "MG42 T Card": ItemClassification.progression,
    "M29 T Card": ItemClassification.progression,
    "M73 T Card": ItemClassification.progression,
    "Type38 T Card": ItemClassification.progression,
    "Type3 T Card": ItemClassification.progression,
    "Eagle T Card": ItemClassification.progression,

    "Heal 1": ItemClassification.progression,
    "Heal 2": ItemClassification.progression,
    "Heal 3": ItemClassification.progression,
    "Detox": ItemClassification.progression,
    "Medic": ItemClassification.progression,
    "Barrier": ItemClassification.progression,
    "Energy Shot": ItemClassification.progression,
    "Scan": ItemClassification.useful,
    "Slow": ItemClassification.useful,
    "Haste": ItemClassification.progression,
    "Confuse": ItemClassification.useful,
    "Gene Heal": ItemClassification.useful,
    "Preraise": ItemClassification.progression,
    #mito14": "Unused PE, has an animation, but no cost or effect.",
    #mito15": "Unused PE, has an animation, but no cost or effect.",
    #mito16": "Unused PE, has an animation, but no cost or effect.",
    #mito17": "Unused PE, has an animation, but no cost or effect.",
    #mito18": "Unused PE, has an animation, but no cost or effect.",
    "Full Recover": ItemClassification.progression,
    "Liberate": ItemClassification.progression,

    "Area: Carnegie Hall": ItemClassification.progression,
    "Area: N.Y.P.D. #17": ItemClassification.progression,
    "Area: Central Park": ItemClassification.progression,
    "Area: Soho": ItemClassification.progression,
    "Area: Hospital": ItemClassification.progression,
    "Area: Chinatown": ItemClassification.progression,
    "Area: Subway": ItemClassification.progression,
    "Area: Warehouse": ItemClassification.progression,
    "Area: Museum": ItemClassification.progression,
    "Area: Chrysler BLDG.": ItemClassification.progression,

    "Confusion Trap": ItemClassification.trap,
    "Darkness Trap": ItemClassification.trap,
    "Silence Trap": ItemClassification.trap,
    "Impact Trap": ItemClassification.trap,
}


class PE1Item(Item):
    game = "Parasite Eve"




def get_random_filler_item_name(world: PE1World) -> str:

    return "Junk"




def create_item_with_correct_classification(world: PE1World, name: str) -> PE1Item:

    classification = DEFAULT_ITEM_CLASSIFICATIONS[name]

    # Come back to change ItemClassification on items for different settings.

    return PE1Item(name, classification, ITEM_NAME_TO_ID[name], world.player)




def create_all_items(world: PE1World) -> None:

    itempool: list[Item] = [
        world.create_item("Ammo +15"),
        world.create_item("Ammo +30"),
        world.create_item("Ammo +30"),
        world.create_item("DNA Bullets"),
        world.create_item("Rocket"),
        world.create_item("Medicine 2"),
        world.create_item("Medicine 2"),
        world.create_item("Medicine 2"),
        world.create_item("Medicine 2"),
        world.create_item("Medicine 3"),
        world.create_item("Medicine 3"),
        world.create_item("Medicine 4"),
        world.create_item("Super Junk"),
        world.create_item("Cure-P"),
        world.create_item("Cure-D"),
        world.create_item("Cure-M"),
        world.create_item("Revive"),
        world.create_item("Junk"),
        world.create_item("Junk"),
        world.create_item("Junk"),
        world.create_item("Junk"),
        world.create_item("Junk"),
        world.create_item("Trading Card"),
        world.create_item("Tool"),
        world.create_item("Tool"),
        world.create_item("Tool"),
        world.create_item("Tool"),
        world.create_item("Tool"),
        world.create_item("Super Tool"),
        world.create_item("Offense +1"),
        world.create_item("Offense +2"),
        world.create_item("Offense +2"),
        world.create_item("Offense +3"),
        world.create_item("Range +1"),
        world.create_item("Range +2"),
        world.create_item("Range +3"),
        world.create_item("Defense +1"),
        world.create_item("Defense +2"),
        world.create_item("Defense +2"),
        world.create_item("Defense +3"),
        world.create_item("PE +1"),
        world.create_item("PE +2"),
        world.create_item("PE +2"),
        world.create_item("PE +3"),
        world.create_item("Mod Permit"),
        world.create_item("Mod Permit"),
        world.create_item("Club 4"),
        world.create_item("Club 5"),
        world.create_item("M9-3"),
        world.create_item("M8000"),
        world.create_item("M96R"),
        world.create_item("PPK"),
        world.create_item("Maverick"),
        world.create_item("MP5A5"),
        world.create_item("Type64"),
        world.create_item("M203-3"),
        world.create_item("M79"),
        world.create_item("LAW80"),
        world.create_item("Sp Armor 2"),
        world.create_item("Sv Armor 1"),
        world.create_item("Cr Protector"),
        world.create_item("B Vest 1"),
        world.create_item("B Protector"),
        world.create_item("B Jacket 2"),
        world.create_item("B Suit 2"),
        world.create_item("Cm Vest 1"),
        world.create_item("Cm Suit 1"),
        world.create_item("Cm Armor 2"),
        world.create_item("Theater Key"),
        world.create_item("Rehearse Key"),
        world.create_item("Zoo Key"),
        world.create_item("Narita"),
        world.create_item("Mayoke"),
        world.create_item("Hamaya"),
        world.create_item("Fuse 1"),
        world.create_item("Fuse 2"),
        world.create_item("Fuse 3"),
        world.create_item("Autopsy Key"),
        world.create_item("Blue Cardkey"),
        world.create_item("Green Cardkey"),
        world.create_item("Pump Key"),
        world.create_item("Klamp Key"),
        world.create_item("Storage Key"),
        world.create_item("Locker Key"),
        world.create_item("Weapon Memo"),
        world.create_item("Elevator Key"),
        world.create_item("Gate Key"),
        world.create_item("Warehouse Key"),
        world.create_item("Heal 1"),
        world.create_item("Scan"),
        world.create_item("Slow"),
        world.create_item("Confuse"),
        world.create_item("Gene Heal"),
        world.create_item("Area: Carnegie Hall"),
        world.create_item("Area: Central Park"),
        world.create_item("Area: Soho"),
        world.create_item("Area: Hospital"),
        world.create_item("Area: Chinatown"),
        world.create_item("Area: Subway"),
        world.create_item("Area: Warehouse"),
        world.create_item("Area: Museum"),
        world.create_item("Area: Chrysler BLDG."),
    ]
    #Add in item pool additions related to player options. This is bare minimum.

    number_of_items = len(itempool)
    number_of_unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))
    needed_number_of_filler_items = number_of_unfilled_locations - number_of_items
    itempool += [world.create_filler() for _ in range(needed_number_of_filler_items)]


    world.multiworld.itempool += itempool


    if world.options.unreasonable_checks:

        starting_precinct_visit = world.create_item("Area: N.Y.P.D. #17")
        world.push_precollected(starting_precinct_visit)