from typing import Dict, NamedTuple, Optional

from BaseClasses import Item, ItemClassification


class PEItem(Item):
    game = "Parasite Eve"


class PEItemData(NamedTuple):
    code: Optional[int] = None
    type: ItemClassification = ItemClassification.filler


item_data_table: Dict[str, PEItemData] = {
    "Ammo +6":          PEItemData(5001, ItemClassification.filler),
    "Ammo +15":         PEItemData(5002, ItemClassification.useful),
    "Ammo +30":         PEItemData(5003, ItemClassification.useful),
    "DNA Bullets":      PEItemData(5004, ItemClassification.useful),
    "Rocket":           PEItemData(5005, ItemClassification.useful),
    "Medicine 1":       PEItemData(5006, ItemClassification.filler),
    "Medicine 2":       PEItemData(5007, ItemClassification.useful),
    "Medicine 3":       PEItemData(5008, ItemClassification.useful),
    "Medicine 4":       PEItemData(5009, ItemClassification.useful),
    "Full Recovery":    PEItemData(5010, ItemClassification.useful),
    "Super Junk":       PEItemData(5011, ItemClassification.progression),
    "Duper Junk":       PEItemData(5012, ItemClassification.filler),
    "Cure-P":           PEItemData(5013, ItemClassification.useful),
    "Cure-D":           PEItemData(5014, ItemClassification.useful),
    "Cure-C":           PEItemData(5015, ItemClassification.filler),
    "Cure-M":           PEItemData(5016, ItemClassification.useful),
    "FullCure":         PEItemData(5017, ItemClassification.useful),
    "Revive":           PEItemData(5018, ItemClassification.useful),
    #Defense +1":       PEItemData(5019, "Unused duplicate Defense 1, unable to be used."),
    "Junk":             PEItemData(5020, ItemClassification.filler),
    "Trading Card":     PEItemData(5021, ItemClassification.filler),
    "Tool":             PEItemData(5022, ItemClassification.useful),
    "Super Tool":       PEItemData(5023, ItemClassification.useful),
    #Item24":           PEItemData(5024, "Unused item. Consumable, but has no effect."),
    #Item25":           PEItemData(5025, "Unused item. Consumable, but has no effect."),
    #Ammo Crate":       PEItemData(5026, "Crate is automatically given upon receiving its ammo."),
    #Rocket Crate":     PEItemData(5027, "Crate is automatically given upon receiving its ammo."),
    #Maeda Crate":      PEItemData(5028, "Crate is automatically given upon receiving its ammo."),
    "Offense +1":       PEItemData(5029, ItemClassification.filler),
    "Offense +2":       PEItemData(5030, ItemClassification.useful),
    "Offense +3":       PEItemData(5031, ItemClassification.useful),
    "Offense +4":       PEItemData(5032, ItemClassification.useful),
    "Range +1":         PEItemData(5033, ItemClassification.filler),
    "Range +2":         PEItemData(5034, ItemClassification.useful),
    "Range +3":         PEItemData(5035, ItemClassification.useful),
    "Range +4":         PEItemData(5036, ItemClassification.useful),
    "Bullet Cap +1":    PEItemData(5037, ItemClassification.filler),
    "Bullet Cap +2":    PEItemData(5038, ItemClassification.useful),
    "Bullet Cap +3":    PEItemData(5039, ItemClassification.useful),
    "Bullet Cap +4":    PEItemData(5040, ItemClassification.useful),
    "Defense +1":       PEItemData(5041, ItemClassification.filler),
    "Defense +2":       PEItemData(5042, ItemClassification.useful),
    "Defense +3":       PEItemData(5043, ItemClassification.useful),
    "Defense +4":       PEItemData(5044, ItemClassification.useful),
    "Cr Evade +1":      PEItemData(5045, ItemClassification.filler),
    "Cr Evade +2":      PEItemData(5046, ItemClassification.useful),
    "Cr Evade +3":      PEItemData(5047, ItemClassification.useful),
    "Cr Evade +4":      PEItemData(5048, ItemClassification.useful),
    "PE +1":            PEItemData(5049, ItemClassification.filler),
    "PE +2":            PEItemData(5050, ItemClassification.useful),
    "PE +3":            PEItemData(5051, ItemClassification.useful),
    "PE +4":            PEItemData(5052, ItemClassification.useful),
    "Tool Kit":         PEItemData(5053, ItemClassification.useful),
    "Super Tool Kit":   PEItemData(5054, ItemClassification.useful),
    "ModPermit":        PEItemData(5055, ItemClassification.useful),
    "Chrysler Key 1":   PEItemData(5056, ItemClassification.progression),
    "Chrysler Key 2":   PEItemData(5057, ItemClassification.progression),
    "Chrysler Key 3":   PEItemData(5058, ItemClassification.progression),
    "Chrysler Key 4":   PEItemData(5059, ItemClassification.progression),
    "Chrysler Key 5":   PEItemData(5060, ItemClassification.progression),
    "Chrysler Key 6":   PEItemData(5061, ItemClassification.progression),
    "Chrysler Key 7":   PEItemData(5062, ItemClassification.progression),

    "Club 1":           PEItemData(5063, ItemClassification.useful),
    "Club 2":           PEItemData(5064, ItemClassification.useful),
    "Club 3":           PEItemData(5065, ItemClassification.useful),
    "Club 4":           PEItemData(5066, ItemClassification.progression),
    "Club 5":           PEItemData(5067, ItemClassification.progression),
    "M84F":             PEItemData(5068, ItemClassification.useful),
    "M9":               PEItemData(5069, ItemClassification.useful),
    "M9-2":             PEItemData(5070, ItemClassification.useful),
    "M9-3":             PEItemData(5071, ItemClassification.progression),
    "M8000":            PEItemData(5072, ItemClassification.progression),
    "M96":              PEItemData(5073, ItemClassification.useful),
    "M96R":             PEItemData(5074, ItemClassification.progression),
    "P220":             PEItemData(5075, ItemClassification.useful),
    "P220-2":           PEItemData(5076, ItemClassification.useful),
    "P228":             PEItemData(5077, ItemClassification.useful),
    "P226":             PEItemData(5078, ItemClassification.useful),
    "P229":             PEItemData(5079, ItemClassification.useful),
    "M1911A1":          PEItemData(5080, ItemClassification.useful),
    "M1911A2":          PEItemData(5081, ItemClassification.useful),
    "M1911A3":          PEItemData(5082, ItemClassification.useful),
    "M1911A4":          PEItemData(5083, ItemClassification.useful),
    "M1911A5":          PEItemData(5084, ItemClassification.useful),
    "P8":               PEItemData(5085, ItemClassification.useful),
    "USP":              PEItemData(5086, ItemClassification.useful),
    "USP-2":            PEItemData(5087, ItemClassification.useful),
    "USP-3":            PEItemData(5088, ItemClassification.useful),
    "Mark 23":          PEItemData(5089, ItemClassification.useful),
    "G19":              PEItemData(5090, ItemClassification.useful),
    "G23":              PEItemData(5091, ItemClassification.useful),
    "G22":              PEItemData(5092, ItemClassification.useful),
    "G20":              PEItemData(5093, ItemClassification.useful),
    "M712":             PEItemData(5094, ItemClassification.useful),
    "PPK":              PEItemData(5095, ItemClassification.progression),
    "AM44":             PEItemData(5096, ItemClassification.useful),
    "Maeda's Gun":      PEItemData(5097, ItemClassification.useful),
    "PPSh41":           PEItemData(5098, ItemClassification.useful),
    "SP1C":             PEItemData(5099, ItemClassification.useful),
    "USP-TU":           PEItemData(5100, ItemClassification.useful),
    "AK-47":            PEItemData(5101, ItemClassification.useful),
    "DE50AE7":          PEItemData(5102, ItemClassification.useful),
    #Debug SMG":        PEItemData(5103, "Completely busted plus stats, not using."),
    "M870":             PEItemData(5104, ItemClassification.useful),
    "M870-2":           PEItemData(5105, ItemClassification.useful),
    "M500":             PEItemData(5106, ItemClassification.useful),
    "M500-2":           PEItemData(5107, ItemClassification.useful),
    "Maverick":         PEItemData(5108, ItemClassification.progression),
    "S12":              PEItemData(5109, ItemClassification.useful),
    "M10B":             PEItemData(5110, ItemClassification.useful),
    "M11":              PEItemData(5111, ItemClassification.useful),
    "M10":              PEItemData(5112, ItemClassification.useful),
    "MP5K":             PEItemData(5113, ItemClassification.useful),
    "MP5PDW":           PEItemData(5114, ItemClassification.useful),
    "MP5A5":            PEItemData(5115, ItemClassification.progression),
    "MP5SD6":           PEItemData(5116, ItemClassification.useful),
    "Micro UZ":         PEItemData(5117, ItemClassification.useful),
    "Mini UZ":          PEItemData(5118, ItemClassification.useful),
    "Full UZ":          PEItemData(5119, ItemClassification.useful),
    "P90":              PEItemData(5120, ItemClassification.useful),
    "M16A1":            PEItemData(5121, ItemClassification.useful),
    "M16A2":            PEItemData(5122, ItemClassification.useful),
    "SG550":            PEItemData(5123, ItemClassification.useful),
    "SAR":              PEItemData(5124, ItemClassification.useful),
    "G3A3":             PEItemData(5125, ItemClassification.useful),
    "Type64":           PEItemData(5126, ItemClassification.progression),
    "XM177E2":          PEItemData(5127, ItemClassification.useful),
    "PSG-1":            PEItemData(5128, ItemClassification.useful),
    "FA-MAS":           PEItemData(5129, ItemClassification.useful),
    "MAG":              PEItemData(5130, ItemClassification.useful),
    "M203":             PEItemData(5131, ItemClassification.useful),
    "M203-2":           PEItemData(5132, ItemClassification.useful),
    "M203-3":           PEItemData(5133, ItemClassification.progression),
    "M203-4":           PEItemData(5134, ItemClassification.useful),
    "M203-5":           PEItemData(5135, ItemClassification.useful),
    "M203-6":           PEItemData(5136, ItemClassification.useful),
    "M79":              PEItemData(5137, ItemClassification.progression),
    "M79-2":            PEItemData(5138, ItemClassification.useful),
    "M79-3":            PEItemData(5139, ItemClassification.useful),
    "M79-4":            PEItemData(5140, ItemClassification.useful),
    "M79-5":            PEItemData(5141, ItemClassification.useful),
    "M79-6":            PEItemData(5142, ItemClassification.useful),
    "HK40":             PEItemData(5143, ItemClassification.useful),
    "AT4":              PEItemData(5144, ItemClassification.useful),
    "AT4-1":            PEItemData(5145, ItemClassification.useful),
    "LAW80":            PEItemData(5146, ItemClassification.progression),
    #Maeda's Gun WB":   PEItemData(5147, "Loaded variant for final fight, excluded."),
    "M92F":             PEItemData(5148, ItemClassification.useful),
    "Dress":            PEItemData(5149, ItemClassification.useful),
    "N Vest":           PEItemData(5150, ItemClassification.useful),
    "N Protector":      PEItemData(5151, ItemClassification.useful),
    "N Jacket":         PEItemData(5152, ItemClassification.useful),
    "N Suit":           PEItemData(5153, ItemClassification.useful),
    "N Armor":          PEItemData(5154, ItemClassification.useful),
    "Kv Vest 1":        PEItemData(5155, ItemClassification.useful),
    "Kv Protector":     PEItemData(5156, ItemClassification.useful),
    "Kv Jacket":        PEItemData(5157, ItemClassification.useful),
    "Kv Suit 1":        PEItemData(5158, ItemClassification.useful),
    "Kv Armor 1":       PEItemData(5159, ItemClassification.useful),
    "Sp Vest 1":        PEItemData(5160, ItemClassification.useful),
    "Sp Vest 2":        PEItemData(5161, ItemClassification.useful),
    "Sp Protector":     PEItemData(5162, ItemClassification.useful),
    "Sp Jacket":        PEItemData(5163, ItemClassification.useful),
    "Sp Suit 1":        PEItemData(5164, ItemClassification.useful),
    "Sp Suit 2":        PEItemData(5165, ItemClassification.useful),
    "Sp Armor 1":       PEItemData(5166, ItemClassification.useful),
    "Sp Armor 2":       PEItemData(5167, ItemClassification.progression),
    "Sv Vest 1":        PEItemData(5168, ItemClassification.useful),
    "Sv Vest 2":        PEItemData(5169, ItemClassification.useful),
    "Sv Protector":     PEItemData(5170, ItemClassification.useful),
    "Sv Jacket":        PEItemData(5171, ItemClassification.useful),
    "Sv Suit 1":        PEItemData(5172, ItemClassification.useful),
    "Sv Suit 2":        PEItemData(5173, ItemClassification.useful),
    "Sv Armor 1":       PEItemData(5174, ItemClassification.progression),
    "Sv Armor 2":       PEItemData(5175, ItemClassification.useful),
    "Cr Vest 1":        PEItemData(5176, ItemClassification.useful),
    "Cr Vest 2":        PEItemData(5177, ItemClassification.useful),
    "Cr Protector":     PEItemData(5178, ItemClassification.progression),
    "Cr Jacket":        PEItemData(5179, ItemClassification.useful),
    "Cr Suit 1":        PEItemData(5180, ItemClassification.useful),
    "Cr Suit 2":        PEItemData(5181, ItemClassification.useful),
    "Cr Armor 1":       PEItemData(5182, ItemClassification.useful),
    "Cr Armor 2":       PEItemData(5183, ItemClassification.useful),
    "B Vest 1":         PEItemData(5184, ItemClassification.progression),
    "B Vest 2":         PEItemData(5185, ItemClassification.useful),
    "B Protector":      PEItemData(5186, ItemClassification.progression),
    "B Jacket 1":       PEItemData(5187, ItemClassification.useful),
    "B Jacket 2":       PEItemData(5188, ItemClassification.progression),
    "B Suit 1":         PEItemData(5189, ItemClassification.useful),
    "B Suit 2":         PEItemData(5190, ItemClassification.progression),
    "B Armor":          PEItemData(5191, ItemClassification.useful),
    "Cm Vest 1":        PEItemData(5192, ItemClassification.progression),
    "Cm Vest 2":        PEItemData(5193, ItemClassification.useful),
    "Cm Protector":     PEItemData(5194, ItemClassification.useful),
    "Cm Jacket":        PEItemData(5195, ItemClassification.useful),
    "Cm Suit 1":        PEItemData(5196, ItemClassification.progression),
    "Cm Armor 1":       PEItemData(5197, ItemClassification.useful),
    "Cm Armor 2":       PEItemData(5198, ItemClassification.progression),
    #Cm Suit 2":        PEItemData(5199, "Armor-equivalent of Debug SMG, excluded."),

    "Theater Key":      PEItemData(5200, ItemClassification.progression),
    "Rehearse Key":     PEItemData(5201, ItemClassification.progression),
    "Zoo Key":          PEItemData(5202, ItemClassification.progression),
    "Narita":           PEItemData(5203, ItemClassification.progression),
    "Mayoke":           PEItemData(5204, ItemClassification.progression),
    "Hamaya":           PEItemData(5205, ItemClassification.progression),
    "Fuse 1":           PEItemData(5206, ItemClassification.progression),
    "Fuse 2":           PEItemData(5207, ItemClassification.progression),
    "Fuse 3":           PEItemData(5208, ItemClassification.progression),
    "Autopsy Key":      PEItemData(5209, ItemClassification.progression),
    "Blue Cardkey":     PEItemData(5210, ItemClassification.progression),
    "Green Cardkey":    PEItemData(5211, ItemClassification.progression),
    "Pump Key":         PEItemData(5212, ItemClassification.progression),
    "Klamp Key":        PEItemData(5213, ItemClassification.progression),
    "Storage Key":      PEItemData(5214, ItemClassification.progression),
    "Locker Key":       PEItemData(5215, ItemClassification.progression),
    "Weapon Memo":      PEItemData(5216, ItemClassification.progression),
    #Medal":            PEItemData(5217, "Currently unused for the rando."),
    "Elevator Key":     PEItemData(5218, ItemClassification.progression),
    "Gate Key":         PEItemData(5219, ItemClassification.progression),
    "Warehouse Key":    PEItemData(5220, ItemClassification.progression),
    "GSP T Card":       PEItemData(5221, ItemClassification.progression),
    "P38 T Card":       PEItemData(5222, ItemClassification.progression),
    "Bhawk T Card":     PEItemData(5223, ItemClassification.progression),
    "Kasul T Card":     PEItemData(5224, ItemClassification.progression),
    "PPKS T Card":      PEItemData(5225, ItemClassification.progression),
    "M1 T Card":        PEItemData(5226, ItemClassification.progression),
    "MK5 T Card":       PEItemData(5227, ItemClassification.progression),
    "MP44 T Card":      PEItemData(5228, ItemClassification.progression),
    "BAR T Card":       PEItemData(5229, ItemClassification.progression),
    "MG42 T Card":      PEItemData(5230, ItemClassification.progression),
    "M29 T Card":       PEItemData(5231, ItemClassification.progression),
    "M73 T Card":       PEItemData(5232, ItemClassification.progression),
    "Type38 T Card":    PEItemData(5233, ItemClassification.progression),
    "Type3 T Card":     PEItemData(5234, ItemClassification.progression),
    "Eagle T Card":     PEItemData(5235, ItemClassification.progression),

    "Heal 1":           PEItemData(5236, ItemClassification.progression),
    "Heal 2":           PEItemData(5237, ItemClassification.progression),
    "Heal 3":           PEItemData(5238, ItemClassification.progression),
    "Detox":            PEItemData(5239, ItemClassification.progression),
    "Medic":            PEItemData(5240, ItemClassification.progression),
    "Barrier":          PEItemData(5241, ItemClassification.progression),
    "Energy Shot":      PEItemData(5242, ItemClassification.progression),
    "Scan":             PEItemData(5243, ItemClassification.useful),
    "Slow":             PEItemData(5244, ItemClassification.useful),
    "Haste":            PEItemData(5245, ItemClassification.progression),
    "Confuse":          PEItemData(5246, ItemClassification.useful),
    "Gene Heal":        PEItemData(5247, ItemClassification.progression),
    "Preraise":         PEItemData(5248, ItemClassification.progression),
    #mito14":           PEItemData(5249, "Unused PE, has an animation, but no cost or effect.")
    #mito15":           PEItemData(5250, "Unused PE, has an animation, but no cost or effect.")
    #mito16":           PEItemData(5251, "Unused PE, has an animation, but no cost or effect.")
    #mito17":           PEItemData(5252, "Unused PE, has an animation, but no cost or effect.")
    #mito18":           PEItemData(5253, "Unused PE, has an animation, but no cost or effect.")
    "Full Recover":     PEItemData(5254, ItemClassification.progression),
    "Liberate":         PEItemData(5255, ItemClassification.progression),

    "Carnegie Hall":    PEItemData(5256, ItemClassification.progression),
    "N.Y.P.D. #17":     PEItemData(5257, ItemClassification.progression),
    "Central Park":     PEItemData(5258, ItemClassification.progression),
    "Soho":             PEItemData(5259, ItemClassification.progression),
    "Hospital":         PEItemData(5260, ItemClassification.progression),
    "Chinatown":        PEItemData(5261, ItemClassification.progression),
    "Subway":           PEItemData(5262, ItemClassification.progression),
    "Warehouse":        PEItemData(5263, ItemClassification.progression),
    "Museum":           PEItemData(5264, ItemClassification.progression),
    "Chrysler BLDG.":   PEItemData(5265, ItemClassification.progression),

    "Confusion Trap":   PEItemData(5266, "Trap",        ItemClassification.trap),
    "Darkness Trap":    PEItemData(5267, "Trap",        ItemClassification.trap),
    "Silence Trap":     PEItemData(5268, "Trap",        ItemClassification.trap),
    "Impact Trap":      PEItemData(5269, "Trap",        ItemClassification.trap),
}


item_table = {name: data.code for name, data in item_data_table.items() if data.code is not None}
