from typing import Dict, NamedTuple, Optional

from BaseClasses import Item, ItemClassification


class PEItem(Item):
    game = "Parasite Eve"


class PEItemData(NamedTuple):
    code: Optional[int] = None
    type: ItemClassification = ItemClassification.filler


item_data_table: Dict[str, PEItemData] = {
    "Ammo +6":          PEItemData(624001, ItemClassification.filler),
    "Ammo +15":         PEItemData(624002, ItemClassification.useful),
    "Ammo +30":         PEItemData(624003, ItemClassification.useful),
    "DNA Bullets":      PEItemData(624004, ItemClassification.useful),
    "Rocket":           PEItemData(624005, ItemClassification.useful),
    "Medicine 1":       PEItemData(624006, ItemClassification.filler),
    "Medicine 2":       PEItemData(624007, ItemClassification.useful),
    "Medicine 3":       PEItemData(624008, ItemClassification.useful),
    "Medicine 4":       PEItemData(624009, ItemClassification.useful),
    "Full Recovery":    PEItemData(624010, ItemClassification.useful),
    "Super Junk":       PEItemData(624011, ItemClassification.progression),
    "Duper Junk":       PEItemData(624012, ItemClassification.filler),
    "Cure-P":           PEItemData(624013, ItemClassification.useful),
    "Cure-D":           PEItemData(624014, ItemClassification.useful),
    "Cure-C":           PEItemData(624015, ItemClassification.filler),
    "Cure-M":           PEItemData(624016, ItemClassification.useful),
    "FullCure":         PEItemData(624017, ItemClassification.useful),
    "Revive":           PEItemData(624018, ItemClassification.useful),
    #Defense +1":       PEItemData(624019, "Unused duplicate Defense 1, unable to be used."),
    "Junk":             PEItemData(624020, ItemClassification.filler),
    "Trading Card":     PEItemData(624021, ItemClassification.filler),
    "Tool":             PEItemData(624022, ItemClassification.useful),
    "Super Tool":       PEItemData(624023, ItemClassification.useful),
    #Item24":           PEItemData(624024, "Unused item. Consumable, but has no effect."),
    #Item25":           PEItemData(624025, "Unused item. Consumable, but has no effect."),
    #Ammo Crate":       PEItemData(624026, "Crate is automatically given upon receiving its ammo."),
    #Rocket Crate":     PEItemData(624027, "Crate is automatically given upon receiving its ammo."),
    #Maeda Crate":      PEItemData(624028, "Crate is automatically given upon receiving its ammo."),
    "Offense +1":       PEItemData(624029, ItemClassification.filler),
    "Offense +2":       PEItemData(624030, ItemClassification.useful),
    "Offense +3":       PEItemData(624031, ItemClassification.useful),
    "Offense +4":       PEItemData(624032, ItemClassification.useful),
    "Range +1":         PEItemData(624033, ItemClassification.filler),
    "Range +2":         PEItemData(624034, ItemClassification.useful),
    "Range +3":         PEItemData(624035, ItemClassification.useful),
    "Range +4":         PEItemData(624036, ItemClassification.useful),
    "Bullet Cap +1":    PEItemData(624037, ItemClassification.filler),
    "Bullet Cap +2":    PEItemData(624038, ItemClassification.useful),
    "Bullet Cap +3":    PEItemData(624039, ItemClassification.useful),
    "Bullet Cap +4":    PEItemData(624040, ItemClassification.useful),
    "Defense +1":       PEItemData(624041, ItemClassification.filler),
    "Defense +2":       PEItemData(624042, ItemClassification.useful),
    "Defense +3":       PEItemData(624043, ItemClassification.useful),
    "Defense +4":       PEItemData(624044, ItemClassification.useful),
    "Cr Evade +1":      PEItemData(624045, ItemClassification.filler),
    "Cr Evade +2":      PEItemData(624046, ItemClassification.useful),
    "Cr Evade +3":      PEItemData(624047, ItemClassification.useful),
    "Cr Evade +4":      PEItemData(624048, ItemClassification.useful),
    "PE +1":            PEItemData(624049, ItemClassification.filler),
    "PE +2":            PEItemData(624050, ItemClassification.useful),
    "PE +3":            PEItemData(624051, ItemClassification.useful),
    "PE +4":            PEItemData(624052, ItemClassification.useful),
    "Tool Kit":         PEItemData(624053, ItemClassification.useful),
    "Super Tool Kit":   PEItemData(624054, ItemClassification.useful),
    "ModPermit":        PEItemData(624055, ItemClassification.useful),
    "Chrysler Key 1":   PEItemData(624056, ItemClassification.progression),
    "Chrysler Key 2":   PEItemData(624057, ItemClassification.progression),
    "Chrysler Key 3":   PEItemData(624058, ItemClassification.progression),
    "Chrysler Key 4":   PEItemData(624059, ItemClassification.progression),
    "Chrysler Key 5":   PEItemData(624060, ItemClassification.progression),
    "Chrysler Key 6":   PEItemData(624061, ItemClassification.progression),
    "Chrysler Key 7":   PEItemData(624062, ItemClassification.progression),

    "Club 1":           PEItemData(624063, ItemClassification.useful),
    "Club 2":           PEItemData(624064, ItemClassification.useful),
    "Club 3":           PEItemData(624065, ItemClassification.useful),
    "Club 4":           PEItemData(624066, ItemClassification.progression),
    "Club 5":           PEItemData(624067, ItemClassification.progression),
    "M84F":             PEItemData(624068, ItemClassification.useful),
    "M9":               PEItemData(624069, ItemClassification.useful),
    "M9-2":             PEItemData(624070, ItemClassification.useful),
    "M9-3":             PEItemData(624071, ItemClassification.progression),
    "M8000":            PEItemData(624072, ItemClassification.progression),
    "M96":              PEItemData(624073, ItemClassification.useful),
    "M96R":             PEItemData(624074, ItemClassification.progression),
    "P220":             PEItemData(624075, ItemClassification.useful),
    "P220-2":           PEItemData(624076, ItemClassification.useful),
    "P228":             PEItemData(624077, ItemClassification.useful),
    "P226":             PEItemData(624078, ItemClassification.useful),
    "P229":             PEItemData(624079, ItemClassification.useful),
    "M1911A1":          PEItemData(624080, ItemClassification.useful),
    "M1911A2":          PEItemData(624081, ItemClassification.useful),
    "M1911A3":          PEItemData(624082, ItemClassification.useful),
    "M1911A4":          PEItemData(624083, ItemClassification.useful),
    "M1911A5":          PEItemData(624084, ItemClassification.useful),
    "P8":               PEItemData(624085, ItemClassification.useful),
    "USP":              PEItemData(624086, ItemClassification.useful),
    "USP-2":            PEItemData(624087, ItemClassification.useful),
    "USP-3":            PEItemData(624088, ItemClassification.useful),
    "Mark 23":          PEItemData(624089, ItemClassification.useful),
    "G19":              PEItemData(624090, ItemClassification.useful),
    "G23":              PEItemData(624091, ItemClassification.useful),
    "G22":              PEItemData(624092, ItemClassification.useful),
    "G20":              PEItemData(624093, ItemClassification.useful),
    "M712":             PEItemData(624094, ItemClassification.useful),
    "PPK":              PEItemData(624095, ItemClassification.progression),
    "AM44":             PEItemData(624096, ItemClassification.useful),
    "Maeda's Gun":      PEItemData(624097, ItemClassification.useful),
    "PPSh41":           PEItemData(624098, ItemClassification.useful),
    "SP1C":             PEItemData(624099, ItemClassification.useful),
    "USP-TU":           PEItemData(624100, ItemClassification.useful),
    "AK-47":            PEItemData(624101, ItemClassification.useful),
    "DE50AE7":          PEItemData(624102, ItemClassification.useful),
    #Debug SMG":        PEItemData(624103, "Completely busted plus stats, not using."),
    "M870":             PEItemData(624104, ItemClassification.useful),
    "M870-2":           PEItemData(624105, ItemClassification.useful),
    "M500":             PEItemData(624106, ItemClassification.useful),
    "M500-2":           PEItemData(624107, ItemClassification.useful),
    "Maverick":         PEItemData(624108, ItemClassification.progression),
    "S12":              PEItemData(624109, ItemClassification.useful),
    "M10B":             PEItemData(624110, ItemClassification.useful),
    "M11":              PEItemData(624111, ItemClassification.useful),
    "M10":              PEItemData(624112, ItemClassification.useful),
    "MP5K":             PEItemData(624113, ItemClassification.useful),
    "MP5PDW":           PEItemData(624114, ItemClassification.useful),
    "MP5A5":            PEItemData(624115, ItemClassification.progression),
    "MP5SD6":           PEItemData(624116, ItemClassification.useful),
    "Micro UZ":         PEItemData(624117, ItemClassification.useful),
    "Mini UZ":          PEItemData(624118, ItemClassification.useful),
    "Full UZ":          PEItemData(624119, ItemClassification.useful),
    "P90":              PEItemData(624120, ItemClassification.useful),
    "M16A1":            PEItemData(624121, ItemClassification.useful),
    "M16A2":            PEItemData(624122, ItemClassification.useful),
    "SG550":            PEItemData(624123, ItemClassification.useful),
    "SAR":              PEItemData(624124, ItemClassification.useful),
    "G3A3":             PEItemData(624125, ItemClassification.useful),
    "Type64":           PEItemData(624126, ItemClassification.progression),
    "XM177E2":          PEItemData(624127, ItemClassification.useful),
    "PSG-1":            PEItemData(624128, ItemClassification.useful),
    "FA-MAS":           PEItemData(624129, ItemClassification.useful),
    "MAG":              PEItemData(624130, ItemClassification.useful),
    "M203":             PEItemData(624131, ItemClassification.useful),
    "M203-2":           PEItemData(624132, ItemClassification.useful),
    "M203-3":           PEItemData(624133, ItemClassification.progression),
    "M203-4":           PEItemData(624134, ItemClassification.useful),
    "M203-5":           PEItemData(624135, ItemClassification.useful),
    "M203-6":           PEItemData(624136, ItemClassification.useful),
    "M79":              PEItemData(624137, ItemClassification.progression),
    "M79-2":            PEItemData(624138, ItemClassification.useful),
    "M79-3":            PEItemData(624139, ItemClassification.useful),
    "M79-4":            PEItemData(624140, ItemClassification.useful),
    "M79-5":            PEItemData(624141, ItemClassification.useful),
    "M79-6":            PEItemData(624142, ItemClassification.useful),
    "HK40":             PEItemData(624143, ItemClassification.useful),
    "AT4":              PEItemData(624144, ItemClassification.useful),
    "AT4-1":            PEItemData(624145, ItemClassification.useful),
    "LAW80":            PEItemData(624146, ItemClassification.progression),
    #Maeda's Gun WB":   PEItemData(624147, "Loaded variant for final fight, excluded."),
    "M92F":             PEItemData(624148, ItemClassification.useful),
    "Dress":            PEItemData(624149, ItemClassification.useful),
    "N Vest":           PEItemData(624150, ItemClassification.useful),
    "N Protector":      PEItemData(624151, ItemClassification.useful),
    "N Jacket":         PEItemData(624152, ItemClassification.useful),
    "N Suit":           PEItemData(624153, ItemClassification.useful),
    "N Armor":          PEItemData(624154, ItemClassification.useful),
    "Kv Vest 1":        PEItemData(624155, ItemClassification.useful),
    "Kv Protector":     PEItemData(624156, ItemClassification.useful),
    "Kv Jacket":        PEItemData(624157, ItemClassification.useful),
    "Kv Suit 1":        PEItemData(624158, ItemClassification.useful),
    "Kv Armor 1":       PEItemData(624159, ItemClassification.useful),
    "Sp Vest 1":        PEItemData(624160, ItemClassification.useful),
    "Sp Vest 2":        PEItemData(624161, ItemClassification.useful),
    "Sp Protector":     PEItemData(624162, ItemClassification.useful),
    "Sp Jacket":        PEItemData(624163, ItemClassification.useful),
    "Sp Suit 1":        PEItemData(624164, ItemClassification.useful),
    "Sp Suit 2":        PEItemData(624165, ItemClassification.useful),
    "Sp Armor 1":       PEItemData(624166, ItemClassification.useful),
    "Sp Armor 2":       PEItemData(624167, ItemClassification.progression),
    "Sv Vest 1":        PEItemData(624168, ItemClassification.useful),
    "Sv Vest 2":        PEItemData(624169, ItemClassification.useful),
    "Sv Protector":     PEItemData(624170, ItemClassification.useful),
    "Sv Jacket":        PEItemData(624171, ItemClassification.useful),
    "Sv Suit 1":        PEItemData(624172, ItemClassification.useful),
    "Sv Suit 2":        PEItemData(624173, ItemClassification.useful),
    "Sv Armor 1":       PEItemData(624174, ItemClassification.progression),
    "Sv Armor 2":       PEItemData(624175, ItemClassification.useful),
    "Cr Vest 1":        PEItemData(624176, ItemClassification.useful),
    "Cr Vest 2":        PEItemData(624177, ItemClassification.useful),
    "Cr Protector":     PEItemData(624178, ItemClassification.progression),
    "Cr Jacket":        PEItemData(624179, ItemClassification.useful),
    "Cr Suit 1":        PEItemData(624180, ItemClassification.useful),
    "Cr Suit 2":        PEItemData(624181, ItemClassification.useful),
    "Cr Armor 1":       PEItemData(624182, ItemClassification.useful),
    "Cr Armor 2":       PEItemData(624183, ItemClassification.useful),
    "B Vest 1":         PEItemData(624184, ItemClassification.progression),
    "B Vest 2":         PEItemData(624185, ItemClassification.useful),
    "B Protector":      PEItemData(624186, ItemClassification.progression),
    "B Jacket 1":       PEItemData(624187, ItemClassification.useful),
    "B Jacket 2":       PEItemData(624188, ItemClassification.progression),
    "B Suit 1":         PEItemData(624189, ItemClassification.useful),
    "B Suit 2":         PEItemData(624190, ItemClassification.progression),
    "B Armor":          PEItemData(624191, ItemClassification.useful),
    "Cm Vest 1":        PEItemData(624192, ItemClassification.progression),
    "Cm Vest 2":        PEItemData(624193, ItemClassification.useful),
    "Cm Protector":     PEItemData(624194, ItemClassification.useful),
    "Cm Jacket":        PEItemData(624195, ItemClassification.useful),
    "Cm Suit 1":        PEItemData(624196, ItemClassification.progression),
    "Cm Armor 1":       PEItemData(624197, ItemClassification.useful),
    "Cm Armor 2":       PEItemData(624198, ItemClassification.progression),
    #Cm Suit 2":        PEItemData(624199, "Armor-equivalent of Debug SMG, excluded."),

    "Theater Key":      PEItemData(624200, ItemClassification.progression),
    "Rehearse Key":     PEItemData(624201, ItemClassification.progression),
    "Zoo Key":          PEItemData(624202, ItemClassification.progression),
    "Narita":           PEItemData(624203, ItemClassification.progression),
    "Mayoke":           PEItemData(624204, ItemClassification.progression),
    "Hamaya":           PEItemData(624205, ItemClassification.progression),
    "Fuse 1":           PEItemData(624206, ItemClassification.progression),
    "Fuse 2":           PEItemData(624207, ItemClassification.progression),
    "Fuse 3":           PEItemData(624208, ItemClassification.progression),
    "Autopsy Key":      PEItemData(624209, ItemClassification.progression),
    "Blue Cardkey":     PEItemData(624210, ItemClassification.progression),
    "Green Cardkey":    PEItemData(624211, ItemClassification.progression),
    "Pump Key":         PEItemData(624212, ItemClassification.progression),
    "Klamp Key":        PEItemData(624213, ItemClassification.progression),
    "Storage Key":      PEItemData(624214, ItemClassification.progression),
    "Locker Key":       PEItemData(624215, ItemClassification.progression),
    "Weapon Memo":      PEItemData(624216, ItemClassification.progression),
    #Medal":            PEItemData(624217, "Currently unused for the rando."),
    "Elevator Key":     PEItemData(624218, ItemClassification.progression),
    "Gate Key":         PEItemData(624219, ItemClassification.progression),
    "Warehouse Key":    PEItemData(624220, ItemClassification.progression),
    "GSP T Card":       PEItemData(624221, ItemClassification.progression),
    "P38 T Card":       PEItemData(624222, ItemClassification.progression),
    "Bhawk T Card":     PEItemData(624223, ItemClassification.progression),
    "Kasul T Card":     PEItemData(624224, ItemClassification.progression),
    "PPKS T Card":      PEItemData(624225, ItemClassification.progression),
    "M1 T Card":        PEItemData(624226, ItemClassification.progression),
    "MK5 T Card":       PEItemData(624227, ItemClassification.progression),
    "MP44 T Card":      PEItemData(624228, ItemClassification.progression),
    "BAR T Card":       PEItemData(624229, ItemClassification.progression),
    "MG42 T Card":      PEItemData(624230, ItemClassification.progression),
    "M29 T Card":       PEItemData(624231, ItemClassification.progression),
    "M73 T Card":       PEItemData(624232, ItemClassification.progression),
    "Type38 T Card":    PEItemData(624233, ItemClassification.progression),
    "Type3 T Card":     PEItemData(624234, ItemClassification.progression),
    "Eagle T Card":     PEItemData(624235, ItemClassification.progression),

    "Heal 1":           PEItemData(624236, ItemClassification.progression),
    "Heal 2":           PEItemData(624237, ItemClassification.progression),
    "Heal 3":           PEItemData(624238, ItemClassification.progression),
    "Detox":            PEItemData(624239, ItemClassification.progression),
    "Medic":            PEItemData(624240, ItemClassification.progression),
    "Barrier":          PEItemData(624241, ItemClassification.progression),
    "Energy Shot":      PEItemData(624242, ItemClassification.progression),
    "Scan":             PEItemData(624243, ItemClassification.useful),
    "Slow":             PEItemData(624244, ItemClassification.useful),
    "Haste":            PEItemData(624245, ItemClassification.progression),
    "Confuse":          PEItemData(624246, ItemClassification.useful),
    "Gene Heal":        PEItemData(624247, ItemClassification.progression),
    "Preraise":         PEItemData(624248, ItemClassification.progression),
    #mito14":           PEItemData(624249, "Unused PE, has an animation, but no cost or effect.")
    #mito15":           PEItemData(624250, "Unused PE, has an animation, but no cost or effect.")
    #mito16":           PEItemData(624251, "Unused PE, has an animation, but no cost or effect.")
    #mito17":           PEItemData(624252, "Unused PE, has an animation, but no cost or effect.")
    #mito18":           PEItemData(624253, "Unused PE, has an animation, but no cost or effect.")
    "Full Recover":     PEItemData(624254, ItemClassification.progression),
    "Liberate":         PEItemData(624255, ItemClassification.progression),

    "Carnegie Hall":    PEItemData(624256, ItemClassification.progression),
    "N.Y.P.D. #17":     PEItemData(624257, ItemClassification.progression),
    "Central Park":     PEItemData(624258, ItemClassification.progression),
    "Soho":             PEItemData(624259, ItemClassification.progression),
    "Hospital":         PEItemData(624260, ItemClassification.progression),
    "Chinatown":        PEItemData(624261, ItemClassification.progression),
    "Subway":           PEItemData(624262, ItemClassification.progression),
    "Warehouse":        PEItemData(624263, ItemClassification.progression),
    "Museum":           PEItemData(624264, ItemClassification.progression),
    "Chrysler BLDG.":   PEItemData(624265, ItemClassification.progression),

    "Confusion Trap":   PEItemData(624266, "Trap",        ItemClassification.trap),
    "Darkness Trap":    PEItemData(624267, "Trap",        ItemClassification.trap),
    "Silence Trap":     PEItemData(624268, "Trap",        ItemClassification.trap),
    "Impact Trap":      PEItemData(624269, "Trap",        ItemClassification.trap),
}


item_table = {name: data.code for name, data in item_data_table.items() if data.code is not None}
