from typing import Dict, NamedTuple, Optional

from BaseClasses import Location


class PELocation(Location):
    game = "Parasite Eve"

class PELocationData(NamedTuple):
    address: Optional[int] = None
    region: str


location_data_table: Dict[str, PELocationData] = {

    "Carnegie Hall - F1 Backstage: Chest":                             PELocationData(625001, "Carnegie Hall: NoReqs"),
    "Carnegie Hall - B1 Save Room: Chest":                             PELocationData(625002, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Save Room: Theater Corpse":                    PELocationData(625003, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Diary Room: Diary Key":                        PELocationData(625004, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Diary Room: Closet":                           PELocationData(625005, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Parrot Room: Closet":                          PELocationData(625006, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Clown Locker Room: Locker":                    PELocationData(625007, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Burned Pair Locker Room: Locker":              PELocationData(625008, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Prop Room: Front Chest":                       PELocationData(625009, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Hidden Chest":                      PELocationData(625010, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Rat Cabinet":                       PELocationData(625011, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Backstage Storage: Chest":                     PELocationData(625012, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - Sewers Stairway: Chest":                          PELocationData(625013, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Left Chest":              PELocationData(625014, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Right Chest":             PELocationData(625015, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Front Left Chest":             PELocationData(625016, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Left Chest":            PELocationData(625017, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Center Chest":          PELocationData(625018, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Right Chest":           PELocationData(625019, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Valve Chest":           PELocationData(625020, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Alligator: Boss Drop":                     PELocationData(625021, "Carnegie Hall: Combat+RK+Boss"),
    "N.Y.P.D. #17 - D2 1F Baker's Office: Baker Permit 1":             PELocationData(625022, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Right Locker":                  PELocationData(625023, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Center Locker":                 PELocationData(625024, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Conference Room: Baker Permit 2":            PELocationData(625025, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 B1 Weapons Department: M16A1":                  PELocationData(625026, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D3 1F Entrance: Maeda's Hamaya":                   PELocationData(625027, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Cop's Ammo":                      PELocationData(625028, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Nix's Ammo":                      PELocationData(625029, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Save Room: Warner's Ammo":                   PELocationData(625030, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Right Locker":                  PELocationData(625031, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Cop's Ammo":                    PELocationData(625032, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Locked Locker":                 PELocationData(625033, "N.Y.P.D. #17: LK"),
    "N.Y.P.D. #17 - D3 B1 Weapons Department: Torres's Gun":           PELocationData(625034, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 B1 Kennel: Cathy's Ammo":                       PELocationData(625035, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Conference Room: Spider Chest":              PELocationData(625036, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Barred Staircase: Cop's Ammo":               PELocationData(625037, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Left Chest":                  PELocationData(625038, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Right Chest":                 PELocationData(625039, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Chest":                  PELocationData(625040, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Table Sparkle":          PELocationData(625041, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Desk Chest":                    PELocationData(625042, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Floor Chest":                   PELocationData(625043, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 3F Ambush Hall: Cop's Locker Key":              PELocationData(625044, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D4 3F Medical Office: Daniel's Ammo":              PELocationData(625045, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Chest":                        PELocationData(625046, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Boss Drop":                    PELocationData(625047, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Cop's Ammo":                   PELocationData(625048, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf's Backroom: Chest":             PELocationData(625049, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Left Chest":                PELocationData(625050, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Center Chest":              PELocationData(625051, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Right Chest":               PELocationData(625052, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D3 3F Kerberos: Boss Drop":                        PELocationData(625053, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Tool Kit":               PELocationData(625054, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+12RTC"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Super Tool Kit":         PELocationData(625055, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+14RTC"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Leave It to Wayne":      PELocationData(625056, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+JunkReq"),
    "Central Park - Entrance: Car Chest":                              PELocationData(625057, "Central Park: NoReqs"),
    "Central Park - Entrance: Snake Chest":                            PELocationData(625058, "Central Park: NoReqs"),
    "Central Park - Front Gate: Left Chest":                           PELocationData(625059, "Central Park: Combat"),
    "Central Park - Front Gate: Right Chest":                          PELocationData(625060, "Central Park: Combat"),
    "Central Park - Courtyard: Left Gun Chest":                        PELocationData(625061, "Central Park: Combat"),
    "Central Park - Courtyard: Right Tool Chest":                      PELocationData(625062, "Central Park: Combat"),
    "Central Park - Office: Key Drawer":                               PELocationData(625063, "Central Park: Combat"),
    "Central Park - Office: Cabinet":                                  PELocationData(625064, "Central Park: Combat"),
    "Central Park - Office: Locked Cupboard":                          PELocationData(625065, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Upper Right Chest":                 PELocationData(625066, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Left Chest":                  PELocationData(625067, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Right Chest":                 PELocationData(625068, "Central Park: Combat+ZK"),
    "Central Park - Back Courtyard: Ammo Chest":                       PELocationData(625069, "Central Park: Combat"),
    "Central Park - Figure 8: Right Chest":                            PELocationData(625070, "Central Park: Combat"),
    "Central Park - Figure 8: Left Chest":                             PELocationData(625071, "Central Park: Combat"),
    "Central Park - Gazebo: Left Chest":                               PELocationData(625072, "Central Park: Combat+ZK"),
    "Central Park - Gazebo: Right Chest":                              PELocationData(625073, "Central Park: Combat+ZK"),
    "Central Park - Behind Gazebo (Save): Chest":                      PELocationData(625074, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze West: Mythical Tool Chest":            PELocationData(625075, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Bridge: Chest":                        PELocationData(625076, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Dock: Chest":                          PELocationData(625077, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze East: Backup Tool Chest":              PELocationData(625078, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Left Stat Chest":               PELocationData(625079, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Right YOLO Tool Chest":         PELocationData(625080, "Central Park: Combat+ZK"),
    "Central Park - Flaming Carriage Eve 2: Boss Drop":                PELocationData(625081, "Central Park: Combat+ZK+Boss"),
    "Soho - Apartment Interior: Chest":                                PELocationData(625082, "Soho: NoReqs"),
    "Soho - Apartment Exterior: Trash Card":                           PELocationData(625083, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 3 Medicine Chest":                         PELocationData(625084, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 5 Revive Chest":                           PELocationData(625085, "Soho: NoReqs"),
    "Soho - Pharmacy: Backroom Left Chest":                            PELocationData(625086, "Soho: NoReqs"),
    "Soho - Pharmacy: Backroom Right Chest":                           PELocationData(625087, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 1 Left Shelf":                             PELocationData(625088, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 3 Far Back Shelf":                         PELocationData(625089, "Soho: NoReqs"),
    "Soho - Pharmacy: Behind Phone Counter":                           PELocationData(625090, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 4 Right Shelf":                            PELocationData(625091, "Soho: NoReqs"),
    "Soho - Sam's Gun Shop: Upper Left Chest":                         PELocationData(625092, "Soho: WM"),
    "Soho - Sam's Gun Shop: Upper Right Chest":                        PELocationData(625093, "Soho: WM"),
    "Soho - Sam's Gun Shop: Behind Counter Chest":                     PELocationData(625094, "Soho: WM"),
    "Soho - Sam's Gun Shop: Lower Right Chest":                        PELocationData(625095, "Soho: WM"),
    "Soho - Sam's Gun Shop: Green Box":                                PELocationData(625096, "Soho: WM"),
    "Soho - Sam's Gun Shop: Red Box":                                  PELocationData(625097, "Soho: WM"),
    "Soho - Sam's Gun Shop: Shotgun Rack":                             PELocationData(625098, "Soho: WM"),
    "Soho - Sam's Gun Shop: Rifle Rack":                               PELocationData(625099, "Soho: WM"),
    "Hospital - 1F Outside: Maeda's Mayoke":                           PELocationData(625100, "Hospital: NoReqs"),
    "Hospital - 1F Lobby: Corner Ammo Chest":                          PELocationData(625101, "Hospital: NoReqs"),
    "Hospital - 1F Lobby: Closet Chest":                               PELocationData(625102, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Upper Chest":                              PELocationData(625103, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Lower Chest":                              PELocationData(625104, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Shelf Fuse Sparkle":                       PELocationData(625105, "Hospital: NoReqs"),
    "Hospital - B1 Save Office: Chest":                                PELocationData(625106, "Hospital: NoReqs"),
    "Hospital - B1 Save Office: Key Drawer":                           PELocationData(625107, "Hospital: NoReqs"),
    "Hospital - B1 Morgue: Chest":                                     PELocationData(625108, "Hospital: NoReqs"),
    "Hospital - B1 Autopsy: Lower Chest":                              PELocationData(625109, "Hospital: Combat+AK"),
    "Hospital - B1 Autopsy: Upper Chest":                              PELocationData(625110, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Corner Chest":                           PELocationData(625111, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Fuse Sparkle":                           PELocationData(625112, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Cardkey Corpse":                         PELocationData(625113, "Hospital: Combat+AK"),
    "Hospital - B1 Blue Hallway: 50/50 Chest":                         PELocationData(625114, "Hospital: Combat+BC"),
    "Hospital - B1 Collapsed Back Stairway: Sparkle":                  PELocationData(625115, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Right Chest":                   PELocationData(625116, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Left Chest":                    PELocationData(625117, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Fuse Sparkle":                  PELocationData(625118, "Hospital: Combat+BC"),
    "Hospital - 1F Emergency Room: Chest":                             PELocationData(625119, "Hospital: Combat"),
    "Hospital - 1F Flashback Room: Chest":                             PELocationData(625120, "Hospital: Combat"),
    "Hospital - 1F Flashback Room: Nurse":                             PELocationData(625121, "Hospital: Combat"),
    "Hospital - 1F Green Hallway: Chest":                              PELocationData(625122, "Hospital: Combat+GC"),
    "Hospital - 1F Nitrogen Storage: Chest":                           PELocationData(625123, "Hospital: Combat+GC"),
    "Hospital - 1F Nitrogen Storage: King Bacterium Drop":             PELocationData(625124, "Hospital: Combat+GC"),
    "Hospital - 13F Research Lab: Chest":                              PELocationData(625125, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Research Lab: Counter":                            PELocationData(625126, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Research Lab: Shelf":                              PELocationData(625127, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Kennel: Chest":                                    PELocationData(625128, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: Lower Chest":                PELocationData(625129, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: Upper Chest":                PELocationData(625130, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: 1st Sparkle (Junk)":         PELocationData(625131, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: 2nd Sparkle (Key)":          PELocationData(625132, "Hospital: Combat+BC+Fuses"),
    "Hospital - Roof Spiderwoman: Boss Drop":                          PELocationData(625133, "Hospital: Combat+BC+Fuses+EK+Boss"),
    "Chinatown - Near Entrance: Left Chest":                           PELocationData(625134, "Chinatown: NoReqs|Combat+GK"),
    "Chinatown - Near Entrance: Right Chest":                          PELocationData(625135, "Chinatown: NoReqs|Combat+GK"),
    "Chinatown - Antique Shop Exterior (Save): Lower Chest":           PELocationData(625136, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Exterior (Save): Upper Chest":           PELocationData(625137, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Interior: Chest":                        PELocationData(625138, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Interior: Shelf":                        PELocationData(625139, "Chinatown: Combat|Combat+GK"),
    "Chinatown - End of the Street: Chest":                            PELocationData(625140, "Chinatown: Combat|Combat+GK"),
    "Chinatown - End of the Street: Maeda's Narita":                   PELocationData(625141, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth A-04: Super Tool Sparkle":           PELocationData(625142, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-01: Medicine 4 Chest":             PELocationData(625143, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-03: Cure-D Sparkle":               PELocationData(625144, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-06: Ammo Chest":                   PELocationData(625145, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth C-02: Cr Protector Chest":           PELocationData(625146, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth C-06: Range Sparkle":                PELocationData(625147, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-03: M203-3 Chest":                 PELocationData(625148, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-08: M870 Chest":                   PELocationData(625149, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-11: Off or Def Chest":             PELocationData(625150, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth E-04: Medicine 3 Chest":             PELocationData(625151, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth E-10: Tool Sparkle":                 PELocationData(625152, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth F-09: Offense Chest":                PELocationData(625153, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Exit Catwalk: Club 3 Chest":                   PELocationData(625154, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Pump Station Exterior: Alligator Chest":              PELocationData(625155, "Chinatown: Combat+Boss|Combat+GK+Boss"),
    "Chinatown - Pump Station Exterior: Catwalk Chest":                PELocationData(625156, "Chinatown: Combat|GK"),
    "Chinatown - Pump Station Control Room: Chest":                    PELocationData(625157, "Chinatown: Combat|GK"),
    "Subway - Platform (Save): Bench Chest":                           PELocationData(625158, "Subway: Combat+PK|GK"),
    "Subway - Platform (Save): Phone Chest":                           PELocationData(625159, "Subway: Combat+PK|GK"),
    "Subway - Exit Stairway: Chest":                                   PELocationData(625160, "Subway: Combat+PK|GK"),
    "Subway - Left Mole Tunnel: Chest":                                PELocationData(625161, "Subway: Combat+PK|Combat+GK"),
    "Subway - Centipede: Boss Drop":                                   PELocationData(625162, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Right Chest":                      PELocationData(625163, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Left Chest":                       PELocationData(625164, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Lower Chest":                      PELocationData(625165, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Bridge: Cop's Gate Key":                                 PELocationData(625166, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Warehouse - Outside: Left Chest (Hidden)":                        PELocationData(625167, "Warehouse: NoReqs"),
    "Warehouse - Outside: Right Chest":                                PELocationData(625168, "Warehouse: NoReqs"),
    "Warehouse - Entrance: Forklift Chest":                            PELocationData(625169, "Warehouse: NoReqs"),
    "Warehouse - Tom and Jerry: Chest":                                PELocationData(625170, "Warehouse: Combat"),
    "Warehouse - Tom and Jerry: Key Sparkle":                          PELocationData(625171, "Warehouse: Combat"),
    "Warehouse - Save Room: Ladder Chest":                             PELocationData(625172, "Warehouse: Combat"),
    "Warehouse - Save Room: Upper Ground Chest":                       PELocationData(625173, "Warehouse: Combat"),
    "Warehouse - Save Room: Lower Ground Chest":                       PELocationData(625174, "Warehouse: Combat"),
    "Warehouse - Before Descent: Upper Left Chest":                    PELocationData(625175, "Warehouse: Combat+WK"),
    "Warehouse - Before Descent: Upper Left Chest":                    PELocationData(625176, "Warehouse: Combat+WK"),
    "Warehouse - Before Descent: Lower Left Chest":                    PELocationData(625177, "Warehouse: Combat+WK"),
    "Warehouse - Giant Enemy Crab: Boss Drop":                         PELocationData(625178, "Warehouse: Combat+WK+Boss"),
    "Warehouse - Giant Enemy Crab: Steamed Tool":                      PELocationData(625179, "Warehouse: Combat+WK+Boss"),
    "Museum - 1F Klamp Pursuit East Exhibit: Chest":                   PELocationData(625180, "Museum: NoReqs"),
    "Museum - 1F Klamp Pursuit West Exhibit: Chest":                   PELocationData(625181, "Museum: NoReqs"),
    "Museum - 1F Klamp Pursuit Troodon Hall: Right Chest":             PELocationData(625182, "Museum: Combat"),
    "Museum - 1F Klamp Pursuit Troodon Hall: Left Chest":              PELocationData(625183, "Museum: Combat"),
    "Museum - 1F Rainforest Employee Hallway: Chest":                  PELocationData(625184, "Museum: NoReqs"),
    "Museum - 1F Rainforest Storage Room: Lower Right Chest":          PELocationData(625185, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Lower Center Chest":         PELocationData(625186, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Upper Chest":                PELocationData(625187, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Right Chest":  PELocationData(625188, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Left Chest":   PELocationData(625189, "Museum: Combat"),
    "Museum - 1F Tribal Staircase: Chest":                             PELocationData(625190, "Museum: Combat"),
    "Museum - 1F Stone Head Room: Ladder Access Chest":                PELocationData(625191, "Museum: Combat"),
    "Museum - 1F Fire Escape: Stat Chest":                             PELocationData(625192, "Museum: Combat"),
    "Museum - 2F Gemstone Staircase: Right Chest":                     PELocationData(625193, "Museum: Combat"),
    "Museum - 2F Gemstone Staircase: Left Chest":                      PELocationData(625194, "Museum: Combat"),
    "Museum - 3F Fire Escape: Rocket Chest":                           PELocationData(625195, "Museum: Combat"),
    "Museum - 2F Festive Lobby: Revive Chest":                         PELocationData(625196, "Museum: Combat"),
    "Museum - 3F Pterodactyl Ambush Hall: Chest":                      PELocationData(625197, "Museum: Combat"),
    "Museum - 3F Stegosaurus Room: Chest":                             PELocationData(625198, "Museum: Combat"),
    "Museum - 2F Museum Shop Tents: Upper Chest":                      PELocationData(625199, "Museum: Combat"),
    "Museum - 2F Museum Shop Tents: Lower Chest":                      PELocationData(625200, "Museum: Combat"),
    "Museum - 2F Security Office: Chest":                              PELocationData(625201, "Museum: Combat"),
    "Museum - 4F Security Storage: Lower Right Chest":                 PELocationData(625202, "Museum: Combat"),
    "Museum - 4F Security Storage: Lower Left Chest":                  PELocationData(625203, "Museum: Combat"),
    "Museum - 4F Security Storage: Upper Left Chest":                  PELocationData(625204, "Museum: Combat"),
    "Museum - 4F Security Storage: Center Chest":                      PELocationData(625205, "Museum: Combat"),
    "Museum - 2F Klamp's Office: Maeda's Gun":                         PELocationData(625206, "Museum: Combat"),
    "Museum - 2F Klamp's Office: Klamp's Key":                         PELocationData(625207, "Museum: Combat"),
    "Museum - 4F Forgotten Landing: Full Recover Chest":               PELocationData(625208, "Museum: Combat"),
    "Museum - 2F Broken Display: Left Chest":                          PELocationData(625209, "Museum: Combat+KK"),
    "Museum - 2F Broken Display: Right Chest":                         PELocationData(625210, "Museum: Combat+KK"),
    "Museum - 3F Triceratops: Boss Drop":                              PELocationData(625211, "Museum: Combat+KK+Boss"),
    "Museum - 1F T-Rex: Left Chest":                                   PELocationData(625212, "Museum: NoReqs"),
    "Museum - 1F T-Rex: Right Chest":                                  PELocationData(625213, "Museum: NoReqs"),
    "Museum - 1F T-Rex: Boss Drop":                                    PELocationData(625214, "Museum: Combat+KK+Boss"),
    "Museum - 3F Final Approach: Right Chest Behind Glass":            PELocationData(625215, "Museum: Combat+KK+Boss"),
    "Museum - 3F Final Approach: Left Chest Behind Glass":             PELocationData(625216, "Museum: Combat+KK+Boss"),
    "Cruiser - Deck: Daniel's Sacrifice":                              PELocationData(625217, "Cruiser"),

    "Chrysler BLDG. - Treasurebox Set 1-01: Offense":                  PELocationData(625218, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: Cr Evade":                 PELocationData(625219, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: Tool":                     PELocationData(625220, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: USP-2":                    PELocationData(625221, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Tool A":                   PELocationData(625222, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: M1911A4":                  PELocationData(625223, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Tool B":                   PELocationData(625224, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Sp Vest 2":                PELocationData(625225, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: M16A2":                    PELocationData(625226, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: Tool":                     PELocationData(625227, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: Cr Evade":                 PELocationData(625228, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: PE":                       PELocationData(625229, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: Kv Jacket":                PELocationData(625230, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: M79-4":                    PELocationData(625231, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: P38 T Card":               PELocationData(625232, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: P228":                     PELocationData(625233, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: PE":                       PELocationData(625234, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: Cr Evade":                 PELocationData(625235, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-06: Sv Jacket":                PELocationData(625236, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-06: Cr Evade":                 PELocationData(625237, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: PE":                       PELocationData(625238, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: P226":                     PELocationData(625239, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: Defense":                  PELocationData(625240, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Range":                    PELocationData(625241, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Bullet Cap":               PELocationData(625242, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Rocket":                   PELocationData(625243, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Tool":                     PELocationData(625244, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Bullet Cap":               PELocationData(625245, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Offense A":                PELocationData(625246, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Offense B":                PELocationData(625247, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - 10F Spiderwoman EX: Boss Drop":                  PELocationData(625248, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 2-01: Cr Jacket":                PELocationData(625249, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-01: Defense":                  PELocationData(625250, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-02: Tool":                     PELocationData(625251, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: Tool A":                   PELocationData(625252, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: Tool B":                   PELocationData(625253, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: M203-5":                   PELocationData(625254, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: Tool":                     PELocationData(625255, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: M96":                      PELocationData(625256, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: Bullet Cap":               PELocationData(625257, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Kasul T Card":             PELocationData(625258, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Offense":                  PELocationData(625259, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Rocket":                   PELocationData(625260, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Super Tool":               PELocationData(625261, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Club 4":                   PELocationData(625262, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Defense":                  PELocationData(625263, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-07: AM44":                     PELocationData(625264, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-07: P229":                     PELocationData(625265, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-08: PE":                       PELocationData(625266, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-08: Sp Suit 1":                PELocationData(625267, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Full UZ":                  PELocationData(625268, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Range":                    PELocationData(625269, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Bhawk T Card":             PELocationData(625270, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-10: Kv Suit 1":                PELocationData(625271, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-10: Tool":                     PELocationData(625272, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - 20F Alligators EX: Boss Drops":                  PELocationData(625273, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 3-01: Tool":                     PELocationData(625274, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: Tool A":                   PELocationData(625275, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: PPKS T Card":              PELocationData(625276, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: Tool B":                   PELocationData(625277, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Bullet Cap":               PELocationData(625278, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Tool":                     PELocationData(625279, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Super Tool":               PELocationData(625280, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Super Tool":               PELocationData(625281, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Cr Evade":                 PELocationData(625282, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Mark 23":                  PELocationData(625283, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: Offense":                  PELocationData(625284, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: Tool":                     PELocationData(625285, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: M870-2":                   PELocationData(625286, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-06: Type64":                   PELocationData(625287, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-06: Defense":                  PELocationData(625288, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-07: Cm Jacket":                PELocationData(625289, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: B Jacket 2":               PELocationData(625290, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: M1 T Card":                PELocationData(625291, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: Offense":                  PELocationData(625292, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-09: Range":                    PELocationData(625293, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-09: Cr Evade":                 PELocationData(625294, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: Tool":                     PELocationData(625295, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: Sv Suit 1":                PELocationData(625296, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: M79-5":                    PELocationData(625297, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - 30F Centipede EX: Boss Drop":                    PELocationData(625298, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 4-01: PSG-1":                    PELocationData(625299, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Tool":                     PELocationData(625300, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Full Cure":                PELocationData(625301, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Bullet Cap":               PELocationData(625302, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Cm Suit 1":                PELocationData(625303, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Tool":                     PELocationData(625304, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Full Recover":             PELocationData(625305, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Tool":                     PELocationData(625306, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Rocket":                   PELocationData(625307, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Defense":                  PELocationData(625308, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Sv Suit 2":                PELocationData(625309, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: MP5A5":                    PELocationData(625310, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: MK5 T Card":               PELocationData(625311, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: Sp Armor 1":               PELocationData(625312, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: BAR T Card":               PELocationData(625313, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-05: Tool":                     PELocationData(625314, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-06: MP44 T Card":              PELocationData(625315, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: MG42 T Card":              PELocationData(625316, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: Cr Evade":                 PELocationData(625317, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: M1911A5":                  PELocationData(625318, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: Defense":                  PELocationData(625319, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-08: Maverick":                 PELocationData(625320, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-08: Range":                    PELocationData(625321, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-09: Kv Armor 1":               PELocationData(625322, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-10: Tool":                     PELocationData(625323, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - 40F Triceratops EX: Boss Drop":                  PELocationData(625324, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 5-01: SAR":                      PELocationData(625325, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-01: Tool":                     PELocationData(625326, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-01: M29 T Card":               PELocationData(625327, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: M73 T Card":               PELocationData(625328, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: PE":                       PELocationData(625329, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: Super Tool":               PELocationData(625330, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: AT4-1":                    PELocationData(625331, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-03: Tool":                     PELocationData(625332, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-03: Bullet Cap":               PELocationData(625333, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-04: Cr Suit 1":                PELocationData(625334, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-05: USP-3":                    PELocationData(625335, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Offense":                  PELocationData(625336, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Rocket":                   PELocationData(625337, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Cm Armor 1":               PELocationData(625338, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Tool":                     PELocationData(625339, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Range":                    PELocationData(625340, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-07: Tool":                     PELocationData(625341, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-08: B Suit 1":                 PELocationData(625342, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: G20":                      PELocationData(625343, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Tool":                     PELocationData(625344, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Offense":                  PELocationData(625345, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Sv Armor 1":               PELocationData(625346, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - 50F Cockroach: Boss Drop":                       PELocationData(625347, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Type38 T Card":            PELocationData(625348, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Cr Evade":                 PELocationData(625349, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Sp Armor 2":               PELocationData(625350, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-02: Rocket":                   PELocationData(625351, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-02: MP5SD6":                   PELocationData(625352, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-03: B Suit 2":                 PELocationData(625353, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-04: M712":                     PELocationData(625354, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: S12":                      PELocationData(625355, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: PE":                       PELocationData(625356, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: Full Recover":             PELocationData(625357, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: Cr Armor 1":               PELocationData(625358, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-06: Full Cure":                PELocationData(625359, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-07: FA-MAS":                   PELocationData(625360, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-08: Range":                    PELocationData(625361, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool A":                   PELocationData(625362, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool B":                   PELocationData(625363, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool C":                   PELocationData(625364, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - 60F Giant Enemy Crab EX: Boss Drop":             PELocationData(625365, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 7-01: PE":                       PELocationData(625366, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: M500-2":                   PELocationData(625367, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: Full Recover":             PELocationData(625368, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: M500":                     PELocationData(625369, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-02: Defense":                  PELocationData(625370, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: XM177E2":                  PELocationData(625371, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Tool":                     PELocationData(625372, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Range":                    PELocationData(625373, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Full Cure":                PELocationData(625374, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Super Tool":               PELocationData(625375, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Cm Armor 2":               PELocationData(625376, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Bullet Cap":               PELocationData(625377, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: B Armor":                  PELocationData(625378, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: M96R":                     PELocationData(625379, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: Super Tool":               PELocationData(625380, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: Tool":                     PELocationData(625381, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-06: Type3 T Card":             PELocationData(625382, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: M203-6":                   PELocationData(625383, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: Offense":                  PELocationData(625384, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: Sv Armor 2":               PELocationData(625385, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Eagle T Card":             PELocationData(625386, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: PE":                       PELocationData(625387, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Club 5":                   PELocationData(625388, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Cr Armor 2":               PELocationData(625389, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - 70F Queen Bee: Boss Drop":                       PELocationData(625390, "Chrysler BLDG.: Key 7"),

    "PE - Heal 1: Awakening":                                          PELocationData(625391, "Carnegie Hall: NoReqs"),
    "PE - Scan: Level 4":                                              PELocationData(625392, "PE"),
    "PE - Slow: Level 7":                                              PELocationData(625393, "PE"),
    "PE - Detox: Level 9":                                             PELocationData(625394, "PE"),
    "PE - Heal 2: Level 11":                                           PELocationData(625395, "PE"),
    "PE - Barrier: Level 13":                                          PELocationData(625396, "PE"),
    "PE - Energy Shot: Level 15":                                      PELocationData(625397, "PE"),
    "PE - Confuse: Level 17":                                          PELocationData(625398, "PE"),
    "PE - Haste: Level 20":                                            PELocationData(625399, "PE"),
    "PE - Heal 3: Level 22":                                           PELocationData(625400, "PE"),
    "PE - Gene Heal: Level 25":                                        PELocationData(625401, "PE"),
    "PE - Medic: Level 28":                                            PELocationData(625402, "PE"),
    "PE - Preraise: Level 30":                                         PELocationData(625403, "PE"),
    "PE - Full Recover: Level 32":                                     PELocationData(625404, "PE"),
    "PE - Liberate: Level 33":                                         PELocationData(625405, "PE"),
}

location_table = {name: data.address for name, data in location_data_table.items() if data.address is not None}
