from typing import Dict, NamedTuple, Optional

from BaseClasses import Location


class PELocation(Location):
    game = "Parasite Eve"

class PELocationData(NamedTuple):
    region: str
    address: Optional[int] = None


d1_location_data_table: Dict[str, PELocationData] = {

    "Carnegie Hall - F1 Backstage: Chest":                              PELocationData("Carnegie Hall: NoReqs",                     6245001),
    "Carnegie Hall - B1 Save Room: Chest":                              PELocationData("Carnegie Hall: Combat",                     6245002),
    "Carnegie Hall - B1 Save Room: Theater Corpse":                     PELocationData("Carnegie Hall: Combat",                     6245003),
    "Carnegie Hall - B1 Diary Room: Diary Key":                         PELocationData("Carnegie Hall: Combat+TK",                  6245004),
    "Carnegie Hall - B1 Diary Room: Closet":                            PELocationData("Carnegie Hall: Combat+TK",                  6245005),
    "Carnegie Hall - B1 Parrot Room: Closet":                           PELocationData("Carnegie Hall: Combat+TK",                  6245006),
    "Carnegie Hall - B1 Clown Locker Room: Locker":                     PELocationData("Carnegie Hall: Combat",                     6245007),
    "Carnegie Hall - B1 Burned Pair Locker Room: Locker":               PELocationData("Carnegie Hall: Combat",                     6245008),
    "Carnegie Hall - B1 Prop Room: Front Chest":                        PELocationData("Carnegie Hall: Combat+TK",                  6245009),
    "Carnegie Hall - B1 Prop Room: Hidden Chest":                       PELocationData("Carnegie Hall: Combat+TK",                  6245010),
    "Carnegie Hall - B1 Prop Room: Rat Cabinet":                        PELocationData("Carnegie Hall: Combat+TK",                  6245011),
    "Carnegie Hall - B1 Backstage Storage: Chest":                      PELocationData("Carnegie Hall: Combat+TK",                  6245012),
    "Carnegie Hall - Sewers Stairway: Chest":                           PELocationData("Carnegie Hall: Combat+RK",                  6245013),
    "Carnegie Hall - Sewers Ghost Girl: Back Left Chest":               PELocationData("Carnegie Hall: Combat+RK",                  6245014),
    "Carnegie Hall - Sewers Ghost Girl: Back Right Chest":              PELocationData("Carnegie Hall: Combat+RK",                  6245015),
    "Carnegie Hall - Sewers Ghost Girl: Front Left Chest":              PELocationData("Carnegie Hall: Combat+RK",                  6245016),
    "Carnegie Hall - Sewers Hidden Chest Room: Left Chest":             PELocationData("Carnegie Hall: Combat+RK",                  6245017),
    "Carnegie Hall - Sewers Hidden Chest Room: Center Chest":           PELocationData("Carnegie Hall: Combat+RK",                  6245018),
    "Carnegie Hall - Sewers Hidden Chest Room: Right Chest":            PELocationData("Carnegie Hall: Combat+RK",                  6245019),
    "Carnegie Hall - Sewers Hidden Chest Room: Valve Chest":            PELocationData("Carnegie Hall: Combat+RK",                  6245020),
    "Carnegie Hall - Sewers Alligator: Boss Drop":                      PELocationData("Carnegie Hall: Combat+RK+Boss",             6245021),

}

d2_location_data_table: Dict[str, PELocationData] = {

    "N.Y.P.D. #17 - D2 1F Baker's Office: Baker Permit 1":              PELocationData("N.Y.P.D. #17: NoReqs",                      6245022),
    "N.Y.P.D. #17 - D2 1F Locker Room: Right Locker":                   PELocationData("N.Y.P.D. #17: NoReqs",                      6245023),
    "N.Y.P.D. #17 - D2 1F Locker Room: Center Locker":                  PELocationData("N.Y.P.D. #17: NoReqs",                      6245024),
    "N.Y.P.D. #17 - D2 1F Conference Room: Baker Permit 2":             PELocationData("N.Y.P.D. #17: NoReqs",                      6245025),
    "N.Y.P.D. #17 - D2 B1 Weapons Department: M16A1":                   PELocationData("N.Y.P.D. #17: NoReqs",                      6245026),
    "N.Y.P.D. #17 - D3 1F Entrance: Maeda's Hamaya":                    PELocationData("N.Y.P.D. #17: SJ",                          6245027),
    "N.Y.P.D. #17 - D3 1F Main Hall: Cop's Ammo":                       PELocationData("N.Y.P.D. #17: SJ",                          6245028),
    "N.Y.P.D. #17 - D3 1F Main Hall: Nix's Ammo":                       PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245029),
    "N.Y.P.D. #17 - D3 1F Save Room: Warner's Ammo":                    PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245030),
    "N.Y.P.D. #17 - D3 1F Locker Room: Right Locker":                   PELocationData("N.Y.P.D. #17: SJ",                          6245031),
    "N.Y.P.D. #17 - D3 1F Locker Room: Cop's Ammo":                     PELocationData("N.Y.P.D. #17: SJ",                          6245032),
    "N.Y.P.D. #17 - D2 1F Locker Room: Locked Locker":                  PELocationData("N.Y.P.D. #17: LK",                          6245033),
    "N.Y.P.D. #17 - D3 B1 Weapons Department: Torres's Gun":            PELocationData("N.Y.P.D. #17: SJ",                          6245034),
    "N.Y.P.D. #17 - D3 B1 Kennel: Cathy's Ammo":                        PELocationData("N.Y.P.D. #17: SJ",                          6245035),
    "N.Y.P.D. #17 - D3 1F Conference Room: Spider Chest":               PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245036),
    "N.Y.P.D. #17 - D3 2F Barred Staircase: Cop's Ammo":                PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245037),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Left Chest":                   PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245038),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Right Chest":                  PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245039),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Chest":                   PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245040),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Table Sparkle":           PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245041),
    "N.Y.P.D. #17 - D3 2F Save Office: Desk Chest":                     PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245042),
    "N.Y.P.D. #17 - D3 2F Save Office: Floor Chest":                    PELocationData("N.Y.P.D. #17: Combat+SJ",                   6245043),
    "N.Y.P.D. #17 - D3 3F Ambush Hall: Cop's Locker Key":               PELocationData("N.Y.P.D. #17: Combat+SJ+Boss",              6245044),
    "N.Y.P.D. #17 - D4 3F Medical Office: Daniel's Ammo":               PELocationData("N.Y.P.D. #17: Combat+SJ+Boss",              6245045),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Chest":                         PELocationData("N.Y.P.D. #17: Combat+SJ+Boss",              6245046),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Boss Drop":                     PELocationData("N.Y.P.D. #17: Combat+SJ+Boss",              6245047),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Cop's Ammo":                    PELocationData("N.Y.P.D. #17: Combat+SJ+Boss",              6245048),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf's Backroom: Chest":              PELocationData("N.Y.P.D. #17: Combat+SJ+Boss",              6245049),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Left Chest":                 PELocationData("N.Y.P.D. #17: SK",                          6245050),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Center Chest":               PELocationData("N.Y.P.D. #17: SK",                          6245051),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Right Chest":                PELocationData("N.Y.P.D. #17: SK",                          6245052),
    "N.Y.P.D. #17 - D3 3F Kerberos: Boss Drop":                         PELocationData("N.Y.P.D. #17: Combat+SJ+Boss",              6245053),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Tool Kit":                PELocationData("N.Y.P.D. #17: Combat+SJ+Boss+UC+12RTC",     6245054),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Super Tool Kit":          PELocationData("N.Y.P.D. #17: Combat+SJ+Boss+UC+14RTC",     6245055),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Leave It to Wayne":       PELocationData("N.Y.P.D. #17: Combat+SJ+Boss+UC+JunkReq",   6245056),
    "Central Park - Entrance: Car Chest":                               PELocationData("Central Park: NoReqs",                      6245057),
    "Central Park - Entrance: Snake Chest":                             PELocationData("Central Park: NoReqs",                      6245058),
    "Central Park - Front Gate: Left Chest":                            PELocationData("Central Park: Combat",                      6245059),
    "Central Park - Front Gate: Right Chest":                           PELocationData("Central Park: Combat",                      6245060),
    "Central Park - Courtyard: Left Gun Chest":                         PELocationData("Central Park: Combat",                      6245061),
    "Central Park - Courtyard: Right Tool Chest":                       PELocationData("Central Park: Combat",                      6245062),
    "Central Park - Office: Key Drawer":                                PELocationData("Central Park: Combat",                      6245063),
    "Central Park - Office: Cabinet":                                   PELocationData("Central Park: Combat",                      6245064),
    "Central Park - Office: Locked Cupboard":                           PELocationData("Central Park: Combat+ZK",                   6245065),
    "Central Park - Snake Exhibit: Upper Right Chest":                  PELocationData("Central Park: Combat+ZK",                   6245066),
    "Central Park - Snake Exhibit: Lower Left Chest":                   PELocationData("Central Park: Combat+ZK",                   6245067),
    "Central Park - Snake Exhibit: Lower Right Chest":                  PELocationData("Central Park: Combat+ZK",                   6245068),
    "Central Park - Back Courtyard: Ammo Chest":                        PELocationData("Central Park: Combat",                      6245069),
    "Central Park - Figure 8: Right Chest":                             PELocationData("Central Park: Combat",                      6245070),
    "Central Park - Figure 8: Left Chest":                              PELocationData("Central Park: Combat",                      6245071),
    "Central Park - Gazebo: Left Chest":                                PELocationData("Central Park: Combat+ZK",                   6245072),
    "Central Park - Gazebo: Right Chest":                               PELocationData("Central Park: Combat+ZK",                   6245073),
    "Central Park - Behind Gazebo (Save): Chest":                       PELocationData("Central Park: Combat+ZK",                   6245074),
    "Central Park - Forest Maze West: Mythical Tool Chest":             PELocationData("Central Park: Combat+ZK",                   6245075),
    "Central Park - Forest Maze Bridge: Chest":                         PELocationData("Central Park: Combat+ZK",                   6245076),
    "Central Park - Forest Maze Dock: Chest":                           PELocationData("Central Park: Combat+ZK",                   6245077),
    "Central Park - Forest Maze East: Backup Tool Chest":               PELocationData("Central Park: Combat+ZK",                   6245078),
    "Central Park - Under Bush Bridge: Left Stat Chest":                PELocationData("Central Park: Combat+ZK",                   6245079),
    "Central Park - Under Bush Bridge: Right YOLO Tool Chest":          PELocationData("Central Park: Combat+ZK",                   6245080),

}

d3_location_data_table: Dict[str, PELocationData] = {
    
    "Soho - Apartment Interior: Chest":                                 PELocationData("Soho: NoReqs",                              6245081),
    "Soho - Apartment Exterior: Trash Card":                            PELocationData("Soho: NoReqs",                              6245082),
    "Soho - Pharmacy: Aisle 3 Medicine Chest":                          PELocationData("Soho: NoReqs",                              6245083),
    "Soho - Pharmacy: Aisle 5 Revive Chest":                            PELocationData("Soho: NoReqs",                              6245084),
    "Soho - Pharmacy: Backroom Left Chest":                             PELocationData("Soho: NoReqs",                              6245085),
    "Soho - Pharmacy: Backroom Right Chest":                            PELocationData("Soho: NoReqs",                              6245086),
    "Soho - Pharmacy: Aisle 1 Left Shelf":                              PELocationData("Soho: NoReqs",                              6245087),
    "Soho - Pharmacy: Aisle 3 Far Back Shelf":                          PELocationData("Soho: NoReqs",                              6245088),
    "Soho - Pharmacy: Behind Phone Counter":                            PELocationData("Soho: NoReqs",                              6245089),
    "Soho - Pharmacy: Aisle 4 Right Shelf":                             PELocationData("Soho: NoReqs",                              6245090),
    "Soho - Sam's Gun Shop: Upper Left Chest":                          PELocationData("Soho: WM",                                  6245091),
    "Soho - Sam's Gun Shop: Upper Right Chest":                         PELocationData("Soho: WM",                                  6245092),
    "Soho - Sam's Gun Shop: Behind Counter Chest":                      PELocationData("Soho: WM",                                  6245093),
    "Soho - Sam's Gun Shop: Lower Right Chest":                         PELocationData("Soho: WM",                                  6245094),
    "Soho - Sam's Gun Shop: Green Box":                                 PELocationData("Soho: WM",                                  6245095),
    "Soho - Sam's Gun Shop: Red Box":                                   PELocationData("Soho: WM",                                  6245096),
    "Soho - Sam's Gun Shop: Shotgun Rack":                              PELocationData("Soho: WM",                                  6245097),
    "Soho - Sam's Gun Shop: Rifle Rack":                                PELocationData("Soho: WM",                                  6245098),
    "Hospital - 1F Outside: Maeda's Mayoke":                            PELocationData("Hospital: NoReqs",                          6245099),
    "Hospital - 1F Lobby: Corner Ammo Chest":                           PELocationData("Hospital: NoReqs",                          6245100),
    "Hospital - 1F Lobby: Closet Chest":                                PELocationData("Hospital: NoReqs",                          6245101),
    "Hospital - B1 Storage: Upper Chest":                               PELocationData("Hospital: NoReqs",                          6245102),
    "Hospital - B1 Storage: Lower Chest":                               PELocationData("Hospital: NoReqs",                          6245103),
    "Hospital - B1 Storage: Shelf Fuse Sparkle":                        PELocationData("Hospital: NoReqs",                          6245104),
    "Hospital - B1 Save Office: Chest":                                 PELocationData("Hospital: NoReqs",                          6245105),
    "Hospital - B1 Save Office: Key Drawer":                            PELocationData("Hospital: NoReqs",                          6245106),
    "Hospital - B1 Morgue: Chest":                                      PELocationData("Hospital: NoReqs",                          6245107),
    "Hospital - B1 Autopsy: Lower Chest":                               PELocationData("Hospital: Combat+AK",                       6245108),
    "Hospital - B1 Autopsy: Upper Chest":                               PELocationData("Hospital: Combat+AK",                       6245109),
    "Hospital - B1 Crematory: Corner Chest":                            PELocationData("Hospital: Combat+AK",                       6245110),
    "Hospital - B1 Crematory: Fuse Sparkle":                            PELocationData("Hospital: Combat+AK",                       6245111),
    "Hospital - B1 Crematory: Cardkey Corpse":                          PELocationData("Hospital: Combat+AK",                       6245112),
    "Hospital - B1 Blue Hallway: 50/50 Chest":                          PELocationData("Hospital: Combat+BC",                       6245113),
    "Hospital - B1 Collapsed Back Stairway: Sparkle":                   PELocationData("Hospital: Combat+BC",                       6245114),
    "Hospital - B1 Sterilization Room: Right Chest":                    PELocationData("Hospital: Combat+BC",                       6245115),
    "Hospital - B1 Sterilization Room: Left Chest":                     PELocationData("Hospital: Combat+BC",                       6245116),
    "Hospital - B1 Sterilization Room: Fuse Sparkle":                   PELocationData("Hospital: Combat+BC",                       6245117),
    "Hospital - 1F Emergency Room: Chest":                              PELocationData("Hospital: Combat",                          6245118),
    "Hospital - 1F Flashback Room: Chest":                              PELocationData("Hospital: Combat",                          6245119),
    "Hospital - 1F Flashback Room: Nurse":                              PELocationData("Hospital: Combat",                          6245120),
    "Hospital - 1F Green Hallway: Chest":                               PELocationData("Hospital: Combat+GC",                       6245121),
    "Hospital - 1F Nitrogen Storage: Chest":                            PELocationData("Hospital: Combat+GC",                       6245122),
    "Hospital - 1F Nitrogen Storage: King Bacterium Drop":              PELocationData("Hospital: Combat+GC",                       6245123),
    "Hospital - 13F Research Lab: Chest":                               PELocationData("Hospital: Combat+BC+Fuses",                 6245124),
    "Hospital - 13F Research Lab: Counter":                             PELocationData("Hospital: Combat+BC+Fuses",                 6245125),
    "Hospital - 13F Research Lab: Shelf":                               PELocationData("Hospital: Combat+BC+Fuses",                 6245126),
    "Hospital - 13F Kennel: Chest":                                     PELocationData("Hospital: Combat+BC+Fuses",                 6245127),
    "Hospital - 13F Roof Elevator Access: Lower Chest":                 PELocationData("Hospital: Combat+BC+Fuses",                 6245128),
    "Hospital - 13F Roof Elevator Access: Upper Chest":                 PELocationData("Hospital: Combat+BC+Fuses",                 6245129),
    "Hospital - 13F Roof Elevator Access: 1st Sparkle (Junk)":          PELocationData("Hospital: Combat+BC+Fuses",                 6245130),
    "Hospital - 13F Roof Elevator Access: 2nd Sparkle (Key)":           PELocationData("Hospital: Combat+BC+Fuses",                 6245131),
    "Hospital - Roof Spiderwoman: Boss Drop":                           PELocationData("Hospital: Combat+BC+Fuses+EK+Boss",         6245132),

}

d5_location_data_table: Dict[str, PELocationData] = {

    "Chinatown - Near Entrance: Left Chest":                            PELocationData("Chinatown: NoReqs|Combat+GK",               6245133),
    "Chinatown - Near Entrance: Right Chest":                           PELocationData("Chinatown: NoReqs|Combat+GK",               6245134),
    "Chinatown - Antique Shop Exterior (Save): Lower Chest":            PELocationData("Chinatown: Combat|Combat+GK",               6245135),
    "Chinatown - Antique Shop Exterior (Save): Upper Chest":            PELocationData("Chinatown: Combat|Combat+GK",               6245136),
    "Chinatown - Antique Shop Interior: Chest":                         PELocationData("Chinatown: Combat|Combat+GK",               6245137),
    "Chinatown - Antique Shop Interior: Shelf":                         PELocationData("Chinatown: Combat|Combat+GK",               6245138),
    "Chinatown - End of the Street: Chest":                             PELocationData("Chinatown: Combat|Combat+GK",               6245139),
    "Chinatown - End of the Street: Maeda's Narita":                    PELocationData("Chinatown: Combat|Combat+GK",               6245140),
    "Chinatown - Sewers Labyrinth A-04: Super Tool Sparkle":            PELocationData("Chinatown: Combat|Combat+GK",               6245141),
    "Chinatown - Sewers Labyrinth B-01: Medicine 4 Chest":              PELocationData("Chinatown: Combat|Combat+GK",               6245142),
    "Chinatown - Sewers Labyrinth B-03: Cure-D Sparkle":                PELocationData("Chinatown: Combat|Combat+GK",               6245143),
    "Chinatown - Sewers Labyrinth B-06: Ammo Chest":                    PELocationData("Chinatown: Combat|Combat+GK",               6245144),
    "Chinatown - Sewers Labyrinth C-02: Cr Protector Chest":            PELocationData("Chinatown: Combat|Combat+GK",               6245145),
    "Chinatown - Sewers Labyrinth C-06: Range Sparkle":                 PELocationData("Chinatown: Combat|Combat+GK",               6245146),
    "Chinatown - Sewers Labyrinth D-03: M203-3 Chest":                  PELocationData("Chinatown: Combat|Combat+GK",               6245147),
    "Chinatown - Sewers Labyrinth D-08: M870 Chest":                    PELocationData("Chinatown: Combat|Combat+GK",               6245148),
    "Chinatown - Sewers Labyrinth D-11: Off or Def Chest":              PELocationData("Chinatown: Combat|Combat+GK",               6245149),
    "Chinatown - Sewers Labyrinth E-04: Medicine 3 Chest":              PELocationData("Chinatown: Combat|Combat+GK",               6245150),
    "Chinatown - Sewers Labyrinth E-10: Tool Sparkle":                  PELocationData("Chinatown: Combat|Combat+GK",               6245151),
    "Chinatown - Sewers Labyrinth F-09: Offense Chest":                 PELocationData("Chinatown: Combat|Combat+GK",               6245152),
    "Chinatown - Sewers Exit Catwalk: Club 3 Chest":                    PELocationData("Chinatown: Combat|Combat+GK",               6245153),
    "Chinatown - Pump Station Exterior: Alligator Chest":               PELocationData("Chinatown: Combat+Boss|Combat+GK+Boss",     6245154),
    "Chinatown - Pump Station Exterior: Catwalk Chest":                 PELocationData("Chinatown: Combat|GK",                      6245155),
    "Chinatown - Pump Station Control Room: Chest":                     PELocationData("Chinatown: Combat|GK",                      6245156),
    "Subway - Platform (Save): Bench Chest":                            PELocationData("Subway: Combat+PK|GK",                      6245157),
    "Subway - Platform (Save): Phone Chest":                            PELocationData("Subway: Combat+PK|GK",                      6245158),
    "Subway - Exit Stairway: Chest":                                    PELocationData("Subway: Combat+PK|GK",                      6245159),
    "Subway - Left Mole Tunnel: Chest":                                 PELocationData("Subway: Combat+PK|Combat+GK",               6245160),
    "Subway - Centipede: Boss Drop":                                    PELocationData("Subway: Combat+PK+Boss|Combat+GK+Boss",     6245161),
    "Subway - Parked Passenger Car: Right Chest":                       PELocationData("Subway: Combat+PK+Boss|Combat+GK+Boss",     6245162),
    "Subway - Parked Passenger Car: Left Chest":                        PELocationData("Subway: Combat+PK+Boss|Combat+GK+Boss",     6245163),
    "Subway - Parked Passenger Car: Lower Chest":                       PELocationData("Subway: Combat+PK+Boss|Combat+GK+Boss",     6245164),
    "Subway - Bridge: Cop's Gate Key":                                  PELocationData("Subway: Combat+PK+Boss|Combat+GK+Boss",     6245165),
    "Warehouse - Outside: Left Chest (Hidden)":                         PELocationData("Warehouse: NoReqs",                         6245166),
    "Warehouse - Outside: Right Chest":                                 PELocationData("Warehouse: NoReqs",                         6245167),
    "Warehouse - Entrance: Forklift Chest":                             PELocationData("Warehouse: NoReqs",                         6245168),
    "Warehouse - Tom and Jerry: Chest":                                 PELocationData("Warehouse: Combat",                         6245169),
    "Warehouse - Tom and Jerry: Key Sparkle":                           PELocationData("Warehouse: Combat",                         6245170),
    "Warehouse - Save Room: Ladder Chest":                              PELocationData("Warehouse: Combat",                         6245171),
    "Warehouse - Save Room: Upper Ground Chest":                        PELocationData("Warehouse: Combat",                         6245172),
    "Warehouse - Save Room: Lower Ground Chest":                        PELocationData("Warehouse: Combat",                         6245173),
    "Warehouse - Before Descent: Upper Left Chest":                     PELocationData("Warehouse: Combat+WK",                      6245174),
    "Warehouse - Before Descent: Upper Left Chest":                     PELocationData("Warehouse: Combat+WK",                      6245175),
    "Warehouse - Before Descent: Lower Left Chest":                     PELocationData("Warehouse: Combat+WK",                      6245176),
    "Warehouse - Giant Enemy Crab: Boss Drop":                          PELocationData("Warehouse: Combat+WK+Boss",                 6245177),
    "Warehouse - Giant Enemy Crab: Steamed Tool":                       PELocationData("Warehouse: Combat+WK+Boss",                 6245178),
    "Museum - 1F Klamp Pursuit East Exhibit: Chest":                    PELocationData("Museum: NoReqs",                            6245179),
    "Museum - 1F Klamp Pursuit West Exhibit: Chest":                    PELocationData("Museum: NoReqs",                            6245180),
    "Museum - 1F Klamp Pursuit Troodon Hall: Right Chest":              PELocationData("Museum: Combat",                            6245181),
    "Museum - 1F Klamp Pursuit Troodon Hall: Left Chest":               PELocationData("Museum: Combat",                            6245182),
    "Museum - 1F Rainforest Employee Hallway: Chest":                   PELocationData("Museum: NoReqs",                            6245183),
    "Museum - 1F Rainforest Storage Room: Lower Right Chest":           PELocationData("Museum: Combat",                            6245184),
    "Museum - 1F Rainforest Storage Room: Lower Center Chest":          PELocationData("Museum: Combat",                            6245185),
    "Museum - 1F Rainforest Storage Room: Upper Chest":                 PELocationData("Museum: Combat",                            6245186),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Right Chest":   PELocationData("Museum: Combat",                            6245187),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Left Chest":    PELocationData("Museum: Combat",                            6245188),
    "Museum - 1F Tribal Staircase: Chest":                              PELocationData("Museum: Combat",                            6245189),
    "Museum - 1F Stone Head Room: Ladder Access Chest":                 PELocationData("Museum: Combat",                            6245190),
    "Museum - 1F Fire Escape: Stat Chest":                              PELocationData("Museum: Combat",                            6245191),
    "Museum - 2F Gemstone Staircase: Right Chest":                      PELocationData("Museum: Combat",                            6245192),
    "Museum - 2F Gemstone Staircase: Left Chest":                       PELocationData("Museum: Combat",                            6245193),
    "Museum - 3F Fire Escape: Rocket Chest":                            PELocationData("Museum: Combat",                            6245194),
    "Museum - 2F Festive Lobby: Revive Chest":                          PELocationData("Museum: Combat",                            6245195),
    "Museum - 3F Pterodactyl Ambush Hall: Chest":                       PELocationData("Museum: Combat",                            6245196),
    "Museum - 3F Stegosaurus Room: Chest":                              PELocationData("Museum: Combat",                            6245197),
    "Museum - 2F Museum Shop Tents: Upper Chest":                       PELocationData("Museum: Combat",                            6245198),
    "Museum - 2F Museum Shop Tents: Lower Chest":                       PELocationData("Museum: Combat",                            6245199),
    "Museum - 2F Security Office: Chest":                               PELocationData("Museum: Combat",                            6245200),
    "Museum - 4F Security Storage: Lower Right Chest":                  PELocationData("Museum: Combat",                            6245201),
    "Museum - 4F Security Storage: Lower Left Chest":                   PELocationData("Museum: Combat",                            6245202),
    "Museum - 4F Security Storage: Upper Left Chest":                   PELocationData("Museum: Combat",                            6245203),
    "Museum - 4F Security Storage: Center Chest":                       PELocationData("Museum: Combat",                            6245204),
    "Museum - 2F Klamp's Office: Maeda's Gun":                          PELocationData("Museum: Combat",                            6245205),
    "Museum - 2F Klamp's Office: Klamp's Key":                          PELocationData("Museum: Combat",                            6245206),
    "Museum - 4F Forgotten Landing: Full Recover Chest":                PELocationData("Museum: Combat",                            6245207),
    "Museum - 2F Broken Display: Left Chest":                           PELocationData("Museum: Combat+KK",                         6245208),
    "Museum - 2F Broken Display: Right Chest":                          PELocationData("Museum: Combat+KK",                         6245209),
    "Museum - 3F Triceratops: Boss Drop":                               PELocationData("Museum: Combat+KK+Boss",                    6245210),
    "Museum - 1F T-Rex: Left Chest":                                    PELocationData("Museum: NoReqs",                            6245211),
    "Museum - 1F T-Rex: Right Chest":                                   PELocationData("Museum: NoReqs",                            6245212),
    "Museum - 1F T-Rex: Boss Drop":                                     PELocationData("Museum: Combat+KK+Boss",                    6245213),
    "Museum - 3F Final Approach: Right Chest Behind Glass":             PELocationData("Museum: Combat+KK+Boss",                    6245214),
    "Museum - 3F Final Approach: Left Chest Behind Glass":              PELocationData("Museum: Combat+KK+Boss",                    6245215),
    "Cruiser - Deck: Daniel's Sacrifice":                               PELocationData("Cruiser",                                   6245216),
}

location_data_table: Dict[str, PELocationData] = {**d1_location_data_table,
                                                  **d2_location_data_table,
                                                  **d3_location_data_table,
                                                  **d5_location_data_table}

location_table = {name: data.address for name, data in location_data_table.items() if data.address is not None}
