from typing import Dict, NamedTuple, Optional

from BaseClasses import Location


class PELocation(Location):
    game = "Parasite Eve"

class PELocationData(NamedTuple):
    address: Optional[int] = None
    region: str


location_data_table: Dict[str, PELocationData] = {

    "Carnegie Hall - F1 Backstage: Chest":                             PELocationData(6250001, "Carnegie Hall: NoReqs"),
    "Carnegie Hall - B1 Save Room: Chest":                             PELocationData(6250002, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Save Room: Theater Corpse":                    PELocationData(6250003, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Diary Room: Diary Key":                        PELocationData(6250004, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Diary Room: Closet":                           PELocationData(6250005, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Parrot Room: Closet":                          PELocationData(6250006, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Clown Locker Room: Locker":                    PELocationData(6250007, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Burned Pair Locker Room: Locker":              PELocationData(6250008, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Prop Room: Front Chest":                       PELocationData(6250009, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Hidden Chest":                      PELocationData(6250010, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Rat Cabinet":                       PELocationData(6250011, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Backstage Storage: Chest":                     PELocationData(6250012, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - Sewers Stairway: Chest":                          PELocationData(6250013, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Left Chest":              PELocationData(6250014, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Right Chest":             PELocationData(6250015, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Front Left Chest":             PELocationData(6250016, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Left Chest":            PELocationData(6250017, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Center Chest":          PELocationData(6250018, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Right Chest":           PELocationData(6250019, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Valve Chest":           PELocationData(6250020, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Alligator: Boss Drop":                     PELocationData(6250021, "Carnegie Hall: Combat+RK+Boss"),
    "N.Y.P.D. #17 - D2 1F Baker's Office: Baker Permit 1":             PELocationData(6250022, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Right Locker":                  PELocationData(6250023, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Center Locker":                 PELocationData(6250024, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Conference Room: Baker Permit 2":            PELocationData(6250025, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 B1 Weapons Department: M16A1":                  PELocationData(6250026, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D3 1F Entrance: Maeda's Hamaya":                   PELocationData(6250027, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Cop's Ammo":                      PELocationData(6250028, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Nix's Ammo":                      PELocationData(6250029, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Save Room: Warner's Ammo":                   PELocationData(6250030, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Right Locker":                  PELocationData(6250031, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Cop's Ammo":                    PELocationData(6250032, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Locked Locker":                 PELocationData(6250033, "N.Y.P.D. #17: LK"),
    "N.Y.P.D. #17 - D3 B1 Weapons Department: Torres's Gun":           PELocationData(6250034, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 B1 Kennel: Cathy's Ammo":                       PELocationData(6250035, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Conference Room: Spider Chest":              PELocationData(6250036, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Barred Staircase: Cop's Ammo":               PELocationData(6250037, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Left Chest":                  PELocationData(6250038, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Right Chest":                 PELocationData(6250039, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Chest":                  PELocationData(6250040, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Table Sparkle":          PELocationData(6250041, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Desk Chest":                    PELocationData(6250042, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Floor Chest":                   PELocationData(6250043, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 3F Ambush Hall: Cop's Locker Key":              PELocationData(6250044, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D4 3F Medical Office: Daniel's Ammo":              PELocationData(6250045, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Chest":                        PELocationData(6250046, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Boss Drop":                    PELocationData(6250047, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Cop's Ammo":                   PELocationData(6250048, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf's Backroom: Chest":             PELocationData(6250049, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Left Chest":                PELocationData(6250050, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Center Chest":              PELocationData(6250051, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Right Chest":               PELocationData(6250052, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D3 3F Kerberos: Boss Drop":                        PELocationData(6250053, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Tool Kit":               PELocationData(6250054, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+12RTC"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Super Tool Kit":         PELocationData(6250055, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+14RTC"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Leave It to Wayne":      PELocationData(6250056, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+JunkReq"),
    "Central Park - Entrance: Car Chest":                              PELocationData(6250057, "Central Park: NoReqs"),
    "Central Park - Entrance: Snake Chest":                            PELocationData(6250058, "Central Park: NoReqs"),
    "Central Park - Front Gate: Left Chest":                           PELocationData(6250059, "Central Park: Combat"),
    "Central Park - Front Gate: Right Chest":                          PELocationData(6250060, "Central Park: Combat"),
    "Central Park - Courtyard: Left Gun Chest":                        PELocationData(6250061, "Central Park: Combat"),
    "Central Park - Courtyard: Right Tool Chest":                      PELocationData(6250062, "Central Park: Combat"),
    "Central Park - Office: Key Drawer":                               PELocationData(6250063, "Central Park: Combat"),
    "Central Park - Office: Cabinet":                                  PELocationData(6250064, "Central Park: Combat"),
    "Central Park - Office: Locked Cupboard":                          PELocationData(6250065, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Upper Right Chest":                 PELocationData(6250066, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Left Chest":                  PELocationData(6250067, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Right Chest":                 PELocationData(6250068, "Central Park: Combat+ZK"),
    "Central Park - Back Courtyard: Ammo Chest":                       PELocationData(6250069, "Central Park: Combat"),
    "Central Park - Figure 8: Right Chest":                            PELocationData(6250070, "Central Park: Combat"),
    "Central Park - Figure 8: Left Chest":                             PELocationData(6250071, "Central Park: Combat"),
    "Central Park - Gazebo: Left Chest":                               PELocationData(6250072, "Central Park: Combat+ZK"),
    "Central Park - Gazebo: Right Chest":                              PELocationData(6250073, "Central Park: Combat+ZK"),
    "Central Park - Behind Gazebo (Save): Chest":                      PELocationData(6250074, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze West: Mythical Tool Chest":            PELocationData(6250075, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Bridge: Chest":                        PELocationData(6250076, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Dock: Chest":                          PELocationData(6250077, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze East: Backup Tool Chest":              PELocationData(6250078, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Left Stat Chest":               PELocationData(6250079, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Right YOLO Tool Chest":         PELocationData(6250080, "Central Park: Combat+ZK"),
    "Central Park - Flaming Carriage Eve 2: Boss Drop":                PELocationData(6250081, "Central Park: Combat+ZK+Boss"),
    "Soho - Apartment Interior: Chest":                                PELocationData(6250082, "Soho: NoReqs"),
    "Soho - Apartment Exterior: Trash Card":                           PELocationData(6250083, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 3 Medicine Chest":                         PELocationData(6250084, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 5 Revive Chest":                           PELocationData(6250085, "Soho: NoReqs"),
    "Soho - Pharmacy: Backroom Left Chest":                            PELocationData(6250086, "Soho: NoReqs"),
    "Soho - Pharmacy: Backroom Right Chest":                           PELocationData(6250087, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 1 Left Shelf":                             PELocationData(6250088, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 3 Far Back Shelf":                         PELocationData(6250089, "Soho: NoReqs"),
    "Soho - Pharmacy: Behind Phone Counter":                           PELocationData(6250090, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 4 Right Shelf":                            PELocationData(6250091, "Soho: NoReqs"),
    "Soho - Sam's Gun Shop: Upper Left Chest":                         PELocationData(6250092, "Soho: WM"),
    "Soho - Sam's Gun Shop: Upper Right Chest":                        PELocationData(6250093, "Soho: WM"),
    "Soho - Sam's Gun Shop: Behind Counter Chest":                     PELocationData(6250094, "Soho: WM"),
    "Soho - Sam's Gun Shop: Lower Right Chest":                        PELocationData(6250095, "Soho: WM"),
    "Soho - Sam's Gun Shop: Green Box":                                PELocationData(6250096, "Soho: WM"),
    "Soho - Sam's Gun Shop: Red Box":                                  PELocationData(6250097, "Soho: WM"),
    "Soho - Sam's Gun Shop: Shotgun Rack":                             PELocationData(6250098, "Soho: WM"),
    "Soho - Sam's Gun Shop: Rifle Rack":                               PELocationData(6250099, "Soho: WM"),
    "Hospital - 1F Outside: Maeda's Mayoke":                           PELocationData(6250100, "Hospital: NoReqs"),
    "Hospital - 1F Lobby: Corner Ammo Chest":                          PELocationData(6250101, "Hospital: NoReqs"),
    "Hospital - 1F Lobby: Closet Chest":                               PELocationData(6250102, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Upper Chest":                              PELocationData(6250103, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Lower Chest":                              PELocationData(6250104, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Shelf Fuse Sparkle":                       PELocationData(6250105, "Hospital: NoReqs"),
    "Hospital - B1 Save Office: Chest":                                PELocationData(6250106, "Hospital: NoReqs"),
    "Hospital - B1 Save Office: Key Drawer":                           PELocationData(6250107, "Hospital: NoReqs"),
    "Hospital - B1 Morgue: Chest":                                     PELocationData(6250108, "Hospital: NoReqs"),
    "Hospital - B1 Autopsy: Lower Chest":                              PELocationData(6250109, "Hospital: Combat+AK"),
    "Hospital - B1 Autopsy: Upper Chest":                              PELocationData(6250110, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Corner Chest":                           PELocationData(6250111, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Fuse Sparkle":                           PELocationData(6250112, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Cardkey Corpse":                         PELocationData(6250113, "Hospital: Combat+AK"),
    "Hospital - B1 Blue Hallway: 50/50 Chest":                         PELocationData(6250114, "Hospital: Combat+BC"),
    "Hospital - B1 Collapsed Back Stairway: Sparkle":                  PELocationData(6250115, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Right Chest":                   PELocationData(6250116, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Left Chest":                    PELocationData(6250117, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Fuse Sparkle":                  PELocationData(6250118, "Hospital: Combat+BC"),
    "Hospital - 1F Emergency Room: Chest":                             PELocationData(6250119, "Hospital: Combat"),
    "Hospital - 1F Flashback Room: Chest":                             PELocationData(6250120, "Hospital: Combat"),
    "Hospital - 1F Flashback Room: Nurse":                             PELocationData(6250121, "Hospital: Combat"),
    "Hospital - 1F Green Hallway: Chest":                              PELocationData(6250122, "Hospital: Combat+GC"),
    "Hospital - 1F Nitrogen Storage: Chest":                           PELocationData(6250123, "Hospital: Combat+GC"),
    "Hospital - 1F Nitrogen Storage: King Bacterium Drop":             PELocationData(6250124, "Hospital: Combat+GC"),
    "Hospital - 13F Research Lab: Chest":                              PELocationData(6250125, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Research Lab: Counter":                            PELocationData(6250126, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Research Lab: Shelf":                              PELocationData(6250127, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Kennel: Chest":                                    PELocationData(6250128, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: Lower Chest":                PELocationData(6250129, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: Upper Chest":                PELocationData(6250130, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: 1st Sparkle (Junk)":         PELocationData(6250131, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: 2nd Sparkle (Key)":          PELocationData(6250132, "Hospital: Combat+BC+Fuses"),
    "Hospital - Roof Spiderwoman: Boss Drop":                          PELocationData(6250133, "Hospital: Combat+BC+Fuses+EK+Boss"),
    "Chinatown - Near Entrance: Left Chest":                           PELocationData(6250134, "Chinatown: NoReqs|Combat+GK"),
    "Chinatown - Near Entrance: Right Chest":                          PELocationData(6250135, "Chinatown: NoReqs|Combat+GK"),
    "Chinatown - Antique Shop Exterior (Save): Lower Chest":           PELocationData(6250136, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Exterior (Save): Upper Chest":           PELocationData(6250137, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Interior: Chest":                        PELocationData(6250138, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Interior: Shelf":                        PELocationData(6250139, "Chinatown: Combat|Combat+GK"),
    "Chinatown - End of the Street: Chest":                            PELocationData(6250140, "Chinatown: Combat|Combat+GK"),
    "Chinatown - End of the Street: Maeda's Narita":                   PELocationData(6250141, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth A-04: Super Tool Sparkle":           PELocationData(6250142, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-01: Medicine 4 Chest":             PELocationData(6250143, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-03: Cure-D Sparkle":               PELocationData(6250144, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-06: Ammo Chest":                   PELocationData(6250145, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth C-02: Cr Protector Chest":           PELocationData(6250146, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth C-06: Range Sparkle":                PELocationData(6250147, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-03: M203-3 Chest":                 PELocationData(6250148, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-08: M870 Chest":                   PELocationData(6250149, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-11: Off or Def Chest":             PELocationData(6250150, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth E-04: Medicine 3 Chest":             PELocationData(6250151, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth E-10: Tool Sparkle":                 PELocationData(6250152, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth F-09: Offense Chest":                PELocationData(6250153, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Exit Catwalk: Club 3 Chest":                   PELocationData(6250154, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Pump Station Exterior: Alligator Chest":              PELocationData(6250155, "Chinatown: Combat+Boss|Combat+GK+Boss"),
    "Chinatown - Pump Station Exterior: Catwalk Chest":                PELocationData(6250156, "Chinatown: Combat|GK"),
    "Chinatown - Pump Station Control Room: Chest":                    PELocationData(6250157, "Chinatown: Combat|GK"),
    "Subway - Platform (Save): Bench Chest":                           PELocationData(6250158, "Subway: Combat+PK|GK"),
    "Subway - Platform (Save): Phone Chest":                           PELocationData(6250159, "Subway: Combat+PK|GK"),
    "Subway - Exit Stairway: Chest":                                   PELocationData(6250160, "Subway: Combat+PK|GK"),
    "Subway - Left Mole Tunnel: Chest":                                PELocationData(6250161, "Subway: Combat+PK|Combat+GK"),
    "Subway - Centipede: Boss Drop":                                   PELocationData(6250162, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Right Chest":                      PELocationData(6250163, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Left Chest":                       PELocationData(6250164, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Lower Chest":                      PELocationData(6250165, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Bridge: Cop's Gate Key":                                 PELocationData(6250166, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Warehouse - Outside: Left Chest (Hidden)":                        PELocationData(6250167, "Warehouse: NoReqs"),
    "Warehouse - Outside: Right Chest":                                PELocationData(6250168, "Warehouse: NoReqs"),
    "Warehouse - Entrance: Forklift Chest":                            PELocationData(6250169, "Warehouse: NoReqs"),
    "Warehouse - Tom and Jerry: Chest":                                PELocationData(6250170, "Warehouse: Combat"),
    "Warehouse - Tom and Jerry: Key Sparkle":                          PELocationData(6250171, "Warehouse: Combat"),
    "Warehouse - Save Room: Ladder Chest":                             PELocationData(6250172, "Warehouse: Combat"),
    "Warehouse - Save Room: Upper Ground Chest":                       PELocationData(6250173, "Warehouse: Combat"),
    "Warehouse - Save Room: Lower Ground Chest":                       PELocationData(6250174, "Warehouse: Combat"),
    "Warehouse - Before Descent: Upper Left Chest":                    PELocationData(6250175, "Warehouse: Combat+WK"),
    "Warehouse - Before Descent: Upper Left Chest":                    PELocationData(6250176, "Warehouse: Combat+WK"),
    "Warehouse - Before Descent: Lower Left Chest":                    PELocationData(6250177, "Warehouse: Combat+WK"),
    "Warehouse - Giant Enemy Crab: Boss Drop":                         PELocationData(6250178, "Warehouse: Combat+WK+Boss"),
    "Warehouse - Giant Enemy Crab: Steamed Tool":                      PELocationData(6250179, "Warehouse: Combat+WK+Boss"),
    "Museum - 1F Klamp Pursuit East Exhibit: Chest":                   PELocationData(6250180, "Museum: NoReqs"),
    "Museum - 1F Klamp Pursuit West Exhibit: Chest":                   PELocationData(6250181, "Museum: NoReqs"),
    "Museum - 1F Klamp Pursuit Troodon Hall: Right Chest":             PELocationData(6250182, "Museum: Combat"),
    "Museum - 1F Klamp Pursuit Troodon Hall: Left Chest":              PELocationData(6250183, "Museum: Combat"),
    "Museum - 1F Rainforest Employee Hallway: Chest":                  PELocationData(6250184, "Museum: NoReqs"),
    "Museum - 1F Rainforest Storage Room: Lower Right Chest":          PELocationData(6250185, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Lower Center Chest":         PELocationData(6250186, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Upper Chest":                PELocationData(6250187, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Right Chest":  PELocationData(6250188, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Left Chest":   PELocationData(6250189, "Museum: Combat"),
    "Museum - 1F Tribal Staircase: Chest":                             PELocationData(6250190, "Museum: Combat"),
    "Museum - 1F Stone Head Room: Ladder Access Chest":                PELocationData(6250191, "Museum: Combat"),
    "Museum - 1F Fire Escape: Stat Chest":                             PELocationData(6250192, "Museum: Combat"),
    "Museum - 2F Gemstone Staircase: Right Chest":                     PELocationData(6250193, "Museum: Combat"),
    "Museum - 2F Gemstone Staircase: Left Chest":                      PELocationData(6250194, "Museum: Combat"),
    "Museum - 3F Fire Escape: Rocket Chest":                           PELocationData(6250195, "Museum: Combat"),
    "Museum - 2F Festive Lobby: Revive Chest":                         PELocationData(6250196, "Museum: Combat"),
    "Museum - 3F Pterodactyl Ambush Hall: Chest":                      PELocationData(6250197, "Museum: Combat"),
    "Museum - 3F Stegosaurus Room: Chest":                             PELocationData(6250198, "Museum: Combat"),
    "Museum - 2F Museum Shop Tents: Upper Chest":                      PELocationData(6250199, "Museum: Combat"),
    "Museum - 2F Museum Shop Tents: Lower Chest":                      PELocationData(6250200, "Museum: Combat"),
    "Museum - 2F Security Office: Chest":                              PELocationData(6250201, "Museum: Combat"),
    "Museum - 4F Security Storage: Lower Right Chest":                 PELocationData(6250202, "Museum: Combat"),
    "Museum - 4F Security Storage: Lower Left Chest":                  PELocationData(6250203, "Museum: Combat"),
    "Museum - 4F Security Storage: Upper Left Chest":                  PELocationData(6250204, "Museum: Combat"),
    "Museum - 4F Security Storage: Center Chest":                      PELocationData(6250205, "Museum: Combat"),
    "Museum - 2F Klamp's Office: Maeda's Gun":                         PELocationData(6250206, "Museum: Combat"),
    "Museum - 2F Klamp's Office: Klamp's Key":                         PELocationData(6250207, "Museum: Combat"),
    "Museum - 4F Forgotten Landing: Full Recover Chest":               PELocationData(6250208, "Museum: Combat"),
    "Museum - 2F Broken Display: Left Chest":                          PELocationData(6250209, "Museum: Combat+KK"),
    "Museum - 2F Broken Display: Right Chest":                         PELocationData(6250210, "Museum: Combat+KK"),
    "Museum - 3F Triceratops: Boss Drop":                              PELocationData(6250211, "Museum: Combat+KK+Boss"),
    "Museum - 1F T-Rex: Left Chest":                                   PELocationData(6250212, "Museum: NoReqs"),
    "Museum - 1F T-Rex: Right Chest":                                  PELocationData(6250213, "Museum: NoReqs"),
    "Museum - 1F T-Rex: Boss Drop":                                    PELocationData(6250214, "Museum: Combat+KK+Boss"),
    "Museum - 3F Final Approach: Right Chest Behind Glass":            PELocationData(6250215, "Museum: Combat+KK+Boss"),
    "Museum - 3F Final Approach: Left Chest Behind Glass":             PELocationData(6250216, "Museum: Combat+KK+Boss"),
    "Cruiser - Deck: Daniel's Sacrifice":                              PELocationData(6250217, "Cruiser"),

    "Chrysler BLDG. - Treasurebox Set 1-01: Offense":                  PELocationData(6250218, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: Cr Evade":                 PELocationData(6250219, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: Tool":                     PELocationData(6250220, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: USP-2":                    PELocationData(6250221, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Tool A":                   PELocationData(6250222, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: M1911A4":                  PELocationData(6250223, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Tool B":                   PELocationData(6250224, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Sp Vest 2":                PELocationData(6250225, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: M16A2":                    PELocationData(6250226, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: Tool":                     PELocationData(6250227, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: Cr Evade":                 PELocationData(6250228, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: PE":                       PELocationData(6250229, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: Kv Jacket":                PELocationData(6250230, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: M79-4":                    PELocationData(6250231, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: P38 T Card":               PELocationData(6250232, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: P228":                     PELocationData(6250233, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: PE":                       PELocationData(6250234, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: Cr Evade":                 PELocationData(6250235, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-06: Sv Jacket":                PELocationData(6250236, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-06: Cr Evade":                 PELocationData(6250237, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: PE":                       PELocationData(6250238, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: P226":                     PELocationData(6250239, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: Defense":                  PELocationData(6250240, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Range":                    PELocationData(6250241, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Bullet Cap":               PELocationData(6250242, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Rocket":                   PELocationData(6250243, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Tool":                     PELocationData(6250244, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Bullet Cap":               PELocationData(6250245, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Offense A":                PELocationData(6250246, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Offense B":                PELocationData(6250247, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - 10F Spiderwoman EX: Boss Drop":                  PELocationData(6250248, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 2-01: Cr Jacket":                PELocationData(6250249, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-01: Defense":                  PELocationData(6250250, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-02: Tool":                     PELocationData(6250251, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: Tool A":                   PELocationData(6250252, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: Tool B":                   PELocationData(6250253, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: M203-5":                   PELocationData(6250254, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: Tool":                     PELocationData(6250255, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: M96":                      PELocationData(6250256, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: Bullet Cap":               PELocationData(6250257, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Kasul T Card":             PELocationData(6250258, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Offense":                  PELocationData(6250259, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Rocket":                   PELocationData(6250260, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Super Tool":               PELocationData(6250261, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Club 4":                   PELocationData(6250262, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Defense":                  PELocationData(6250263, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-07: AM44":                     PELocationData(6250264, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-07: P229":                     PELocationData(6250265, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-08: PE":                       PELocationData(6250266, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-08: Sp Suit 1":                PELocationData(6250267, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Full UZ":                  PELocationData(6250268, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Range":                    PELocationData(6250269, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Bhawk T Card":             PELocationData(6250270, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-10: Kv Suit 1":                PELocationData(6250271, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-10: Tool":                     PELocationData(6250272, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - 20F Alligators EX: Boss Drops":                  PELocationData(6250273, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 3-01: Tool":                     PELocationData(6250274, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: Tool A":                   PELocationData(6250275, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: PPKS T Card":              PELocationData(6250276, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: Tool B":                   PELocationData(6250277, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Bullet Cap":               PELocationData(6250278, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Tool":                     PELocationData(6250279, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Super Tool":               PELocationData(6250280, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Super Tool":               PELocationData(6250281, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Cr Evade":                 PELocationData(6250282, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Mark 23":                  PELocationData(6250283, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: Offense":                  PELocationData(6250284, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: Tool":                     PELocationData(6250285, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: M870-2":                   PELocationData(6250286, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-06: Type64":                   PELocationData(6250287, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-06: Defense":                  PELocationData(6250288, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-07: Cm Jacket":                PELocationData(6250289, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: B Jacket 2":               PELocationData(6250290, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: M1 T Card":                PELocationData(6250291, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: Offense":                  PELocationData(6250292, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-09: Range":                    PELocationData(6250293, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-09: Cr Evade":                 PELocationData(6250294, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: Tool":                     PELocationData(6250295, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: Sv Suit 1":                PELocationData(6250296, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: M79-5":                    PELocationData(6250297, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - 30F Centipede EX: Boss Drop":                    PELocationData(6250298, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 4-01: PSG-1":                    PELocationData(6250299, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Tool":                     PELocationData(6250300, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Full Cure":                PELocationData(6250301, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Bullet Cap":               PELocationData(6250302, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Cm Suit 1":                PELocationData(6250303, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Tool":                     PELocationData(6250304, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Full Recover":             PELocationData(6250305, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Tool":                     PELocationData(6250306, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Rocket":                   PELocationData(6250307, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Defense":                  PELocationData(6250308, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Sv Suit 2":                PELocationData(6250309, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: MP5A5":                    PELocationData(6250310, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: MK5 T Card":               PELocationData(6250311, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: Sp Armor 1":               PELocationData(6250312, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: BAR T Card":               PELocationData(6250313, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-05: Tool":                     PELocationData(6250314, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-06: MP44 T Card":              PELocationData(6250315, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: MG42 T Card":              PELocationData(6250316, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: Cr Evade":                 PELocationData(6250317, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: M1911A5":                  PELocationData(6250318, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: Defense":                  PELocationData(6250319, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-08: Maverick":                 PELocationData(6250320, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-08: Range":                    PELocationData(6250321, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-09: Kv Armor 1":               PELocationData(6250322, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-10: Tool":                     PELocationData(6250323, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - 40F Triceratops EX: Boss Drop":                  PELocationData(6250324, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 5-01: SAR":                      PELocationData(6250325, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-01: Tool":                     PELocationData(6250326, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-01: M29 T Card":               PELocationData(6250327, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: M73 T Card":               PELocationData(6250328, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: PE":                       PELocationData(6250329, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: Super Tool":               PELocationData(6250330, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: AT4-1":                    PELocationData(6250331, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-03: Tool":                     PELocationData(6250332, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-03: Bullet Cap":               PELocationData(6250333, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-04: Cr Suit 1":                PELocationData(6250334, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-05: USP-3":                    PELocationData(6250335, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Offense":                  PELocationData(6250336, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Rocket":                   PELocationData(6250337, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Cm Armor 1":               PELocationData(6250338, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Tool":                     PELocationData(6250339, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Range":                    PELocationData(6250340, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-07: Tool":                     PELocationData(6250341, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-08: B Suit 1":                 PELocationData(6250342, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: G20":                      PELocationData(6250343, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Tool":                     PELocationData(6250344, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Offense":                  PELocationData(6250345, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Sv Armor 1":               PELocationData(6250346, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - 50F Cockroach: Boss Drop":                       PELocationData(6250347, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Type38 T Card":            PELocationData(6250348, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Cr Evade":                 PELocationData(6250349, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Sp Armor 2":               PELocationData(6250350, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-02: Rocket":                   PELocationData(6250351, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-02: MP5SD6":                   PELocationData(6250352, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-03: B Suit 2":                 PELocationData(6250353, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-04: M712":                     PELocationData(6250354, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: S12":                      PELocationData(6250355, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: PE":                       PELocationData(6250356, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: Full Recover":             PELocationData(6250357, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: Cr Armor 1":               PELocationData(6250358, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-06: Full Cure":                PELocationData(6250359, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-07: FA-MAS":                   PELocationData(6250360, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-08: Range":                    PELocationData(6250361, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool A":                   PELocationData(6250362, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool B":                   PELocationData(6250363, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool C":                   PELocationData(6250364, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - 60F Giant Enemy Crab EX: Boss Drop":             PELocationData(6250365, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 7-01: PE":                       PELocationData(6250366, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: M500-2":                   PELocationData(6250367, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: Full Recover":             PELocationData(6250368, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: M500":                     PELocationData(6250369, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-02: Defense":                  PELocationData(6250370, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: XM177E2":                  PELocationData(6250371, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Tool":                     PELocationData(6250372, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Range":                    PELocationData(6250373, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Full Cure":                PELocationData(6250374, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Super Tool":               PELocationData(6250375, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Cm Armor 2":               PELocationData(6250376, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Bullet Cap":               PELocationData(6250377, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: B Armor":                  PELocationData(6250378, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: M96R":                     PELocationData(6250379, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: Super Tool":               PELocationData(6250380, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: Tool":                     PELocationData(6250381, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-06: Type3 T Card":             PELocationData(6250382, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: M203-6":                   PELocationData(6250383, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: Offense":                  PELocationData(6250384, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: Sv Armor 2":               PELocationData(6250385, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Eagle T Card":             PELocationData(6250386, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: PE":                       PELocationData(6250387, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Club 5":                   PELocationData(6250388, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Cr Armor 2":               PELocationData(6250389, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - 70F Queen Bee: Boss Drop":                       PELocationData(6250390, "Chrysler BLDG.: Key 7"),
}

location_table = {name: data.address for name, data in location_data_table.items() if data.address is not None}