from typing import NamedTuple, Dict
from BaseClasses import Item, ItemClassification


class PEItem(Item):
    game = "Parasite Eve"

class PEItemData(NamedTuple):
    code: int
    category: str
    classification: any


item_data_table: Dict[str, PEItemData] = {
    
    "Ammo +6":          PEItemData(624001, "AutoDist",    ItemClassification.filler),
    "Ammo +15":         PEItemData(624002, "AutoDist",    ItemClassification.useful),
    "Ammo +30":         PEItemData(624003, "AutoDist",    ItemClassification.useful),
    "DNA Bullets":      PEItemData(624004, "AutoDist",    ItemClassification.useful),
    "Rocket":           PEItemData(624005, "AutoDist",    ItemClassification.useful),
    "Medicine 1":       PEItemData(624006, "Consumable",  ItemClassification.filler),
    "Medicine 2":       PEItemData(624007, "Consumable",  ItemClassification.useful),
    "Medicine 3":       PEItemData(624008, "Consumable",  ItemClassification.useful),
    "Medicine 4":       PEItemData(624009, "Consumable",  ItemClassification.useful),
    "Full Recovery":    PEItemData(624010, "Consumable",  ItemClassification.useful),
    "Super Junk":       PEItemData(624011, "KeyItem",     ItemClassification.progression),
    "Duper Junk":       PEItemData(624012, "Junk",        ItemClassification.filler),
    "Cure-P":           PEItemData(624013, "Consumable",  ItemClassification.useful),
    "Cure-D":           PEItemData(624014, "Consumable",  ItemClassification.useful),
    "Cure-C":           PEItemData(624015, "Consumable",  ItemClassification.filler),
    "Cure-M":           PEItemData(624016, "Consumable",  ItemClassification.useful),
    "FullCure":         PEItemData(624017, "Consumable",  ItemClassification.useful),
    "Revive":           PEItemData(624018, "Consumable",  ItemClassification.useful),
    #Defense +1":       PEItemData(624019, "Unused duplicate Defense 1, unable to be used."),
    "Junk":             PEItemData(624020, "Junk",        ItemClassification.filler),
    "Trading Card":     PEItemData(624021, "CommonTCard", ItemClassification.filler),
    "Tool":             PEItemData(624022, "ToolType",    ItemClassification.useful),
    "Super Tool":       PEItemData(624023, "ToolType",    ItemClassification.useful),
    #Item24":           PEItemData(624024, "Unused item. Consumable, but has no effect."),
    #Item25":           PEItemData(624025, "Unused item. Consumable, but has no effect."),
    #Ammo Crate":       PEItemData(624026, "Crate is automatically given upon receiving its ammo."),
    #Rocket Crate":     PEItemData(624027, "Crate is automatically given upon receiving its ammo."),
    #Maeda Crate":      PEItemData(624028, "Crate is automatically given upon receiving its ammo."),
    "Offense +1":       PEItemData(624029, "Consumable",  ItemClassification.filler),
    "Offense +2":       PEItemData(624030, "Consumable",  ItemClassification.useful),
    "Offense +3":       PEItemData(624031, "Consumable",  ItemClassification.useful),
    "Offense +4":       PEItemData(624032, "Consumable",  ItemClassification.useful),
    "Range +1":         PEItemData(624033, "Consumable",  ItemClassification.filler),
    "Range +2":         PEItemData(624034, "Consumable",  ItemClassification.useful),
    "Range +3":         PEItemData(624035, "Consumable",  ItemClassification.useful),
    "Range +4":         PEItemData(624036, "Consumable",  ItemClassification.useful),
    "Bullet Cap +1":    PEItemData(624037, "Consumable",  ItemClassification.filler),
    "Bullet Cap +2":    PEItemData(624038, "Consumable",  ItemClassification.useful),
    "Bullet Cap +3":    PEItemData(624039, "Consumable",  ItemClassification.useful),
    "Bullet Cap +4":    PEItemData(624040, "Consumable",  ItemClassification.useful),
    "Defense +1":       PEItemData(624041, "Consumable",  ItemClassification.filler),
    "Defense +2":       PEItemData(624042, "Consumable",  ItemClassification.useful),
    "Defense +3":       PEItemData(624043, "Consumable",  ItemClassification.useful),
    "Defense +4":       PEItemData(624044, "Consumable",  ItemClassification.useful),
    "Cr Evade +1":      PEItemData(624045, "Consumable",  ItemClassification.filler),
    "Cr Evade +2":      PEItemData(624046, "Consumable",  ItemClassification.useful),
    "Cr Evade +3":      PEItemData(624047, "Consumable",  ItemClassification.useful),
    "Cr Evade +4":      PEItemData(624048, "Consumable",  ItemClassification.useful),
    "PE +1":            PEItemData(624049, "Consumable",  ItemClassification.filler),
    "PE +2":            PEItemData(624050, "Consumable",  ItemClassification.useful),
    "PE +3":            PEItemData(624051, "Consumable",  ItemClassification.useful),
    "PE +4":            PEItemData(624052, "Consumable",  ItemClassification.useful),
    "Tool Kit":         PEItemData(624053, "ToolType",    ItemClassification.useful),
    "Super Tool Kit":   PEItemData(624054, "ToolType",    ItemClassification.useful),
    "ModPermit":        PEItemData(624055, "CommonTCard", ItemClassification.useful),
    #Chrysler Key 1":   PEItemData(624056, "Chrysler Building not yet implemented."),
    #Chrysler Key 2":   PEItemData(624057, "Chrysler Building not yet implemented."),
    #Chrysler Key 3":   PEItemData(624058, "Chrysler Building not yet implemented."),
    #Chrysler Key 4":   PEItemData(624059, "Chrysler Building not yet implemented."),
    #Chrysler Key 5":   PEItemData(624060, "Chrysler Building not yet implemented."),
    #Chrysler Key 6":   PEItemData(624061, "Chrysler Building not yet implemented."),
    #Chrysler Key 7":   PEItemData(624062, "Chrysler Building not yet implemented."),

    "Club 1":           PEItemData(624063, "Weapon",      ItemClassification.useful),
    "Club 2":           PEItemData(624064, "Weapon",      ItemClassification.useful),
    "Club 3":           PEItemData(624065, "Weapon",      ItemClassification.useful),
    "Club 4":           PEItemData(624066, "Weapon",      ItemClassification.progression),
    "Club 5":           PEItemData(624067, "Weapon",      ItemClassification.progression),
    "M84F":             PEItemData(624068, "Weapon",      ItemClassification.useful),
    "M9":               PEItemData(624069, "Weapon",      ItemClassification.useful),
    "M9-2":             PEItemData(624070, "Weapon",      ItemClassification.useful),
    "M9-3":             PEItemData(624071, "Weapon",      ItemClassification.progression),
    "M8000":            PEItemData(624072, "Weapon",      ItemClassification.progression),
    "M96":              PEItemData(624073, "Weapon",      ItemClassification.useful),
    "M96R":             PEItemData(624074, "Weapon",      ItemClassification.progression),
    "P220":             PEItemData(624075, "Weapon",      ItemClassification.useful),
    "P220-2":           PEItemData(624076, "Weapon",      ItemClassification.useful),
    "P228":             PEItemData(624077, "Weapon",      ItemClassification.useful),
    "P226":             PEItemData(624078, "Weapon",      ItemClassification.useful),
    "P229":             PEItemData(624079, "Weapon",      ItemClassification.useful),
    "M1911A1":          PEItemData(624080, "Weapon",      ItemClassification.useful),
    "M1911A2":          PEItemData(624081, "Weapon",      ItemClassification.useful),
    "M1911A3":          PEItemData(624082, "Weapon",      ItemClassification.useful),
    "M1911A4":          PEItemData(624083, "Weapon",      ItemClassification.useful),
    "M1911A5":          PEItemData(624084, "Weapon",      ItemClassification.useful),
    "P8":               PEItemData(624085, "Weapon",      ItemClassification.useful),
    "USP":              PEItemData(624086, "Weapon",      ItemClassification.useful),
    "USP-2":            PEItemData(624087, "Weapon",      ItemClassification.useful),
    "USP-3":            PEItemData(624088, "Weapon",      ItemClassification.useful),
    "Mark 23":          PEItemData(624089, "Weapon",      ItemClassification.useful),
    "G19":              PEItemData(624090, "Weapon",      ItemClassification.useful),
    "G23":              PEItemData(624091, "Weapon",      ItemClassification.useful),
    "G22":              PEItemData(624092, "Weapon",      ItemClassification.useful),
    "G20":              PEItemData(624093, "Weapon",      ItemClassification.useful),
    "M712":             PEItemData(624094, "Weapon",      ItemClassification.useful),
    "PPK":              PEItemData(624095, "Weapon",      ItemClassification.progression),
    "AM44":             PEItemData(624096, "Weapon",      ItemClassification.useful),
    "Maeda's Gun":      PEItemData(624097, "Weapon",      ItemClassification.useful),
    "PPSh41":           PEItemData(624098, "Weapon",      ItemClassification.useful),
    "SP1C":             PEItemData(624099, "Weapon",      ItemClassification.useful),
    "USP-TU":           PEItemData(624100, "Weapon",      ItemClassification.useful),
    "AK-47":            PEItemData(624101, "Weapon",      ItemClassification.useful),
    "DE50AE7":          PEItemData(624102, "Weapon",      ItemClassification.useful),
    #Debug SMG":        PEItemData(624103, "Completely busted plus stats, not using."),
    "M870":             PEItemData(624104, "Weapon",      ItemClassification.useful),
    "M870-2":           PEItemData(624105, "Weapon",      ItemClassification.useful),
    "M500":             PEItemData(624106, "Weapon",      ItemClassification.useful),
    "M500-2":           PEItemData(624107, "Weapon",      ItemClassification.useful),
    "Maverick":         PEItemData(624108, "Weapon",      ItemClassification.progression),
    "S12":              PEItemData(624109, "Weapon",      ItemClassification.useful),
    "M10B":             PEItemData(624110, "Weapon",      ItemClassification.useful),
    "M11":              PEItemData(624111, "Weapon",      ItemClassification.useful),
    "M10":              PEItemData(624112, "Weapon",      ItemClassification.useful),
    "MP5K":             PEItemData(624113, "Weapon",      ItemClassification.useful),
    "MP5PDW":           PEItemData(624114, "Weapon",      ItemClassification.useful),
    "MP5A5":            PEItemData(624115, "Weapon",      ItemClassification.progression),
    "MP5SD6":           PEItemData(624116, "Weapon",      ItemClassification.useful),
    "Micro UZ":         PEItemData(624117, "Weapon",      ItemClassification.useful),
    "Mini UZ":          PEItemData(624118, "Weapon",      ItemClassification.useful),
    "Full UZ":          PEItemData(624119, "Weapon",      ItemClassification.useful),
    "P90":              PEItemData(624120, "Weapon",      ItemClassification.useful),
    "M16A1":            PEItemData(624121, "Weapon",      ItemClassification.useful),
    "M16A2":            PEItemData(624122, "Weapon",      ItemClassification.useful),
    "SG550":            PEItemData(624123, "Weapon",      ItemClassification.useful),
    "SAR":              PEItemData(624124, "Weapon",      ItemClassification.useful),
    "G3A3":             PEItemData(624125, "Weapon",      ItemClassification.useful),
    "Type64":           PEItemData(624126, "Weapon",      ItemClassification.progression),
    "XM177E2":          PEItemData(624127, "Weapon",      ItemClassification.useful),
    "PSG-1":            PEItemData(624128, "Weapon",      ItemClassification.useful),
    "FA-MAS":           PEItemData(624129, "Weapon",      ItemClassification.useful),
    "MAG":              PEItemData(624130, "Weapon",      ItemClassification.useful),
    "M203":             PEItemData(624131, "Weapon",      ItemClassification.useful),
    "M203-2":           PEItemData(624132, "Weapon",      ItemClassification.useful),
    "M203-3":           PEItemData(624133, "Weapon",      ItemClassification.progression),
    "M203-4":           PEItemData(624134, "Weapon",      ItemClassification.useful),
    "M203-5":           PEItemData(624135, "Weapon",      ItemClassification.useful),
    "M203-6":           PEItemData(624136, "Weapon",      ItemClassification.useful),
    "M79":              PEItemData(624137, "Weapon",      ItemClassification.progression),
    "M79-2":            PEItemData(624138, "Weapon",      ItemClassification.useful),
    "M79-3":            PEItemData(624139, "Weapon",      ItemClassification.useful),
    "M79-4":            PEItemData(624140, "Weapon",      ItemClassification.useful),
    "M79-5":            PEItemData(624141, "Weapon",      ItemClassification.useful),
    "M79-6":            PEItemData(624142, "Weapon",      ItemClassification.useful),
    "HK40":             PEItemData(624143, "Weapon",      ItemClassification.useful),
    "AT4":              PEItemData(624144, "Weapon",      ItemClassification.useful),
    "AT4-1":            PEItemData(624145, "Weapon",      ItemClassification.useful),
    "LAW80":            PEItemData(624146, "Weapon",      ItemClassification.progression),
    #Maeda's Gun WB":   PEItemData(624147, "Loaded variant for final fight, excluded."),
    "M92F":             PEItemData(624148, "Weapon",      ItemClassification.useful),
    "Dress":            PEItemData(624149, "Armor",       ItemClassification.useful),
    "N Vest":           PEItemData(624150, "Armor",       ItemClassification.useful),
    "N Protector":      PEItemData(624151, "Armor",       ItemClassification.useful),
    "N Jacket":         PEItemData(624152, "Armor",       ItemClassification.useful),
    "N Suit":           PEItemData(624153, "Armor",       ItemClassification.useful),
    "N Armor":          PEItemData(624154, "Armor",       ItemClassification.useful),
    "Kv Vest 1":        PEItemData(624155, "Armor",       ItemClassification.useful),
    "Kv Protector":     PEItemData(624156, "Armor",       ItemClassification.useful),
    "Kv Jacket":        PEItemData(624157, "Armor",       ItemClassification.useful),
    "Kv Suit 1":        PEItemData(624158, "Armor",       ItemClassification.useful),
    "Kv Armor 1":       PEItemData(624159, "Armor",       ItemClassification.useful),
    "Sp Vest 1":        PEItemData(624160, "Armor",       ItemClassification.useful),
    "Sp Vest 2":        PEItemData(624161, "Armor",       ItemClassification.useful),
    "Sp Protector":     PEItemData(624162, "Armor",       ItemClassification.useful),
    "Sp Jacket":        PEItemData(624163, "Armor",       ItemClassification.useful),
    "Sp Suit 1":        PEItemData(624164, "Armor",       ItemClassification.useful),
    "Sp Suit 2":        PEItemData(624165, "Armor",       ItemClassification.useful),
    "Sp Armor 1":       PEItemData(624166, "Armor",       ItemClassification.useful),
    "Sp Armor 2":       PEItemData(624167, "Armor",       ItemClassification.progression),
    "Sv Vest 1":        PEItemData(624168, "Armor",       ItemClassification.useful),
    "Sv Vest 2":        PEItemData(624169, "Armor",       ItemClassification.useful),
    "Sv Protector":     PEItemData(624170, "Armor",       ItemClassification.useful),
    "Sv Jacket":        PEItemData(624171, "Armor",       ItemClassification.useful),
    "Sv Suit 1":        PEItemData(624172, "Armor",       ItemClassification.useful),
    "Sv Suit 2":        PEItemData(624173, "Armor",       ItemClassification.useful),
    "Sv Armor 1":       PEItemData(624174, "Armor",       ItemClassification.progression),
    "Sv Armor 2":       PEItemData(624175, "Armor",       ItemClassification.useful),
    "Cr Vest 1":        PEItemData(624176, "Armor",       ItemClassification.useful),
    "Cr Vest 2":        PEItemData(624177, "Armor",       ItemClassification.useful),
    "Cr Protector":     PEItemData(624178, "Armor",       ItemClassification.progression),
    "Cr Jacket":        PEItemData(624179, "Armor",       ItemClassification.useful),
    "Cr Suit 1":        PEItemData(624180, "Armor",       ItemClassification.useful),
    "Cr Suit 2":        PEItemData(624181, "Armor",       ItemClassification.useful),
    "Cr Armor 1":       PEItemData(624182, "Armor",       ItemClassification.useful),
    "Cr Armor 2":       PEItemData(624183, "Armor",       ItemClassification.useful),
    "B Vest 1":         PEItemData(624184, "Armor",       ItemClassification.progression),
    "B Vest 2":         PEItemData(624185, "Armor",       ItemClassification.useful),
    "B Protector":      PEItemData(624186, "Armor",       ItemClassification.progression),
    "B Jacket 1":       PEItemData(624187, "Armor",       ItemClassification.useful),
    "B Jacket 2":       PEItemData(624188, "Armor",       ItemClassification.progression),
    "B Suit 1":         PEItemData(624189, "Armor",       ItemClassification.useful),
    "B Suit 2":         PEItemData(624190, "Armor",       ItemClassification.progression),
    "B Armor":          PEItemData(624191, "Armor",       ItemClassification.useful),
    "Cm Vest 1":        PEItemData(624192, "Armor",       ItemClassification.progression),
    "Cm Vest 2":        PEItemData(624193, "Armor",       ItemClassification.useful),
    "Cm Protector":     PEItemData(624194, "Armor",       ItemClassification.useful),
    "Cm Jacket":        PEItemData(624195, "Armor",       ItemClassification.useful),
    "Cm Suit 1":        PEItemData(624196, "Armor",       ItemClassification.progression),
    "Cm Armor 1":       PEItemData(624197, "Armor",       ItemClassification.useful),
    "Cm Armor 2":       PEItemData(624198, "Armor",       ItemClassification.progression),
    #Cm Suit 2":        PEItemData(624199, "Armor-equivalent of Debug SMG, excluded."),

    "Theater Key":      PEItemData(624200, "KeyItem",     ItemClassification.progression),
    "Rehearse Key":     PEItemData(624201, "KeyItem",     ItemClassification.progression),
    "Zoo Key":          PEItemData(624202, "KeyItem",     ItemClassification.progression),
    "Narita":           PEItemData(624203, "KeyItem",     ItemClassification.progression),
    "Mayoke":           PEItemData(624204, "KeyItem",     ItemClassification.progression),
    "Hamaya":           PEItemData(624205, "KeyItem",     ItemClassification.progression),
    "Fuse 1":           PEItemData(624206, "KeyItem",     ItemClassification.progression),
    "Fuse 2":           PEItemData(624207, "KeyItem",     ItemClassification.progression),
    "Fuse 3":           PEItemData(624208, "KeyItem",     ItemClassification.progression),
    "Autopsy Key":      PEItemData(624209, "KeyItem",     ItemClassification.progression),
    "Blue Cardkey":     PEItemData(624210, "KeyItem",     ItemClassification.progression),
    "Green Cardkey":    PEItemData(624211, "KeyItem",     ItemClassification.progression),
    "Pump Key":         PEItemData(624212, "KeyItem",     ItemClassification.progression),
    "Klamp Key":        PEItemData(624213, "KeyItem",     ItemClassification.progression),
    "Storage Key":      PEItemData(624214, "KeyItem",     ItemClassification.progression),
    "Locker Key":       PEItemData(624215, "KeyItem",     ItemClassification.progression),
    "Weapon Memo":      PEItemData(624216, "KeyItem",     ItemClassification.progression),
    #Medal":            PEItemData(624217, "Currently unused for the rando."),
    "Elevator Key":     PEItemData(624218, "KeyItem",     ItemClassification.progression),
    "Gate Key":         PEItemData(624219, "KeyItem",     ItemClassification.progression),
    "Warehouse Key":    PEItemData(624220, "KeyItem",     ItemClassification.progression),
    "GSP T Card":       PEItemData(624221, "KeyItem",     ItemClassification.progression),
    "P38 T Card":       PEItemData(624222, "KeyItem",     ItemClassification.progression),
    "Bhawk T Card":     PEItemData(624223, "KeyItem",     ItemClassification.progression),
    "Kasul T Card":     PEItemData(624224, "KeyItem",     ItemClassification.progression),
    "PPKS T Card":      PEItemData(624225, "KeyItem",     ItemClassification.progression),
    "M1 T Card":        PEItemData(624226, "KeyItem",     ItemClassification.progression),
    "MK5 T Card":       PEItemData(624227, "KeyItem",     ItemClassification.progression),
    "MP44 T Card":      PEItemData(624228, "KeyItem",     ItemClassification.progression),
    "BAR T Card":       PEItemData(624229, "KeyItem",     ItemClassification.progression),
    "MG42 T Card":      PEItemData(624230, "KeyItem",     ItemClassification.progression),
    "M29 T Card":       PEItemData(624231, "KeyItem",     ItemClassification.progression),
    "M73 T Card":       PEItemData(624232, "KeyItem",     ItemClassification.progression),
    "Type38 T Card":    PEItemData(624233, "KeyItem",     ItemClassification.progression),
    "Type3 T Card":     PEItemData(624234, "KeyItem",     ItemClassification.progression),
    "Eagle T Card":     PEItemData(624235, "KeyItem",     ItemClassification.progression),

    "Heal 1":           PEItemData(624236, "PEnergy",     ItemClassification.progression),
    "Heal 2":           PEItemData(624237, "PEnergy",     ItemClassification.progression),
    "Heal 3":           PEItemData(624238, "PEnergy",     ItemClassification.progression),
    "Detox":            PEItemData(624239, "PEnergy",     ItemClassification.progression),
    "Medic":            PEItemData(624240, "PEnergy",     ItemClassification.progression),
    "Barrier":          PEItemData(624241, "PEnergy",     ItemClassification.progression),
    "Energy Shot":      PEItemData(624242, "PEnergy",     ItemClassification.progression),
    "Scan":             PEItemData(624243, "PEnergy",     ItemClassification.useful),
    "Slow":             PEItemData(624244, "PEnergy",     ItemClassification.useful),
    "Haste":            PEItemData(624245, "PEnergy",     ItemClassification.progression),
    "Confuse":          PEItemData(624246, "PEnergy",     ItemClassification.useful),
    "Gene Heal":        PEItemData(624247, "PEnergy",     ItemClassification.progression),
    "Preraise":         PEItemData(624248, "PEnergy",     ItemClassification.progression),
    #mito14":           PEItemData(624249, "Unused PE, has an animation, but no cost or effect.")
    #mito15":           PEItemData(624250, "Unused PE, has an animation, but no cost or effect.")
    #mito16":           PEItemData(624251, "Unused PE, has an animation, but no cost or effect.")
    #mito17":           PEItemData(624252, "Unused PE, has an animation, but no cost or effect.")
    #mito18":           PEItemData(624253, "Unused PE, has an animation, but no cost or effect.")
    "Full Recover":     PEItemData(624254, "PEnergy",     ItemClassification.progression),
    "Liberate":         PEItemData(624255, "PEnergy",     ItemClassification.progression),

    "Carnegie Hall":    PEItemData(624256, "VisitUnlock", ItemClassification.progression),
    "N.Y.P.D. #17":     PEItemData(624257, "VisitUnlock", ItemClassification.progression),
    "Central Park":     PEItemData(624258, "VisitUnlock", ItemClassification.progression),
    "Soho":             PEItemData(624259, "VisitUnlock", ItemClassification.progression),
    "Hospital":         PEItemData(624260, "VisitUnlock", ItemClassification.progression),
    "Chinatown":        PEItemData(624261, "VisitUnlock", ItemClassification.progression),
    "Subway":           PEItemData(624262, "VisitUnlock", ItemClassification.progression),
    "Warehouse":        PEItemData(624263, "VisitUnlock", ItemClassification.progression),
    "Museum":           PEItemData(624264, "VisitUnlock", ItemClassification.progression),
    #Chrysler BLDG.":   PEItemData(624265, "Chrysler Building is currently unused."),

    "Offense Level":    PEItemData(624266, "LevelStat",   ItemClassification.progression),
    "Defense Level":    PEItemData(624267, "LevelStat",   ItemClassification.progression),
    "P.Energy Level":   PEItemData(624268, "LevelStat",   ItemClassification.progression),
    "StatusRcvr Level": PEItemData(624269, "LevelStat",   ItemClassification.progression),
    "ActiveTime Level": PEItemData(624270, "LevelStat",   ItemClassification.progression),
    "ItemCapcty Level": PEItemData(624271, "LevelStat",   ItemClassification.progression),
    "Confusion Trap":   PEItemData(624272, "Trap",        ItemClassification.trap),
    "Darkness Trap":    PEItemData(624273, "Trap",        ItemClassification.trap),
    "Silence Trap":     PEItemData(624274, "Trap",        ItemClassification.trap),
    "Impact Trap":      PEItemData(624275, "Trap",        ItemClassification.trap),
}

item_table = {name: data.code for name, data in item_data_table.items()}
