from BaseClasses import Location
import typing


class PELoctData(typing.NamedTuple):
    code: int
    region: str


item_table: Dict[str, PELoctData] = {
    "Carnegie Hall - F1 Backstage: Chest":                             PELoctData(625001, "Carnegie Hall: NoReqs"),
    "Carnegie Hall - B1 Save Room: Chest":                             PELoctData(625002, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Save Room: Theater Corpse":                    PELoctData(625003, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Diary Room: Diary Key":                        PELoctData(625004, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Diary Room: Closet":                           PELoctData(625005, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Parrot Room: Closet":                          PELoctData(625006, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Clown Locker Room: Locker":                    PELoctData(625007, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Burned Pair Locker Room: Locker":              PELoctData(625008, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Prop Room: Front Chest":                       PELoctData(625009, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Hidden Chest":                      PELoctData(625010, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Rat Cabinet":                       PELoctData(625011, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Backstage Storage: Chest":                     PELoctData(625012, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - Sewers Stairway: Chest":                          PELoctData(625013, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Left Chest":              PELoctData(625014, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Right Chest":             PELoctData(625015, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Front Left Chest":             PELoctData(625016, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Left Chest":            PELoctData(625017, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Center Chest":          PELoctData(625018, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Right Chest":           PELoctData(625019, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Valve Chest":           PELoctData(625020, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Alligator: Boss Drop":                     PELoctData(625021, "Carnegie Hall: Combat+RK+Boss"),
    "N.Y.P.D. #17 - D2 1F Baker's Office: Baker Permit 1":             PELoctData(625022, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Right Locker":                  PELoctData(625023, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Center Locker":                 PELoctData(625024, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Conference Room: Baker Permit 2":            PELoctData(625025, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 B1 Weapons Department: M16A1":                  PELoctData(625026, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D3 1F Entrance: Maeda's Hamaya":                   PELoctData(625027, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Cop's Ammo":                      PELoctData(625028, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Nix's Ammo":                      PELoctData(625029, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Save Room: Warner's Ammo":                   PELoctData(625030, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Right Locker":                  PELoctData(625031, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Cop's Ammo":                    PELoctData(625032, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Locked Locker":                 PELoctData(625033, "N.Y.P.D. #17: LK"),
    "N.Y.P.D. #17 - D3 B1 Weapons Department: Torres's Gun":           PELoctData(625034, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 B1 Kennel: Cathy's Ammo":                       PELoctData(625035, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Conference Room: Spider Chest":              PELoctData(625036, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Barred Staircase: Cop's Ammo":               PELoctData(625037, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Left Chest":                  PELoctData(625038, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Right Chest":                 PELoctData(625039, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Chest":                  PELoctData(625040, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Table Sparkle":          PELoctData(625041, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Desk Chest":                    PELoctData(625042, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Floor Chest":                   PELoctData(625043, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 3F Ambush Hall: Cop's Locker Key":              PELoctData(625044, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D4 3F Medical Office: Daniel's Ammo":              PELoctData(625045, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Chest":                        PELoctData(625046, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Boss Drop":                    PELoctData(625047, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Cop's Ammo":                   PELoctData(625048, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf's Backroom: Chest":             PELoctData(625049, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Left Chest":                PELoctData(625050, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Center Chest":              PELoctData(625051, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Right Chest":               PELoctData(625052, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D3 3F Kerberos: Boss Drop":                        PELoctData(625053, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "Central Park - Entrance: Car Chest":                              PELoctData(625054, "Central Park: NoReqs"),
    "Central Park - Entrance: Snake Chest":                            PELoctData(625055, "Central Park: NoReqs"),
    "Central Park - Front Gate: Left Chest":                           PELoctData(625056, "Central Park: Combat"),
    "Central Park - Front Gate: Right Chest":                          PELoctData(625057, "Central Park: Combat"),
    "Central Park - Courtyard: Left Gun Chest":                        PELoctData(625058, "Central Park: Combat"),
    "Central Park - Courtyard: Right Tool Chest":                      PELoctData(625059, "Central Park: Combat"),
    "Central Park - Office: Drawer Key":                               PELoctData(625060, "Central Park: Combat"),
    "Central Park - Office: Cabinet":                                  PELoctData(625061, "Central Park: Combat"),
    "Central Park - Office: Locked Cupboard":                          PELoctData(625062, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Upper Right Chest":                 PELoctData(625063, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Left Chest":                  PELoctData(625064, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Right Chest":                 PELoctData(625065, "Central Park: Combat+ZK"),
    "Central Park - Back Courtyard: Ammo Chest":                       PELoctData(625066, "Central Park: Combat"),
    "Central Park - Figure 8: Right Chest":                            PELoctData(625067, "Central Park: Combat"),
    "Central Park - Figure 8: Left Chest":                             PELoctData(625068, "Central Park: Combat"),
    "Central Park - Gazebo: Left Chest":                               PELoctData(625069, "Central Park: Combat+ZK"),
    "Central Park - Gazebo: Right Chest":                              PELoctData(625070, "Central Park: Combat+ZK"),
    "Central Park - Behind Gazebo (Save): Chest":                      PELoctData(625071, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze West: Mythical Tool Chest":            PELoctData(625072, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Bridge: Chest":                        PELoctData(625073, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Dock: Chest":                          PELoctData(625074, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze East: Backup Tool Chest":              PELoctData(625075, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Left Stat Chest":               PELoctData(625076, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Right YOLO Tool Chest":         PELoctData(625077, "Central Park: Combat+ZK"),
    "Central Park - Flaming Carriage Eve 2: Boss Drop":                PELoctData(625078, "Central Park: Combat+ZK+Boss"),
    "Soho - Apartment Interior: Chest":                                PELoctData(625054, "Soho: NoReqs),
    "Soho - Apartment Exterior: Trash Card":                           PELoctData(625054, "Soho: NoReqs),
    "Soho - Sam's Gun Shop: Northwest Chest":                          PELoctData(625054, "Soho: WM),
    "Soho - Sam's Gun Shop: Northeast Chest":                          PELoctData(625054, "Soho: WM),
    "Soho - Sam's Gun Shop: Behind Counter Chest":                     PELoctData(625054, "Soho: WM),
    "Soho - Sam's Gun Shop: Southeast Chest":                          PELoctData(625054, "Soho: WM),
    "Soho - Sam's Gun Shop: Green Box":                                PELoctData(625054, "Soho: WM),
    "Soho - Sam's Gun Shop: Red Box":                                  PELoctData(625054, "Soho: WM),
    "Soho - Sam's Gun Shop: Shotgun Rack":                             PELoctData(625054, "Soho: WM),
    "Soho - Sam's Gun Shop: Rifle Rack":                               PELoctData(625054, "Soho: WM),
    "Soho - Pharmacy: Aisle 3 Medicine Chest":                         PELoctData(625054, "Soho: NoReqs),
    "Soho - Pharmacy: Aisle 5 Revive Chest":                           PELoctData(625054, "Soho: NoReqs),
    "Soho - Pharmacy: Backroom Left Chest":                            PELoctData(625054, "Soho: NoReqs),
    "Soho - Pharmacy: Backroom Right Chest":                           PELoctData(625054, "Soho: NoReqs),
    "Soho - Pharmacy: Aisle 1 Left Shelf":                             PELoctData(625054, "Soho: NoReqs),
    "Soho - Pharmacy: Aisle 3 Far Back Shelf":                         PELoctData(625054, "Soho: NoReqs),
    "Soho - Pharmacy: Behind Phone Counter":                           PELoctData(625054, "Soho: NoReqs),
    "Soho - Pharmacy: Aisle 4 Right Shelf":                            PELoctData(625054, "Soho: NoReqs),
