from typing import NamedTuple, Dict
from BaseClasses import Location


class PELoct(Location):
    game = "Parasite Eve"

class PELoctData(NamedTuple):
    address: int
    region: str


location_data_table: Dict[str, PELoctData] = {

    "Carnegie Hall - F1 Backstage: Chest":                             PELoctData(625001, "Carnegie Hall: NoReqs"),
    "Carnegie Hall - B1 Save Room: Chest":                             PELoctData(625002, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Save Room: Theater Corpse":                    PELoctData(625003, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Diary Room: Diary Key":                        PELoctData(625004, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Diary Room: Closet":                           PELoctData(625005, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Parrot Room: Closet":                          PELoctData(625006, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Clown Locker Room: Locker":                    PELoctData(625007, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Burned Pair Locker Room: Locker":              PELoctData(625008, "Carnegie Hall: Combat"),
    "Carnegie Hall - B1 Prop Room: Front Chest":                       PELoctData(625009, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Hidden Chest":                      PELoctData(625010, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Prop Room: Rat Cabinet":                       PELoctData(625011, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - B1 Backstage Storage: Chest":                     PELoctData(625012, "Carnegie Hall: Combat+TK"),
    "Carnegie Hall - Sewers Stairway: Chest":                          PELoctData(625013, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Left Chest":              PELoctData(625014, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Back Right Chest":             PELoctData(625015, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Ghost Girl: Front Left Chest":             PELoctData(625016, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Left Chest":            PELoctData(625017, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Center Chest":          PELoctData(625018, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Right Chest":           PELoctData(625019, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Hidden Chest Room: Valve Chest":           PELoctData(625020, "Carnegie Hall: Combat+RK"),
    "Carnegie Hall - Sewers Alligator: Boss Drop":                     PELoctData(625021, "Carnegie Hall: Combat+RK+Boss"),
    "N.Y.P.D. #17 - D2 1F Baker's Office: Baker Permit 1":             PELoctData(625022, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Right Locker":                  PELoctData(625023, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Center Locker":                 PELoctData(625024, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 1F Conference Room: Baker Permit 2":            PELoctData(625025, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D2 B1 Weapons Department: M16A1":                  PELoctData(625026, "N.Y.P.D. #17: NoReqs"),
    "N.Y.P.D. #17 - D3 1F Entrance: Maeda's Hamaya":                   PELoctData(625027, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Cop's Ammo":                      PELoctData(625028, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Main Hall: Nix's Ammo":                      PELoctData(625029, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Save Room: Warner's Ammo":                   PELoctData(625030, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Right Locker":                  PELoctData(625031, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Locker Room: Cop's Ammo":                    PELoctData(625032, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D2 1F Locker Room: Locked Locker":                 PELoctData(625033, "N.Y.P.D. #17: LK"),
    "N.Y.P.D. #17 - D3 B1 Weapons Department: Torres's Gun":           PELoctData(625034, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 B1 Kennel: Cathy's Ammo":                       PELoctData(625035, "N.Y.P.D. #17: SJ"),
    "N.Y.P.D. #17 - D3 1F Conference Room: Spider Chest":              PELoctData(625036, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Barred Staircase: Cop's Ammo":               PELoctData(625037, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Left Chest":                  PELoctData(625038, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Holding Cells: Right Chest":                 PELoctData(625039, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Chest":                  PELoctData(625040, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Interrogation Room: Table Sparkle":          PELoctData(625041, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Desk Chest":                    PELoctData(625042, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 2F Save Office: Floor Chest":                   PELoctData(625043, "N.Y.P.D. #17: Combat+SJ"),
    "N.Y.P.D. #17 - D3 3F Ambush Hall: Cop's Locker Key":              PELoctData(625044, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D4 3F Medical Office: Daniel's Ammo":              PELoctData(625045, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Chest":                        PELoctData(625046, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Boss Drop":                    PELoctData(625047, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf: Cop's Ammo":                   PELoctData(625048, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D3 3F Big Bad Wolf's Backroom: Chest":             PELoctData(625049, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Left Chest":                PELoctData(625050, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Center Chest":              PELoctData(625051, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D2 B1 Weapons Storage: Right Chest":               PELoctData(625052, "N.Y.P.D. #17: SK"),
    "N.Y.P.D. #17 - D3 3F Kerberos: Boss Drop":                        PELoctData(625053, "N.Y.P.D. #17: Combat+SJ+Boss"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Tool Kit":               PELoctData(625054, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+12RTC"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Super Tool Kit":         PELoctData(625055, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+14RTC"),
    "N.Y.P.D. #17 - D4 B1 Weapons Department: Leave It to Wayne":      PELoctData(625056, "N.Y.P.D. #17: Combat+SJ+Boss+UnrChks+JunkReq"),
    "Central Park - Entrance: Car Chest":                              PELoctData(625057, "Central Park: NoReqs"),
    "Central Park - Entrance: Snake Chest":                            PELoctData(625058, "Central Park: NoReqs"),
    "Central Park - Front Gate: Left Chest":                           PELoctData(625059, "Central Park: Combat"),
    "Central Park - Front Gate: Right Chest":                          PELoctData(625060, "Central Park: Combat"),
    "Central Park - Courtyard: Left Gun Chest":                        PELoctData(625061, "Central Park: Combat"),
    "Central Park - Courtyard: Right Tool Chest":                      PELoctData(625062, "Central Park: Combat"),
    "Central Park - Office: Key Drawer":                               PELoctData(625063, "Central Park: Combat"),
    "Central Park - Office: Cabinet":                                  PELoctData(625064, "Central Park: Combat"),
    "Central Park - Office: Locked Cupboard":                          PELoctData(625065, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Upper Right Chest":                 PELoctData(625066, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Left Chest":                  PELoctData(625067, "Central Park: Combat+ZK"),
    "Central Park - Snake Exhibit: Lower Right Chest":                 PELoctData(625068, "Central Park: Combat+ZK"),
    "Central Park - Back Courtyard: Ammo Chest":                       PELoctData(625069, "Central Park: Combat"),
    "Central Park - Figure 8: Right Chest":                            PELoctData(625070, "Central Park: Combat"),
    "Central Park - Figure 8: Left Chest":                             PELoctData(625071, "Central Park: Combat"),
    "Central Park - Gazebo: Left Chest":                               PELoctData(625072, "Central Park: Combat+ZK"),
    "Central Park - Gazebo: Right Chest":                              PELoctData(625073, "Central Park: Combat+ZK"),
    "Central Park - Behind Gazebo (Save): Chest":                      PELoctData(625074, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze West: Mythical Tool Chest":            PELoctData(625075, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Bridge: Chest":                        PELoctData(625076, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze Dock: Chest":                          PELoctData(625077, "Central Park: Combat+ZK"),
    "Central Park - Forest Maze East: Backup Tool Chest":              PELoctData(625078, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Left Stat Chest":               PELoctData(625079, "Central Park: Combat+ZK"),
    "Central Park - Under Bush Bridge: Right YOLO Tool Chest":         PELoctData(625080, "Central Park: Combat+ZK"),
    "Central Park - Flaming Carriage Eve 2: Boss Drop":                PELoctData(625081, "Central Park: Combat+ZK+Boss"),
    "Soho - Apartment Interior: Chest":                                PELoctData(625082, "Soho: NoReqs"),
    "Soho - Apartment Exterior: Trash Card":                           PELoctData(625083, "Soho: NoReqs"),
    "Soho - Sam's Gun Shop: Upper Left Chest":                         PELoctData(625084, "Soho: WM"),
    "Soho - Sam's Gun Shop: Upper Right Chest":                        PELoctData(625085, "Soho: WM"),
    "Soho - Sam's Gun Shop: Behind Counter Chest":                     PELoctData(625086, "Soho: WM"),
    "Soho - Sam's Gun Shop: Lower Right Chest":                        PELoctData(625087, "Soho: WM"),
    "Soho - Sam's Gun Shop: Green Box":                                PELoctData(625088, "Soho: WM"),
    "Soho - Sam's Gun Shop: Red Box":                                  PELoctData(625089, "Soho: WM"),
    "Soho - Sam's Gun Shop: Shotgun Rack":                             PELoctData(625090, "Soho: WM"),
    "Soho - Sam's Gun Shop: Rifle Rack":                               PELoctData(625091, "Soho: WM"),
    "Soho - Pharmacy: Aisle 3 Medicine Chest":                         PELoctData(625092, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 5 Revive Chest":                           PELoctData(625093, "Soho: NoReqs"),
    "Soho - Pharmacy: Backroom Left Chest":                            PELoctData(625094, "Soho: NoReqs"),
    "Soho - Pharmacy: Backroom Right Chest":                           PELoctData(625095, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 1 Left Shelf":                             PELoctData(625096, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 3 Far Back Shelf":                         PELoctData(625097, "Soho: NoReqs"),
    "Soho - Pharmacy: Behind Phone Counter":                           PELoctData(625098, "Soho: NoReqs"),
    "Soho - Pharmacy: Aisle 4 Right Shelf":                            PELoctData(625099, "Soho: NoReqs"),
    "Hospital - 1F Outside: Maeda's Mayoke":                           PELoctData(625100, "Hospital: NoReqs"),
    "Hospital - 1F Lobby: Corner Ammo Chest":                          PELoctData(625101, "Hospital: NoReqs"),
    "Hospital - 1F Lobby: Closet Chest":                               PELoctData(625102, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Upper Chest":                              PELoctData(625103, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Lower Chest":                              PELoctData(625104, "Hospital: NoReqs"),
    "Hospital - B1 Storage: Shelf Fuse Sparkle":                       PELoctData(625105, "Hospital: NoReqs"),
    "Hospital - B1 Save Office: Chest":                                PELoctData(625106, "Hospital: NoReqs"),
    "Hospital - B1 Save Office: Key Drawer":                           PELoctData(625107, "Hospital: NoReqs"),
    "Hospital - B1 Morgue: Chest":                                     PELoctData(625108, "Hospital: NoReqs"),
    "Hospital - B1 Autopsy: Lower Chest":                              PELoctData(625109, "Hospital: Combat+AK"),
    "Hospital - B1 Autopsy: Upper Chest":                              PELoctData(625110, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Corner Chest":                           PELoctData(625111, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Fuse Sparkle":                           PELoctData(625112, "Hospital: Combat+AK"),
    "Hospital - B1 Crematory: Cardkey Corpse":                         PELoctData(625113, "Hospital: Combat+AK"),
    "Hospital - B1 Blue Hallway: 50/50 Chest":                         PELoctData(625114, "Hospital: Combat+BC"),
    "Hospital - B1 Collapsed Back Stairway: Sparkle":                  PELoctData(625115, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Right Chest":                   PELoctData(625116, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Left Chest":                    PELoctData(625117, "Hospital: Combat+BC"),
    "Hospital - B1 Sterilization Room: Fuse Sparkle":                  PELoctData(625118, "Hospital: Combat+BC"),
    "Hospital - 1F Emergency Room: Chest":                             PELoctData(625119, "Hospital: Combat"),
    "Hospital - 1F Flashback Room: Chest":                             PELoctData(625120, "Hospital: Combat"),
    "Hospital - 1F Flashback Room: Nurse":                             PELoctData(625121, "Hospital: Combat"),
    "Hospital - 1F Green Hallway: Chest":                              PELoctData(625122, "Hospital: Combat+GC"),
    "Hospital - 1F Nitrogen Storage: Chest":                           PELoctData(625123, "Hospital: Combat+GC"),
    "Hospital - 1F Nitrogen Storage: King Bacterium Drop":             PELoctData(625124, "Hospital: Combat+GC"),
    "Hospital - 13F Research Lab: Chest":                              PELoctData(625125, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Research Lab: Counter":                            PELoctData(625126, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Research Lab: Shelf":                              PELoctData(625127, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Kennel: Chest":                                    PELoctData(625128, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: Lower Chest":                PELoctData(625129, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: Upper Chest":                PELoctData(625130, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: 1st Sparkle (Junk)":         PELoctData(625131, "Hospital: Combat+BC+Fuses"),
    "Hospital - 13F Roof Elevator Access: 2nd Sparkle (Key)":          PELoctData(625132, "Hospital: Combat+BC+Fuses"),
    "Hospital - Roof Spiderwoman: Boss Drop":                          PELoctData(625133, "Hospital: Combat+BC+Fuses+EK+Boss"),
    "Chinatown - Near Entrance: Left Chest":                           PELoctData(625134, "Chinatown: NoReqs|Combat+GK"),
    "Chinatown - Near Entrance: Right Chest":                          PELoctData(625135, "Chinatown: NoReqs|Combat+GK"),
    "Chinatown - Antique Shop Exterior (Save): Lower Chest":           PELoctData(625136, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Exterior (Save): Upper Chest":           PELoctData(625137, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Interior: Chest":                        PELoctData(625138, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Antique Shop Interior: Shelf":                        PELoctData(625139, "Chinatown: Combat|Combat+GK"),
    "Chinatown - End of the Street: Chest":                            PELoctData(625140, "Chinatown: Combat|Combat+GK"),
    "Chinatown - End of the Street: Maeda's Narita":                   PELoctData(625141, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth A-04: Super Tool Sparkle":           PELoctData(625142, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-01: Medicine 4 Chest":             PELoctData(625143, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-03: Cure-D Sparkle":               PELoctData(625144, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth B-06: Ammo Chest":                   PELoctData(625145, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth C-02: Cr Protector Chest":           PELoctData(625146, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth C-06: Range Sparkle":                PELoctData(625147, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-03: M203-3 Chest":                 PELoctData(625148, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-08: M870 Chest":                   PELoctData(625149, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth D-11: Off or Def Chest":             PELoctData(625150, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth E-04: Medicine 3 Chest":             PELoctData(625151, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth E-10: Tool Sparkle":                 PELoctData(625152, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Labyrinth F-09: Offense Chest":                PELoctData(625153, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Sewers Exit Catwalk: Club 3 Chest":                   PELoctData(625154, "Chinatown: Combat|Combat+GK"),
    "Chinatown - Pump Station Exterior: Alligator Chest":              PELoctData(625155, "Chinatown: Combat+Boss|Combat+GK+Boss"),
    "Chinatown - Pump Station Exterior: Catwalk Chest":                PELoctData(625156, "Chinatown: Combat|GK"),
    "Chinatown - Pump Station Control Room: Chest":                    PELoctData(625157, "Chinatown: Combat|GK"),
    "Subway - Platform (Save): Bench Chest":                           PELoctData(625158, "Subway: Combat+PK|GK"),
    "Subway - Platform (Save): Phone Chest":                           PELoctData(625159, "Subway: Combat+PK|GK"),
    "Subway - Exit Stairway: Chest":                                   PELoctData(625160, "Subway: Combat+PK|GK"),
    "Subway - Left Mole Tunnel: Chest":                                PELoctData(625161, "Subway: Combat+PK|Combat+GK"),
    "Subway - Centipede: Boss Drop":                                   PELoctData(625162, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Right Chest":                      PELoctData(625163, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Left Chest":                       PELoctData(625164, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Parked Passenger Car: Lower Chest":                      PELoctData(625165, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Subway - Bridge: Cop's Gate Key":                                 PELoctData(625166, "Subway: Combat+PK+Boss|Combat+GK+Boss"),
    "Warehouse - Outside: Left Chest (Hidden)":                        PELoctData(625167, "Warehouse: NoReqs"),
    "Warehouse - Outside: Right Chest":                                PELoctData(625168, "Warehouse: NoReqs"),
    "Warehouse - Entrance: Forklift Chest":                            PELoctData(625169, "Warehouse: NoReqs"),
    "Warehouse - Tom and Jerry: Chest":                                PELoctData(625170, "Warehouse: Combat"),
    "Warehouse - Tom and Jerry: Key Sparkle":                          PELoctData(625171, "Warehouse: Combat"),
    "Warehouse - Save Room: Ladder Chest":                             PELoctData(625172, "Warehouse: Combat"),
    "Warehouse - Save Room: Upper Ground Chest":                       PELoctData(625173, "Warehouse: Combat"),
    "Warehouse - Save Room: Lower Ground Chest":                       PELoctData(625174, "Warehouse: Combat"),
    "Warehouse - Before Descent: Upper Left Chest":                    PELoctData(625175, "Warehouse: Combat+WK"),
    "Warehouse - Before Descent: Upper Left Chest":                    PELoctData(625176, "Warehouse: Combat+WK"),
    "Warehouse - Before Descent: Lower Left Chest":                    PELoctData(625177, "Warehouse: Combat+WK"),
    "Warehouse - Giant Enemy Crab: Boss Drop":                         PELoctData(625178, "Warehouse: Combat+WK+Boss"),
    "Warehouse - Giant Enemy Crab: Steamed Tool":                      PELoctData(625179, "Warehouse: Combat+WK+Boss"),
    "Museum - 1F Klamp Pursuit East Exhibit: Chest":                   PELoctData(625180, "Museum: NoReqs"),
    "Museum - 1F Klamp Pursuit West Exhibit: Chest":                   PELoctData(625181, "Museum: NoReqs"),
    "Museum - 1F Klamp Pursuit Troodon Hall: Right Chest":             PELoctData(625182, "Museum: Combat"),
    "Museum - 1F Klamp Pursuit Troodon Hall: Left Chest":              PELoctData(625183, "Museum: Combat"),
    "Museum - 1F Rainforest Employee Hallway: Chest":                  PELoctData(625184, "Museum: NoReqs"),
    "Museum - 1F Rainforest Storage Room: Lower Right Chest":          PELoctData(625185, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Lower Center Chest":         PELoctData(625186, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Upper Chest":                PELoctData(625187, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Right Chest":  PELoctData(625188, "Museum: Combat"),
    "Museum - 1F Rainforest Storage Room: Hidden Closet Left Chest":   PELoctData(625189, "Museum: Combat"),
    "Museum - 1F Tribal Staircase: Chest":                             PELoctData(625190, "Museum: Combat"),
    "Museum - 1F Stone Head Room: Ladder Access Chest":                PELoctData(625191, "Museum: Combat"),
    "Museum - 1F Fire Escape: Stat Chest":                             PELoctData(625192, "Museum: Combat"),
    "Museum - 2F Gemstone Staircase: Right Chest":                     PELoctData(625193, "Museum: Combat"),
    "Museum - 2F Gemstone Staircase: Left Chest":                      PELoctData(625194, "Museum: Combat"),
    "Museum - 3F Fire Escape: Rocket Chest":                           PELoctData(625195, "Museum: Combat"),
    "Museum - 2F Festive Lobby: Revive Chest":                         PELoctData(625196, "Museum: Combat"),
    "Museum - 3F Pterodactyl Ambush Hall: Chest":                      PELoctData(625197, "Museum: Combat"),
    "Museum - 3F Stegosaurus Room: Chest":                             PELoctData(625198, "Museum: Combat"),
    "Museum - 2F Museum Shop Tents: Upper Chest":                      PELoctData(625199, "Museum: Combat"),
    "Museum - 2F Museum Shop Tents: Lower Chest":                      PELoctData(625200, "Museum: Combat"),
    "Museum - 2F Security Office: Chest":                              PELoctData(625201, "Museum: Combat"),
    "Museum - 4F Security Storage: Lower Right Chest":                 PELoctData(625202, "Museum: Combat"),
    "Museum - 4F Security Storage: Lower Left Chest":                  PELoctData(625203, "Museum: Combat"),
    "Museum - 4F Security Storage: Upper Left Chest":                  PELoctData(625204, "Museum: Combat"),
    "Museum - 4F Security Storage: Center Chest":                      PELoctData(625205, "Museum: Combat"),
    "Museum - 2F Klamp's Office: Maeda's Gun":                         PELoctData(625206, "Museum: Combat"),
    "Museum - 2F Klamp's Office: Klamp's Key":                         PELoctData(625207, "Museum: Combat"),
    "Museum - 4F Forgotten Landing: Full Recover Chest":               PELoctData(625208, "Museum: Combat"),
    "Museum - 2F Broken Display: Left Chest":                          PELoctData(625209, "Museum: Combat+KK"),
    "Museum - 2F Broken Display: Right Chest":                         PELoctData(625210, "Museum: Combat+KK"),
    "Museum - 3F Triceratops: Boss Drop":                              PELoctData(625211, "Museum: Combat+KK+Boss"),
    "Museum - 1F T-Rex: Left Chest":                                   PELoctData(625212, "Museum: NoReqs"),
    "Museum - 1F T-Rex: Right Chest":                                  PELoctData(625213, "Museum: NoReqs"),
    "Museum - 1F T-Rex: Boss Drop":                                    PELoctData(625214, "Museum: Combat+KK+Boss"),
    "Museum - 3F Final Approach: Right Chest Behind Glass":            PELoctData(625215, "Museum: Combat+KK+Boss"),
    "Museum - 3F Final Approach: Left Chest Behind Glass":             PELoctData(625216, "Museum: Combat+KK+Boss"),
    "Cruiser - Deck: Daniel's Sacrifice":                              PELoctData(625217, "Cruiser"),

    "Chrysler BLDG. - Treasurebox Set 1-01: Offense":                  PELoctData(625218, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: Cr Evade":                 PELoctData(625219, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: Tool":                     PELoctData(625220, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-01: USP-2":                    PELoctData(625221, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Tool A":                   PELoctData(625222, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: M1911A4":                  PELoctData(625223, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Tool B":                   PELoctData(625224, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-02: Sp Vest 2":                PELoctData(625225, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: M16A2":                    PELoctData(625226, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: Tool":                     PELoctData(625227, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-03: Cr Evade":                 PELoctData(625228, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: PE":                       PELoctData(625229, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: Kv Jacket":                PELoctData(625230, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-04: M79-4":                    PELoctData(625231, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: P38 T Card":               PELoctData(625232, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: P228":                     PELoctData(625233, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: PE":                       PELoctData(625234, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-05: Cr Evade":                 PELoctData(625235, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-06: Sv Jacket":                PELoctData(625236, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-06: Cr Evade":                 PELoctData(625237, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: PE":                       PELoctData(625238, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: P226":                     PELoctData(625239, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-07: Defense":                  PELoctData(625240, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Range":                    PELoctData(625241, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Bullet Cap":               PELoctData(625242, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Rocket":                   PELoctData(625243, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-08: Tool":                     PELoctData(625244, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Bullet Cap":               PELoctData(625245, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Offense A":                PELoctData(625246, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 1-09: Offense B":                PELoctData(625247, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - 10F Spiderwoman EX: Boss Drop":                  PELoctData(625248, "Chrysler BLDG.: Key 1"),
    "Chrysler BLDG. - Treasurebox Set 2-01: Cr Jacket":                PELoctData(625249, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-01: Defense":                  PELoctData(625250, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-02: Tool":                     PELoctData(625251, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: Tool A":                   PELoctData(625252, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: Tool B":                   PELoctData(625253, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-03: M203-5":                   PELoctData(625254, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: Tool":                     PELoctData(625255, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: M96":                      PELoctData(625256, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-04: Bullet Cap":               PELoctData(625257, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Kasul T Card":             PELoctData(625258, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Offense":                  PELoctData(625259, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-05: Rocket":                   PELoctData(625260, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Super Tool":               PELoctData(625261, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Club 4":                   PELoctData(625262, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-06: Defense":                  PELoctData(625263, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-07: AM44":                     PELoctData(625264, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-07: P229":                     PELoctData(625265, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-08: PE":                       PELoctData(625266, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-08: Sp Suit 1":                PELoctData(625267, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Full UZ":                  PELoctData(625268, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Range":                    PELoctData(625269, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-09: Bhawk T Card":             PELoctData(625270, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-10: Kv Suit 1":                PELoctData(625271, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 2-10: Tool":                     PELoctData(625272, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - 20F Alligators EX: Boss Drops":                  PELoctData(625273, "Chrysler BLDG.: Key 2"),
    "Chrysler BLDG. - Treasurebox Set 3-01: Tool":                     PELoctData(625274, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: Tool A":                   PELoctData(625275, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: PPKS T Card":              PELoctData(625276, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-02: Tool B":                   PELoctData(625277, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Bullet Cap":               PELoctData(625278, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Tool":                     PELoctData(625279, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-03: Super Tool":               PELoctData(625280, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Super Tool":               PELoctData(625281, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Cr Evade":                 PELoctData(625282, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-04: Mark 23":                  PELoctData(625283, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: Offense":                  PELoctData(625284, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: Tool":                     PELoctData(625285, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-05: M870-2":                   PELoctData(625286, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-06: Type64":                   PELoctData(625287, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-06: Defense":                  PELoctData(625288, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-07: Cm Jacket":                PELoctData(625289, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: B Jacket 2":               PELoctData(625290, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: M1 T Card":                PELoctData(625291, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-08: Offense":                  PELoctData(625292, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-09: Range":                    PELoctData(625293, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-09: Cr Evade":                 PELoctData(625294, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: Tool":                     PELoctData(625295, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: Sv Suit 1":                PELoctData(625296, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 3-10: M79-5":                    PELoctData(625297, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - 30F Centipede EX: Boss Drop":                    PELoctData(625298, "Chrysler BLDG.: Key 3"),
    "Chrysler BLDG. - Treasurebox Set 4-01: PSG-1":                    PELoctData(625299, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Tool":                     PELoctData(625300, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Full Cure":                PELoctData(625301, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-01: Bullet Cap":               PELoctData(625302, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Cm Suit 1":                PELoctData(625303, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Tool":                     PELoctData(625304, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-02: Full Recover":             PELoctData(625305, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Tool":                     PELoctData(625306, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Rocket":                   PELoctData(625307, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Defense":                  PELoctData(625308, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-03: Sv Suit 2":                PELoctData(625309, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: MP5A5":                    PELoctData(625310, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: MK5 T Card":               PELoctData(625311, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: Sp Armor 1":               PELoctData(625312, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-04: BAR T Card":               PELoctData(625313, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-05: Tool":                     PELoctData(625314, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-06: MP44 T Card":              PELoctData(625315, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: MG42 T Card":              PELoctData(625316, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: Cr Evade":                 PELoctData(625317, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: M1911A5":                  PELoctData(625318, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-07: Defense":                  PELoctData(625319, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-08: Maverick":                 PELoctData(625320, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-08: Range":                    PELoctData(625321, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-09: Kv Armor 1":               PELoctData(625322, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 4-10: Tool":                     PELoctData(625323, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - 40F Triceratops EX: Boss Drop":                  PELoctData(625324, "Chrysler BLDG.: Key 4"),
    "Chrysler BLDG. - Treasurebox Set 5-01: SAR":                      PELoctData(625325, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-01: Tool":                     PELoctData(625326, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-01: M29 T Card":               PELoctData(625327, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: M73 T Card":               PELoctData(625328, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: PE":                       PELoctData(625329, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: Super Tool":               PELoctData(625330, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-02: AT4-1":                    PELoctData(625331, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-03: Tool":                     PELoctData(625332, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-03: Bullet Cap":               PELoctData(625333, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-04: Cr Suit 1":                PELoctData(625334, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-05: USP-3":                    PELoctData(625335, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Offense":                  PELoctData(625336, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Rocket":                   PELoctData(625337, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Cm Armor 1":               PELoctData(625338, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Tool":                     PELoctData(625339, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-06: Range":                    PELoctData(625340, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-07: Tool":                     PELoctData(625341, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-08: B Suit 1":                 PELoctData(625342, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: G20":                      PELoctData(625343, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Tool":                     PELoctData(625344, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Offense":                  PELoctData(625345, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 5-09: Sv Armor 1":               PELoctData(625346, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - 50F Cockroach - Boss Drop":                      PELoctData(625347, "Chrysler BLDG.: Key 5"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Type38 T Card":            PELoctData(625348, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Cr Evade":                 PELoctData(625349, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-01: Sp Armor 2":               PELoctData(625350, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-02: Rocket":                   PELoctData(625351, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-02: MP5SD6":                   PELoctData(625352, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-03: B Suit 2":                 PELoctData(625353, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-04: M712":                     PELoctData(625354, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: S12":                      PELoctData(625355, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: PE":                       PELoctData(625356, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: Full Recover":             PELoctData(625357, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-05: Cr Armor 1":               PELoctData(625358, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-06: Full Cure":                PELoctData(625359, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-07: FA-MAS":                   PELoctData(625360, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-08: Range":                    PELoctData(625361, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool A":                   PELoctData(625362, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool B":                   PELoctData(625363, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 6-09: Tool C":                   PELoctData(625364, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - 60F Giant Enemy Crab EX - Boss Drop":            PELoctData(625365, "Chrysler BLDG.: Key 6"),
    "Chrysler BLDG. - Treasurebox Set 7-01: PE":                       PELoctData(625366, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: M500-2":                   PELoctData(625367, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: Full Recover":             PELoctData(625368, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-01: M500":                     PELoctData(625369, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-02: Defense":                  PELoctData(625370, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: XM177E2":                  PELoctData(625371, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Tool":                     PELoctData(625372, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Range":                    PELoctData(625373, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-03: Full Cure":                PELoctData(625374, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Super Tool":               PELoctData(625375, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Cm Armor 2":               PELoctData(625376, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-04: Bullet Cap":               PELoctData(625377, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: B Armor":                  PELoctData(625378, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: M96R":                     PELoctData(625379, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: Super Tool":               PELoctData(625380, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-05: Tool":                     PELoctData(625381, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-06: Type3 T Card":             PELoctData(625382, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: M203-6":                   PELoctData(625383, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: Offense":                  PELoctData(625384, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-07: Sv Armor 2":               PELoctData(625385, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Eagle T Card":             PELoctData(625386, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: PE":                       PELoctData(625387, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Club 5":                   PELoctData(625388, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - Treasurebox Set 7-08: Cr Armor 2":               PELoctData(625389, "Chrysler BLDG.: Key 7"),
    "Chrysler BLDG. - 70F Queen Bee: Boss Drop":                       PELoctData(625390, "Chrysler BLDG.: Key 7"),

    "PE - Heal 1: Awakening":                                          PELoctData(625391, "Carnegie Hall: NoReqs"),
    "PE - Scan: Level 4":                                              PELoctData(625392, "PE"),
    "PE - Slow: Level 7":                                              PELoctData(625393, "PE"),
    "PE - Detox: Level 9":                                             PELoctData(625394, "PE"),
    "PE - Heal 2: Level 11":                                           PELoctData(625395, "PE"),
    "PE - Barrier: Level 13":                                          PELoctData(625396, "PE"),
    "PE - Energy Shot: Level 15":                                      PELoctData(625397, "PE"),
    "PE - Confuse: Level 17":                                          PELoctData(625398, "PE"),
    "PE - Haste: Level 20":                                            PELoctData(625399, "PE"),
    "PE - Heal 3: Level 22":                                           PELoctData(625400, "PE"),
    "PE - Gene Heal: Level 25":                                        PELoctData(625401, "PE"),
    "PE - Medic: Level 28":                                            PELoctData(625402, "PE"),
    "PE - Preraise: Level 30":                                         PELoctData(625403, "PE"),
    "PE - Full Recover: Level 32":                                     PELoctData(625404, "PE"),
    "PE - Liberate: Level 33":                                         PELoctData(625405, "PE"),

    "Level Stat - Offense: 2":                                         PELoctData(625406, "LevelStat"),
    "Level Stat - Defense: 2":                                         PELoctData(625407, "LevelStat"),
    "Level Stat - P.Energy: 2":                                        PELoctData(625408, "LevelStat"),
    "Level Stat - StatusRcvr: 2":                                      PELoctData(625409, "LevelStat"),
    "Level Stat - ActiveTime: 2":                                      PELoctData(625410, "LevelStat"),
    "Level Stat - ItemCapcty: 2":                                      PELoctData(625411, "LevelStat"),
    "Level Stat - Offense: 3":                                         PELoctData(625412, "LevelStat"),
    "Level Stat - Defense: 3":                                         PELoctData(625413, "LevelStat"),
    "Level Stat - P.Energy: 3":                                        PELoctData(625414, "LevelStat"),
    "Level Stat - StatusRcvr: 3":                                      PELoctData(625415, "LevelStat"),
    "Level Stat - ActiveTime: 3":                                      PELoctData(625416, "LevelStat"),
    "Level Stat - ItemCapcty: 3":                                      PELoctData(625417, "LevelStat"),
    "Level Stat - Offense: 4":                                         PELoctData(625418, "LevelStat"),
    "Level Stat - Defense: 4":                                         PELoctData(625419, "LevelStat"),
    "Level Stat - P.Energy: 4":                                        PELoctData(625420, "LevelStat"),
    "Level Stat - StatusRcvr: 4":                                      PELoctData(625421, "LevelStat"),
    "Level Stat - ActiveTime: 4":                                      PELoctData(625422, "LevelStat"),
    "Level Stat - ItemCapcty: 4":                                      PELoctData(625423, "LevelStat"),
    "Level Stat - Offense: 5":                                         PELoctData(625424, "LevelStat"),
    "Level Stat - Defense: 5":                                         PELoctData(625425, "LevelStat"),
    "Level Stat - P.Energy: 5":                                        PELoctData(625426, "LevelStat"),
    "Level Stat - StatusRcvr: 5":                                      PELoctData(625427, "LevelStat"),
    "Level Stat - ActiveTime: 5":                                      PELoctData(625428, "LevelStat"),
    "Level Stat - ItemCapcty: 5":                                      PELoctData(625429, "LevelStat"),
    "Level Stat - Offense: 6":                                         PELoctData(625430, "LevelStat"),
    "Level Stat - Defense: 6":                                         PELoctData(625431, "LevelStat"),
    "Level Stat - P.Energy: 6":                                        PELoctData(625432, "LevelStat"),
    "Level Stat - StatusRcvr: 6":                                      PELoctData(625433, "LevelStat"),
    "Level Stat - ActiveTime: 6":                                      PELoctData(625434, "LevelStat"),
    "Level Stat - ItemCapcty: 6":                                      PELoctData(625435, "LevelStat"),
    "Level Stat - Offense: 7":                                         PELoctData(625436, "LevelStat"),
    "Level Stat - Defense: 7":                                         PELoctData(625437, "LevelStat"),
    "Level Stat - P.Energy: 7":                                        PELoctData(625438, "LevelStat"),
    "Level Stat - StatusRcvr: 7":                                      PELoctData(625439, "LevelStat"),
    "Level Stat - ActiveTime: 7":                                      PELoctData(625440, "LevelStat"),
    "Level Stat - ItemCapcty: 7":                                      PELoctData(625441, "LevelStat"),
    "Level Stat - Offense: 8":                                         PELoctData(625442, "LevelStat"),
    "Level Stat - Defense: 8":                                         PELoctData(625443, "LevelStat"),
    "Level Stat - P.Energy: 8":                                        PELoctData(625444, "LevelStat"),
    "Level Stat - StatusRcvr: 8":                                      PELoctData(625445, "LevelStat"),
    "Level Stat - ActiveTime: 8":                                      PELoctData(625446, "LevelStat"),
    "Level Stat - ItemCapcty: 8":                                      PELoctData(625447, "LevelStat"),
    "Level Stat - Offense: 9":                                         PELoctData(625448, "LevelStat"),
    "Level Stat - Defense: 9":                                         PELoctData(625449, "LevelStat"),
    "Level Stat - P.Energy: 9":                                        PELoctData(625450, "LevelStat"),
    "Level Stat - StatusRcvr: 9":                                      PELoctData(625451, "LevelStat"),
    "Level Stat - ActiveTime: 9":                                      PELoctData(625452, "LevelStat"),
    "Level Stat - ItemCapcty: 9":                                      PELoctData(625453, "LevelStat"),
    "Level Stat - Offense: 10":                                        PELoctData(625454, "LevelStat"),
    "Level Stat - Defense: 10":                                        PELoctData(625455, "LevelStat"),
    "Level Stat - P.Energy: 10":                                       PELoctData(625456, "LevelStat"),
    "Level Stat - StatusRcvr: 10":                                     PELoctData(625457, "LevelStat"),
    "Level Stat - ActiveTime: 10":                                     PELoctData(625458, "LevelStat"),
    "Level Stat - ItemCapcty: 10":                                     PELoctData(625459, "LevelStat"),
    "Level Stat - Offense: 11":                                        PELoctData(625460, "LevelStat"),
    "Level Stat - Defense: 11":                                        PELoctData(625461, "LevelStat"),
    "Level Stat - P.Energy: 11":                                       PELoctData(625462, "LevelStat"),
    "Level Stat - StatusRcvr: 11":                                     PELoctData(625463, "LevelStat"),
    "Level Stat - ActiveTime: 11":                                     PELoctData(625464, "LevelStat"),
    "Level Stat - ItemCapcty: 11":                                     PELoctData(625465, "LevelStat"),
    "Level Stat - Offense: 12":                                        PELoctData(625466, "LevelStat"),
    "Level Stat - Defense: 12":                                        PELoctData(625467, "LevelStat"),
    "Level Stat - P.Energy: 12":                                       PELoctData(625468, "LevelStat"),
    "Level Stat - StatusRcvr: 12":                                     PELoctData(625469, "LevelStat"),
    "Level Stat - ActiveTime: 12":                                     PELoctData(625470, "LevelStat"),
    "Level Stat - ItemCapcty: 12":                                     PELoctData(625471, "LevelStat"),
    "Level Stat - Offense: 13":                                        PELoctData(625472, "LevelStat"),
    "Level Stat - Defense: 13":                                        PELoctData(625473, "LevelStat"),
    "Level Stat - P.Energy: 13":                                       PELoctData(625474, "LevelStat"),
    "Level Stat - StatusRcvr: 13":                                     PELoctData(625475, "LevelStat"),
    "Level Stat - ActiveTime: 13":                                     PELoctData(625476, "LevelStat"),
    "Level Stat - ItemCapcty: 13":                                     PELoctData(625477, "LevelStat"),
    "Level Stat - Offense: 14":                                        PELoctData(625478, "LevelStat"),
    "Level Stat - Defense: 14":                                        PELoctData(625479, "LevelStat"),
    "Level Stat - P.Energy: 14":                                       PELoctData(625480, "LevelStat"),
    "Level Stat - StatusRcvr: 14":                                     PELoctData(625481, "LevelStat"),
    "Level Stat - ActiveTime: 14":                                     PELoctData(625482, "LevelStat"),
    "Level Stat - ItemCapcty: 14":                                     PELoctData(625483, "LevelStat"),
    "Level Stat - Offense: 15":                                        PELoctData(625484, "LevelStat"),
    "Level Stat - Defense: 15":                                        PELoctData(625485, "LevelStat"),
    "Level Stat - P.Energy: 15":                                       PELoctData(625486, "LevelStat"),
    "Level Stat - StatusRcvr: 15":                                     PELoctData(625487, "LevelStat"),
    "Level Stat - ActiveTime: 15":                                     PELoctData(625488, "LevelStat"),
    "Level Stat - ItemCapcty: 15":                                     PELoctData(625489, "LevelStat"),
    "Level Stat - Offense: 16":                                        PELoctData(625490, "LevelStat"),
    "Level Stat - Defense: 16":                                        PELoctData(625491, "LevelStat"),
    "Level Stat - P.Energy: 16":                                       PELoctData(625492, "LevelStat"),
    "Level Stat - StatusRcvr: 16":                                     PELoctData(625493, "LevelStat"),
    "Level Stat - ActiveTime: 16":                                     PELoctData(625494, "LevelStat"),
    "Level Stat - ItemCapcty: 16":                                     PELoctData(625495, "LevelStat"),
    "Level Stat - Offense: 17":                                        PELoctData(625496, "LevelStat"),
    "Level Stat - Defense: 17":                                        PELoctData(625497, "LevelStat"),
    "Level Stat - P.Energy: 17":                                       PELoctData(625498, "LevelStat"),
    "Level Stat - StatusRcvr: 17":                                     PELoctData(625499, "LevelStat"),
    "Level Stat - ActiveTime: 17":                                     PELoctData(625500, "LevelStat"),
    "Level Stat - ItemCapcty: 17":                                     PELoctData(625501, "LevelStat"),
    "Level Stat - Offense: 18":                                        PELoctData(625502, "LevelStat"),
    "Level Stat - Defense: 18":                                        PELoctData(625503, "LevelStat"),
    "Level Stat - P.Energy: 18":                                       PELoctData(625504, "LevelStat"),
    "Level Stat - StatusRcvr: 18":                                     PELoctData(625505, "LevelStat"),
    "Level Stat - ActiveTime: 18":                                     PELoctData(625506, "LevelStat"),
    "Level Stat - ItemCapcty: 18":                                     PELoctData(625507, "LevelStat"),
    "Level Stat - Offense: 19":                                        PELoctData(625508, "LevelStat"),
    "Level Stat - Defense: 19":                                        PELoctData(625509, "LevelStat"),
    "Level Stat - P.Energy: 19":                                       PELoctData(625510, "LevelStat"),
    "Level Stat - StatusRcvr: 19":                                     PELoctData(625511, "LevelStat"),
    "Level Stat - ActiveTime: 19":                                     PELoctData(625512, "LevelStat"),
    "Level Stat - ItemCapcty: 19":                                     PELoctData(625513, "LevelStat"),
    "Level Stat - Offense: 20":                                        PELoctData(625514, "LevelStat"),
    "Level Stat - Defense: 20":                                        PELoctData(625515, "LevelStat"),
    "Level Stat - P.Energy: 20":                                       PELoctData(625516, "LevelStat"),
    "Level Stat - StatusRcvr: 20":                                     PELoctData(625517, "LevelStat"),
    "Level Stat - ActiveTime: 20":                                     PELoctData(625518, "LevelStat"),
    "Level Stat - ItemCapcty: 20":                                     PELoctData(625519, "LevelStat"),
    "Level Stat - Offense: 21":                                        PELoctData(625520, "LevelStat"),
    "Level Stat - Defense: 21":                                        PELoctData(625521, "LevelStat"),
    "Level Stat - P.Energy: 21":                                       PELoctData(625522, "LevelStat"),
    "Level Stat - StatusRcvr: 21":                                     PELoctData(625523, "LevelStat"),
    "Level Stat - ActiveTime: 21":                                     PELoctData(625524, "LevelStat"),
    "Level Stat - ItemCapcty: 21":                                     PELoctData(625525, "LevelStat"),
    "Level Stat - Offense: 22":                                        PELoctData(625526, "LevelStat"),
    "Level Stat - Defense: 22":                                        PELoctData(625527, "LevelStat"),
    "Level Stat - P.Energy: 22":                                       PELoctData(625528, "LevelStat"),
    "Level Stat - StatusRcvr: 22":                                     PELoctData(625529, "LevelStat"),
    "Level Stat - ActiveTime: 22":                                     PELoctData(625530, "LevelStat"),
    "Level Stat - ItemCapcty: 22":                                     PELoctData(625531, "LevelStat"),
    "Level Stat - Offense: 23":                                        PELoctData(625532, "LevelStat"),
    "Level Stat - Defense: 23":                                        PELoctData(625533, "LevelStat"),
    "Level Stat - P.Energy: 23":                                       PELoctData(625534, "LevelStat"),
    "Level Stat - StatusRcvr: 23":                                     PELoctData(625535, "LevelStat"),
    "Level Stat - ActiveTime: 23":                                     PELoctData(625536, "LevelStat"),
    "Level Stat - ItemCapcty: 23":                                     PELoctData(625537, "LevelStat"),
    "Level Stat - Offense: 24":                                        PELoctData(625538, "LevelStat"),
    "Level Stat - Defense: 24":                                        PELoctData(625539, "LevelStat"),
    "Level Stat - P.Energy: 24":                                       PELoctData(625540, "LevelStat"),
    "Level Stat - StatusRcvr: 24":                                     PELoctData(625541, "LevelStat"),
    "Level Stat - ActiveTime: 24":                                     PELoctData(625542, "LevelStat"),
    "Level Stat - ItemCapcty: 24":                                     PELoctData(625543, "LevelStat"),
    "Level Stat - Offense: 25":                                        PELoctData(625544, "LevelStat"),
    "Level Stat - Defense: 25":                                        PELoctData(625545, "LevelStat"),
    "Level Stat - P.Energy: 25":                                       PELoctData(625546, "LevelStat"),
    "Level Stat - StatusRcvr: 25":                                     PELoctData(625547, "LevelStat"),
    "Level Stat - ActiveTime: 25":                                     PELoctData(625548, "LevelStat"),
    "Level Stat - ItemCapcty: 25":                                     PELoctData(625549, "LevelStat"),
    "Level Stat - Offense: 26":                                        PELoctData(625550, "LevelStat"),
    "Level Stat - Defense: 26":                                        PELoctData(625551, "LevelStat"),
    "Level Stat - P.Energy: 26":                                       PELoctData(625552, "LevelStat"),
    "Level Stat - StatusRcvr: 26":                                     PELoctData(625553, "LevelStat"),
    "Level Stat - ActiveTime: 26":                                     PELoctData(625554, "LevelStat"),
    "Level Stat - ItemCapcty: 26":                                     PELoctData(625555, "LevelStat"),
    "Level Stat - Offense: 27":                                        PELoctData(625556, "LevelStat"),
    "Level Stat - Defense: 27":                                        PELoctData(625557, "LevelStat"),
    "Level Stat - P.Energy: 27":                                       PELoctData(625558, "LevelStat"),
    "Level Stat - StatusRcvr: 27":                                     PELoctData(625559, "LevelStat"),
    "Level Stat - ActiveTime: 27":                                     PELoctData(625560, "LevelStat"),
    "Level Stat - ItemCapcty: 27":                                     PELoctData(625561, "LevelStat"),
    "Level Stat - Offense: 28":                                        PELoctData(625562, "LevelStat"),
    "Level Stat - Defense: 28":                                        PELoctData(625563, "LevelStat"),
    "Level Stat - P.Energy: 28":                                       PELoctData(625564, "LevelStat"),
    "Level Stat - StatusRcvr: 28":                                     PELoctData(625565, "LevelStat"),
    "Level Stat - ActiveTime: 28":                                     PELoctData(625566, "LevelStat"),
    "Level Stat - ItemCapcty: 28":                                     PELoctData(625567, "LevelStat"),
    "Level Stat - Offense: 29":                                        PELoctData(625568, "LevelStat"),
    "Level Stat - Defense: 29":                                        PELoctData(625569, "LevelStat"),
    "Level Stat - P.Energy: 29":                                       PELoctData(625570, "LevelStat"),
    "Level Stat - StatusRcvr: 29":                                     PELoctData(625571, "LevelStat"),
    "Level Stat - ActiveTime: 29":                                     PELoctData(625572, "LevelStat"),
    "Level Stat - ItemCapcty: 29":                                     PELoctData(625573, "LevelStat"),
    "Level Stat - Offense: 30":                                        PELoctData(625574, "LevelStat"),
    "Level Stat - Defense: 30":                                        PELoctData(625575, "LevelStat"),
    "Level Stat - P.Energy: 30":                                       PELoctData(625576, "LevelStat"),
    "Level Stat - StatusRcvr: 30":                                     PELoctData(625577, "LevelStat"),
    "Level Stat - ActiveTime: 30":                                     PELoctData(625578, "LevelStat"),
    "Level Stat - ItemCapcty: 30":                                     PELoctData(625579, "LevelStat"),
    "Level Stat - Offense: 31":                                        PELoctData(625580, "LevelStat"),
    "Level Stat - Defense: 31":                                        PELoctData(625581, "LevelStat"),
    "Level Stat - P.Energy: 31":                                       PELoctData(625582, "LevelStat"),
    "Level Stat - StatusRcvr: 31":                                     PELoctData(625583, "LevelStat"),
    "Level Stat - ActiveTime: 31":                                     PELoctData(625584, "LevelStat"),
    "Level Stat - ItemCapcty: 31":                                     PELoctData(625585, "LevelStat"),
    "Level Stat - Offense: 32":                                        PELoctData(625586, "LevelStat"),
    "Level Stat - Defense: 32":                                        PELoctData(625587, "LevelStat"),
    "Level Stat - P.Energy: 32":                                       PELoctData(625588, "LevelStat"),
    "Level Stat - StatusRcvr: 32":                                     PELoctData(625589, "LevelStat"),
    "Level Stat - ActiveTime: 32":                                     PELoctData(625590, "LevelStat"),
    "Level Stat - ItemCapcty: 32":                                     PELoctData(625591, "LevelStat"),
    "Level Stat - Offense: 33":                                        PELoctData(625592, "LevelStat"),
    "Level Stat - Defense: 33":                                        PELoctData(625593, "LevelStat"),
    "Level Stat - P.Energy: 33":                                       PELoctData(625594, "LevelStat"),
    "Level Stat - StatusRcvr: 33":                                     PELoctData(625595, "LevelStat"),
    "Level Stat - ActiveTime: 33":                                     PELoctData(625596, "LevelStat"),
    "Level Stat - ItemCapcty: 33":                                     PELoctData(625597, "LevelStat"),
    "Level Stat - Offense: 34":                                        PELoctData(625598, "LevelStat+UnrChks"),
    "Level Stat - Defense: 34":                                        PELoctData(625599, "LevelStat+UnrChks"),
    "Level Stat - P.Energy: 34":                                       PELoctData(625600, "LevelStat+UnrChks"),
    "Level Stat - StatusRcvr: 34":                                     PELoctData(625601, "LevelStat+UnrChks"),
    "Level Stat - ActiveTime: 34":                                     PELoctData(625602, "LevelStat+UnrChks"),
    "Level Stat - ItemCapcty: 34":                                     PELoctData(625603, "LevelStat+UnrChks"),
    "Level Stat - Offense: 35":                                        PELoctData(625604, "LevelStat+UnrChks"),
    "Level Stat - Defense: 35":                                        PELoctData(625605, "LevelStat+UnrChks"),
    "Level Stat - P.Energy: 35":                                       PELoctData(625606, "LevelStat+UnrChks"),
    "Level Stat - StatusRcvr: 35":                                     PELoctData(625607, "LevelStat+UnrChks"),
    "Level Stat - ActiveTime: 35":                                     PELoctData(625608, "LevelStat+UnrChks"),
    "Level Stat - ItemCapcty: 35":                                     PELoctData(625609, "LevelStat+UnrChks"),
    "Level Stat - Offense: 36":                                        PELoctData(625610, "LevelStat+UnrChks"),
    "Level Stat - Defense: 36":                                        PELoctData(625611, "LevelStat+UnrChks"),
    "Level Stat - P.Energy: 36":                                       PELoctData(625612, "LevelStat+UnrChks"),
    "Level Stat - StatusRcvr: 36":                                     PELoctData(625613, "LevelStat+UnrChks"),
    "Level Stat - ActiveTime: 36":                                     PELoctData(625614, "LevelStat+UnrChks"),
    "Level Stat - ItemCapcty: 36":                                     PELoctData(625615, "LevelStat+UnrChks"),
}

location_table = {name: data.address for name, data in location_data_table.items() if data.address is not None}
